src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurgeSobjectSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting controls which entities to be purged and the history of records to be saved while purging.</description>
    <fields>
        <fullName>Enable_Purge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked only then the corresponding entry will be picked for Purging.</description>
        <label>Enable Purge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Save_History__c</fullName>
        <description>Number of days of data to be saved when the purge batch runs. If set to 10, last 10 days of data will be saved and rest deleted. If set to 0, all data will be deleted.</description>
        <label>Save_History</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Where_Clause__c</fullName>
        <description>Provides optional where clause for building the SOQL to fetch qualified records for purging.</description>
        <label>Where_Clause</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <label>order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>PurgeSobjectSettings</label>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/classes/batchPurgeSobjectEntriesTest.cls
/* 
 * Name: batchPurgeSobjectEntriesTest
 * Type: Apex Test Coverage  
 * Description: Test coverage for the batchPurgeSobjectEntries Apex Batch Class.         
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         03/21/2016       1. Initial Version created
 */
@isTest(SeeAllData=false) 
private class batchPurgeSobjectEntriesTest {

    static testMethod void batchPurgeSobjectEntries_UnitTest() {
      
        PurgeSobjectSettings__c tstPSRec = new PurgeSobjectSettings__c(Name='Account',Enable_Purge__c=true,Save_History__c=0,Where_Clause__c='Name Like \'TSTBPS%\'',order__c=1);
        Insert tstPSRec;

        List<Account> lstAccTst = new List<Account>();
        for(Integer i=0;i<1500;i++){
            Account acc = new Account(Name='TSTBPS'+i,Billing_Entity__c='Dynegy');
            lstAccTst.add(acc);
        }
        insert lstAccTst;
        
        String CRON_EXP = '0 0 * * * ?';
        Test.startTest();                
        String jobId = System.schedule('batchPurgeSobjectEntriesTest',CRON_EXP,new batchPurgeSobjectEntries(1));    
        Test.stopTest(); 
    }
}