src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LodeStar_Integration_Status__c</fullName>
        <description>The Status of this record as it relates to LodeStar having the most up-to-date information.</description>
        <inlineHelpText>Indicates the data was sent to Lodestar, but does not confirm it was received successfully.  The field must be in &quot;Not Synchronized.&quot; See Document &quot;SF to LS Integration.docx&quot; for more details.</inlineHelpText>
        <label>LodeStar Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Synchronized</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Synchronized</fullName>
                </value>
                <value>
                    <fullName>Test Synchronized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSynchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</description>
        <inlineHelpText>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</inlineHelpText>
        <label>Is Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <label>Term Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler.cls
/**
 * the purpose of this class is to provide methods that can be used in the 
 * AccountTrigger.
 *
 * @author Chris Gary <cgary@cloudperformer.com>
 * @version 1.0
 * @version 1.1 Prasad Paladugu Modified for solving 101 SOQL Queries
 * @vesrion 1.2 Prasad Paladugu Created a bacth class handler for requirement
 * @version 1.3 Nanda Eluru Appended another batch class to same class handler 
 * @version 1.4 Nanda Eluru Worked for 10001 DML 
 **/
global class AccountTriggerHandler {

    global static Boolean parentAccountUpdateToChildAcctUpdateRun = false;

    public static void SetChildAccountsToNotSynchronized(Set<Id> parentAccountId,String runJob){
        //first we need to make sure this has not run already
        if(!AccountTriggerHandler.parentAccountUpdateToChildAcctUpdateRun){
            //List<Account> childAccountsToUpdate = new List<Account>();
            AccountTriggerHandler.parentAccountUpdateToChildAcctUpdateRun = true;
            //now grab all of the Child Account Records of the selected Parents and set them to 'Not Synchronized'
            system.debug(' RUN JOB : '+runJob);
            if(runJob == 'Person'){
                AccountTriggerHandlerBatch childAccBatch = new AccountTriggerHandlerBatch(parentAccountId,runJob);
                if(!BatchUtility.IsconcurrentjobsRunning()){
                    Database.executebatch(childAccBatch,1000);
                }
                else{
                    System.scheduleBatch(childAccBatch, 'Re-Scheduled AccountTriggerBatch @ '+Datetime.now(), 5,1000);
                }
            }
        }
    }

 
    public static void setLDCNotSynchronized(Set<Id> accountId,String runJob) {    //, boolean runJob2
    	system.debug('>>>>>>>>>>>>>>>>>*******' + accountId);
        if(!accountId.isempty() && accountId.size() > 0){
            AccountTriggerHandlerBatch childAccBatch = new AccountTriggerHandlerBatch(accountId,runJob);
            system.debug('=========childAccBatch============='+childAccBatch); 
            if(!BatchUtility.IsconcurrentjobsRunning()){
                Database.executebatch(childAccBatch,1000);
            }
            else{
                System.scheduleBatch(childAccBatch, 'Re-Scheduled AccountTriggerBatch @ '+Datetime.now(), 5,1000);
            }
        }
    }
 } 
    
    /*Commented out by Nanda for DML 10001
        for (Contract_LDC__c contractLDC :[SELECT Id,Term_Start_Date__c, IsSynchronized__c,Contract__c,Contract__r.Account.id, LDC_Account__r.Account__r.id FROM Contract_LDC__c
                                           WHERE Contract__r.Account.id IN :accountId or LDC_Account__r.Account__r.id IN :accountId order by Term_Start_Date__c ASC ]) {
             
            system.debug(contractLDC.Contract__r.Account.id);
            if (contractLDC.Contract__r.Account.id != null){
                //cmap.put(contractLDC.Contract__r.Account.id, contractLDC);
                system.debug(contractLDC.LDC_Account__r.Account__r.id);
                if (contractLDC.LDC_Account__r.Account__r.id != null){
                    system.debug('insider main condition');
                    cmap.put(contractLDC.LDC_Account__r.Account__r.id, contractLDC);
                }
            }
        }
        system.debug(cmap);
        lclc = cmap.values();
            
        system.debug('>>>>>>>>>>>>>>>>>*******' + cmap);
        system.debug('>>>>>>>>>>>>>>>>>*******' + lclc);
        for (Contract_LDC__c clc : lclc) {
            clcmap.put(clc.id, clc);
        }
            
        lclc = clcmap.values();
    
        for (Contract_LDC__c clc : lclc) {
            if (clc.IsSynchronized__c != false){
                clc.IsSynchronized__c = false;
                //for SCR:1186 To upadte only modified records
                finalUpdateCLdc.add(clc);
            }
        }
       
       system.debug('=====finalupdateCLdc================'+finalUpdateCLdc);
       if (!finalUpdateCLdc.isempty()) update finalUpdateCLdc; 
   }
}*/

/* OLD CODE Commented Out for 101 SOQL Queries
for(Account a : acc){
    a.LodeStar_Integration_Status__c = 'Not Synchronized';
    childAccountsToUpdate.add(a);
}
if(!childAccountsToUpdate.isEmpty()) {
    if(childAccountsToUpdate.size() >= 1000){
    //list<AsyncApexJob> runningjob = [SELECT ApexClass.name,ExtendedStatus,Id,JobItemsProcessed,JobType,MethodName,Status FROM AsyncApexJob where ApexClass.name='AccountTriggerHandlerBatch' and Status= 'Processing'];
    /*system.debug(' RUN JOB : '+runJob);
    if(runJob){
        AccountTriggerHandlerBatch childAccBatch = new AccountTriggerHandlerBatch(parentAccountId);
        if(!BatchUtility.IsconcurrentjobsRunning()){
            Database.executebatch(childAccBatch,1000);
        }
        else{
            System.scheduleBatch(childAccBatch, 'Re-Scheduled BatchCNIEnrollmentProcess @ '+Datetime.now(), 5,1000);
        }
        runJob = false;
    }*/