src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Business Account for Person Account (Used for MuniAgg, MassMarket etc)</description>
        <inlineHelpText>Related Business Customer for Individual Customer (Used for MuniAgg, MassMarket etc)</inlineHelpText>
        <label>Business Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Mass_Market_Offer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Muni_Agg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>BusinessAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerPLC__c</fullName>
        <label>Customer PLC</label>
        <precision>17</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDC_Individual_Info__c</fullName>
        <label>LDC Individual Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Acct_ADU__c</fullName>
        <label>Acct ADU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capacity_PLC1__c</fullName>
        <label>Capacity PLC1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capacity_PLC2__c</fullName>
        <label>Capacity PLC2</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FRM_Profile__c</fullName>
        <label>FRM Profile</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Record_updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Record updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NSPL1_KW__c</fullName>
        <label>NSPL1 KW</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSPL2_KW__c</fullName>
        <label>NSPL2 KW</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Pk_Kwh__c</fullName>
        <label>Off Pk Kwh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_PK_Kwh__c</fullName>
        <label>On PK Kwh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <inlineHelpText>Populated by the Pricing Webscrape.  It matches the LDC Rate Class on the Meter level.  This field is sent to Lodestar the tag field &quot;Rate Code.&quot;</inlineHelpText>
        <label>Utility Rate Class</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Zone__c</fullName>
        <label>Utility Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LDC_Individual_Info__c</fullName>
        <label>LDC Individual Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LDCinfo.cls
/* 
 * Name: LDCinfo
 * Type: Apex Class
 * Test Class: LDC Trigger
 * Description:  This batch class is to calculate the loads for each business customer when loads are changed for sending to ENDUR. 
 * Change History:
 *=====================================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Prasad Paladugu              01/13/2017       1. Initial Version created
 * 2.0         Prasad Paladugu              03/27/2017       1. Updated the calculations
 * 3.0         Prasad Paladugu              05/09/2017       1. skipped the process for Muni-Agg
 * 4.0         Prasad Paladugu              06/15/2017       1. Added a functionality to calculate at opportunity level for C&I Customers
 * 5.0         Prasad Paladugu              09/25/2017       1. Updated the class performance
 															 2. Revised the calculations
 */
global class LDCinfo implements Database.Batchable<sObject>,Database.Stateful,System.Schedulable {
    
    //global final set<id> ldcset;
    global final set<id> accset;
    //global final string ObjName;
    global map<id,map<string,cusWrapper>> accldcstrmap;
    global map<id,map<string,cusWrapper>> oppldcstrmap;
    global decimal CapacitySum;
    public cusWrapper cwrapper {get;set;}
    
    global void execute (SchedulableContext sc){
        system.debug('Executing through Schedulable Context .........');
        set<id> setacc = new set<id>();
        for(ldc_account__c ldc : [select id,account__c,account__r.business_account__c from ldc_account__c where Is_Record_updated__c = true ]){
            if(ldc.account__r.business_account__c != null)
                setacc.add(ldc.account__r.business_account__c);
            else
                setacc.add(ldc.account__c);
        }
        if(!setacc.isempty()){
            LDCInfo ldc = new LDCinfo(setacc);
            Database.executeBatch(ldc,500);
        }
    }
    
    public LDCinfo(set<id> setacc){
        accset = setacc;
    }
    
    public LDCinfo(){
    }
    
    /*public LDCinfo(set<id> setacc, string obj){
        accset = setacc;
        ObjName = obj;
    }*/
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        string query = 'select id,name,account__c,account__r.business_account__c,Capacity_PLC1__c,Capacity_PLC2__c,Acct_ADU__c,On_PK_Kwh__c,Off_Pk_Kwh__c,NSPL1_KW__c,NSPL2_KW__c,FRM_Profile__c'
                      +',Utility_Zone__c,Utility_Rate_Class__c,Is_Record_updated__c,ldc_vendor__r.name from ldc_account__c ';// and FRM_Profile__c != null';
        /*if(ObjName == null)
            query+= 'where id IN : ldcset order by account__c';
        else*/
            query+= 'where account__c IN : accset or account__r.business_account__c IN : accset order by account__r.business_account__c';
        return database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bc, list<sObject> scope){
        
        list<ldc_account__c> ldclst = (list<ldc_account__c>)scope;
        map<id,list<ldc_account__c>> accldcmap = new map<id,list<ldc_account__c>>();
        set<id> ldcset =new set<id>();
        for(ldc_account__c ldc : ldclst){
            list<ldc_account__c> templdc = new list<ldc_account__c>();
            if(ldc.account__r.business_account__c != null){
                if(accldcmap.containskey(ldc.account__r.business_account__c)){
                    templdc = accldcmap.get(ldc.account__r.business_account__c);
                }   
                templdc.add(ldc);
                accldcmap.put(ldc.account__r.business_account__c,templdc);
            }
            else{
                if(accldcmap.containskey(ldc.account__c)){
                    templdc = accldcmap.get(ldc.account__c);
                }   
                templdc.add(ldc);
                accldcmap.put(ldc.account__c,templdc);
                ldcset.add(ldc.id);
            }
        }
        
        list<opportunity_ldc__c> oldclst = [select id,opportunity__c,ldc_account__c,ldc_account__r.Acct_ADU__c,ldc_account__r.NSPL1_KW__c,ldc_account__r.Capacity_PLC1__c,
                                                ldc_account__r.On_PK_Kwh__c,ldc_account__r.Off_PK_Kwh__c,ldc_account__r.FRM_Profile__c,ldc_account__r.Utility_Zone__c,
                                                ldc_account__r.Capacity_PLC2__c,ldc_account__r.NSPL2_KW__c,ldc_account__r.Utility_Rate_Class__c,ldc_account__r.ldc_vendor__r.name
                                                 from opportunity_ldc__c where ldc_account__c IN : ldcset and opportunity__c IN (select id from opportunity)];
        set<id> oppset = new set<id>();
        map<id,list<ldc_account__c>> oldcmap = new map<id,list<ldc_account__c>>();
        for(opportunity_ldc__c oldc : oldclst){
            list<ldc_account__c> idlst = new list<ldc_account__c>();
            if(oldcmap.containskey(oldc.opportunity__c)){
                idlst.addAll(oldcmap.get(oldc.opportunity__c));
            }
            idlst.add(oldc.ldc_account__r);
            oldcmap.put(oldc.opportunity__c,idlst);
        }
        system.debug('OLDC Map : '+oldcmap.size()+' : '+oldcmap);
        if(accldcstrmap == null)
            accldcstrmap = new map<id,map<string,cusWrapper>>();
        if(oppldcstrmap == null)
            oppldcstrmap = new map<id,map<string,cusWrapper>>();
            
        for(ID mapid : accldcmap.keySet()){
            map<string,cusWrapper> promap = new map<string,cusWrapper>();
            list<ldc_account__c> innerldc = accldcmap.get(mapid);
            if(accldcstrmap.get(mapid) != null)
                promap = accldcstrmap.get(mapid);
            for(ldc_account__c ldc : innerldc){
              //  CapacitySum += (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : 0.0;
              // system.debug('========Sum==========='+CapacitySum);
                //if(ObjName == null)
                cwrapper = new cusWrapper();
                string str = ldc.FRM_Profile__c+'-'+ldc.Utility_Zone__c;
                system.debug('Promap : '+promap.size()+' : '+promap);
                if(promap.containskey(str)){
                    cwrapper = promap.get(str);
                    cwrapper.Acctadu+= (ldc.Acct_ADU__c != null) ? ldc.Acct_ADU__c : 0.0;
                    cwrapper.NSPLCkw+= (ldc.NSPL1_KW__c != null) ? ldc.NSPL1_KW__c : ((ldc.NSPL2_KW__c != null) ? ldc.NSPL2_KW__c : 0.0);
                    cwrapper.CapacityPLC+= (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : 0.0;
                    cwrapper.Capacity+= (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : ((ldc.Capacity_PLC2__c != null) ? ldc.Capacity_PLC2__c : 0.0);
                    cwrapper.totprice+= ((ldc.On_PK_Kwh__c != null) ? ldc.On_PK_Kwh__c : 0.0) + ((ldc.Off_PK_Kwh__c != null) ? ldc.Off_PK_Kwh__c : 0.0);
                    cwrapper.TotAccounts++;
                }
                else{
                    cwrapper = new cusWrapper();
                    cwrapper.Acctadu = (ldc.Acct_ADU__c != null) ? ldc.Acct_ADU__c : 0.0;
                    cwrapper.NSPLCkw = (ldc.NSPL1_KW__c != null) ? ldc.NSPL1_KW__c : ((ldc.NSPL2_KW__c != null) ? ldc.NSPL2_KW__c : 0.0);
                    cwrapper.CapacityPLC = (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : 0.0;
                    cwrapper.Capacity= (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : ((ldc.Capacity_PLC2__c != null) ? ldc.Capacity_PLC2__c : 0.0);
                    cwrapper.Totprice = ((ldc.On_PK_Kwh__c != null) ? ldc.On_PK_Kwh__c : 0.0) + ((ldc.Off_PK_Kwh__c != null) ? ldc.Off_PK_Kwh__c : 0.0);
                    cwrapper.TotAccounts = 1;
                }
                cwrapper.Vendor = ldc.ldc_vendor__r.name;
                cwrapper.Rateclass = ldc.Utility_Rate_Class__c;                     
                promap.put(str,cwrapper);
            }
            accldcstrmap.put(mapid,promap);
        }
        system.debug('Check : '+accldcstrmap.size()+' : '+accldcstrmap);
        
        list<account> acclst = new list<account>();
        //if(ObjName == null){
        for(account a : [select id,LDC_Individual_Info__c from account where id IN : accldcstrmap.keyset()]){
            a.LDC_Individual_Info__c = '';
            acclst.add(a);
        }
        if(!acclst.isempty())update acclst;
        //}
        acclst = new list<account>();
        system.debug('Acc size : '+acclst.size());
        for(ID mapid : accldcstrmap.keyset()){
        //  CapacitySum = 0;
            map<string,cusWrapper> cwrapmap = accldcstrmap.get(mapid);
            system.debug('cwrapmap : '+mapid+' : '+cwrapmap);
            account acc = new account();
            acc.CustomerPLC__c = 0;
            for(string str : cwrapmap.keyset()){
                if(acc.LDC_Individual_Info__c == null)
                    acc.LDC_Individual_Info__c = str+':';
                else
                    acc.LDC_Individual_Info__c+= str+':';
                    
                acc.LDC_Individual_Info__c+= 'Acctadu<'+cwrapmap.get(str).Acctadu+'>';
                acc.LDC_Individual_Info__c+= 'NSPLCkw<'+cwrapmap.get(str).NSPLCkw+'>';
                acc.LDC_Individual_Info__c+= 'Capacity<'+cwrapmap.get(str).Capacity+'>';
                acc.LDC_Individual_Info__c+= 'Totprice<'+cwrapmap.get(str).Totprice+'>';
                acc.LDC_Individual_Info__c+= 'Rateclass<'+cwrapmap.get(str).Rateclass+'>';
                acc.LDC_Individual_Info__c+= 'Vendor<'+cwrapmap.get(str).Vendor+'>';
                acc.LDC_Individual_Info__c+= 'TotAccounts<'+cwrapmap.get(str).TotAccounts+'>; \n';
                
                if(cwrapmap.containsKey(str) && cwrapmap.get(str).CapacityPLC != null){      
                    acc.CustomerPLC__c += cwrapmap.get(str).CapacityPLC;
                }                                                            
            }           
            acc.id = mapid;
         // acc.CustomerPLC__c = CapacitySum;
            system.debug('====CustomerPLC===='+acc.customerPLC__c);
            acclst.add(acc);
        }
        
        system.debug('Test check : '+acclst.size()+' : '+acclst);
        if(!acclst.isempty())update acclst;   
        
        /********************* C&I accounts at Opportunity Level  ***********************/
        for(ID mapid : oldcmap.keySet()){
            map<string,cusWrapper> promap = new map<string,cusWrapper>();
            list<ldc_account__c> innerldc = oldcmap.get(mapid);
            if(oppldcstrmap.get(mapid) != null)
                promap = oppldcstrmap.get(mapid);
            for(ldc_account__c ldc : innerldc){
                //if(ObjName == null)
                cwrapper = new cusWrapper();
                string str = ldc.FRM_Profile__c+'-'+ldc.Utility_Zone__c;
                system.debug('Promap : '+promap.size()+' : '+promap);
                if(promap.containskey(str)){
                    cwrapper = promap.get(str);
                    cwrapper.Acctadu+= (ldc.Acct_ADU__c != null) ? ldc.Acct_ADU__c : 0.0;
                    cwrapper.NSPLCkw+= (ldc.NSPL1_KW__c != null) ? ldc.NSPL1_KW__c : ((ldc.NSPL2_KW__c != null) ? ldc.NSPL2_KW__c : 0.0);
                    cwrapper.Capacity+= (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : ((ldc.Capacity_PLC2__c != null) ? ldc.Capacity_PLC2__c : 0.0);
                    cwrapper.totprice+= ((ldc.On_PK_Kwh__c != null) ? ldc.On_PK_Kwh__c : 0.0) + ((ldc.Off_PK_Kwh__c != null) ? ldc.Off_PK_Kwh__c : 0.0);
                    cwrapper.TotAccounts++;
                }
                else{
                    cwrapper = new cusWrapper();
                    cwrapper.Acctadu = (ldc.Acct_ADU__c != null) ? ldc.Acct_ADU__c : 0.0;
                    cwrapper.NSPLCkw = (ldc.NSPL1_KW__c != null) ? ldc.NSPL1_KW__c : ((ldc.NSPL2_KW__c != null) ? ldc.NSPL2_KW__c : 0.0);
                    cwrapper.Capacity= (ldc.Capacity_PLC1__c != null) ? ldc.Capacity_PLC1__c : ((ldc.Capacity_PLC2__c != null) ? ldc.Capacity_PLC2__c : 0.0);
                    cwrapper.Totprice = ((ldc.On_PK_Kwh__c != null) ? ldc.On_PK_Kwh__c : 0.0) + ((ldc.Off_PK_Kwh__c != null) ? ldc.Off_PK_Kwh__c : 0.0);
                    cwrapper.TotAccounts = 1;
                }
                cwrapper.Vendor = ldc.ldc_vendor__r.name;
                cwrapper.Rateclass = ldc.Utility_Rate_Class__c;                     
                promap.put(str,cwrapper);
            }
            oppldcstrmap.put(mapid,promap);
        }
        system.debug('Check Opp level: '+oppldcstrmap.size()+' : '+oppldcstrmap);  
        
        list<opportunity> opplst = new list<opportunity>();
        for(opportunity o : [select id,LDC_Individual_Info__c from opportunity where id IN : oppldcstrmap.keyset()]){
            o.LDC_Individual_Info__c = '';
            opplst.add(o);
        }
        if(!opplst.isempty())update opplst;

        opplst = new list<opportunity>();
        system.debug('Opp size : '+opplst.size());
        for(ID mapid : oppldcstrmap.keyset()){
            map<string,cusWrapper> cwrapmap = oppldcstrmap.get(mapid);
            system.debug('cwrapmap : '+mapid+' : '+cwrapmap);
            opportunity opp = new opportunity();
            for(string str : cwrapmap.keyset()){
                if(opp.LDC_Individual_Info__c == null)
                    opp.LDC_Individual_Info__c = str+':';
                else
                    opp.LDC_Individual_Info__c+= str+':';
                    
                opp.LDC_Individual_Info__c+= 'Acctadu<'+cwrapmap.get(str).Acctadu+'>';
                opp.LDC_Individual_Info__c+= 'NSPLCkw<'+cwrapmap.get(str).NSPLCkw+'>';
                opp.LDC_Individual_Info__c+= 'Capacity<'+cwrapmap.get(str).Capacity+'>';
                opp.LDC_Individual_Info__c+= 'Totprice<'+cwrapmap.get(str).Totprice+'>';
                opp.LDC_Individual_Info__c+= 'Rateclass<'+cwrapmap.get(str).Rateclass+'>';
                opp.LDC_Individual_Info__c+= 'Vendor<'+cwrapmap.get(str).Vendor+'>';
                opp.LDC_Individual_Info__c+= 'TotAccounts<'+cwrapmap.get(str).TotAccounts+'>; \n';
            }
            opp.id = mapid;
            opplst.add(opp);
        }
        if(!opplst.isempty())update opplst;
        
        for(ldc_account__c ldc : ldclst){
            ldc.Is_Record_updated__c = false;
        }  
        if(!ldclst.isempty()){
            TriggerHandler.firstRun=false;
            update ldclst;
        } 
    }
    
    global void finish (Database.BatchableContext bc){
        
    }
    
    public class cusWrapper{
        public decimal Acctadu {get;set;}
        public decimal NSPLCkw {get;set;}
        public decimal Capacity {get;set;}
        public decimal CapacityPLC {get;set;}
        public decimal Totprice {get;set;}
        public string Rateclass {get;set;}
        public string Vendor {get;set;}
        public integer TotAccounts {get;Set;}
        
        public cusWrapper(){
            
        }
        
        public cusWrapper(decimal adu,decimal nsplc, decimal plc, decimal CusPLC, decimal tot, string rclass, string vnd, integer acc){
            Acctadu = adu;
            NSPLCkw = nsplc;
            Capacity = plc;
            CapacityPLC = CusPLC;
            Totprice = tot;
            Rateclass = rclass;
            Vendor = vnd;
            TotAccounts = acc;
            
        }
    }
}