src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bill_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bill Method</label>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interval_Usage__c</fullName>
        <label>Interval Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interval</fullName>
                </value>
                <value>
                    <fullName>Summary</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to store the supplier information at contract level</description>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Term__c.object
<CustomObject>
    <description>Object supports individual contract terms tied to the contract necessary to flow to LS.</description>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Contract Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <description>Rate Ready
DUAL</description>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Reason__c</fullName>
        <label>Change Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Billing_Entity__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Change Billing Type (Billing Option)</fullName>
                </value>
                <value>
                    <fullName>Change ESP Rate Code</fullName>
                </value>
                <value>
                    <fullName>Change Service Indicator (Summary or Detail Interval Data)</fullName>
                </value>
                <value>
                    <fullName>Change Aggregation Category</fullName>
                </value>
                <value>
                    <fullName>change Billing Type (Bill Presenter)</fullName>
                </value>
                <value>
                    <fullName>Change Consumers Tax Rate</fullName>
                </value>
                <value>
                    <fullName>Change E/M Fixed Charge</fullName>
                </value>
                <value>
                    <fullName>Change of ESP Rate Amount</fullName>
                </value>
                <value>
                    <fullName>Change Party that Calculates the Bill</fullName>
                </value>
                <value>
                    <fullName>Change ESP Account Number</fullName>
                </value>
                <value>
                    <fullName>Change of Interval Status</fullName>
                </value>
                <value>
                    <fullName>Change Percentage of Service Tax Exempt</fullName>
                </value>
                <value>
                    <fullName>Change Rate Ready ESP Bill Code</fullName>
                </value>
                <value>
                    <fullName>Change in Mailing Address</fullName>
                </value>
                <value>
                    <fullName>Tax Exemption Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interval_Usage__c</fullName>
        <label>Interval Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interval</fullName>
                </value>
                <value>
                    <fullName>Summary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interval_Usage__c</fullName>
        <label>Interval Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interval</fullName>
                </value>
                <value>
                    <fullName>Summary</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meter__c.object
<CustomObject>
    <description>Custom Object for Meter</description>
    <fields>
        <fullName>Change_Reason__c</fullName>
        <label>Change Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ESP Rate Code</fullName>
                </value>
                <value>
                    <fullName>ESP Rate Sub Class</fullName>
                </value>
                <value>
                    <fullName>LDC Rate Code</fullName>
                </value>
                <value>
                    <fullName>LDC Rate Sub Class</fullName>
                </value>
                <value>
                    <fullName>LDC Read Cycle</fullName>
                </value>
                <value>
                    <fullName>Load Profile</fullName>
                </value>
                <value>
                    <fullName>MDMA Attributes</fullName>
                </value>
                <value>
                    <fullName>Meter Addition</fullName>
                </value>
                <value>
                    <fullName>Meter Attributes</fullName>
                </value>
                <value>
                    <fullName>Meter Billing Option</fullName>
                </value>
                <value>
                    <fullName>Meter Change Notification</fullName>
                </value>
                <value>
                    <fullName>Meter Exchange</fullName>
                </value>
                <value>
                    <fullName>Meter Installer Attributes</fullName>
                </value>
                <value>
                    <fullName>Meter Multiplier</fullName>
                </value>
                <value>
                    <fullName>Meter Number of Dials</fullName>
                </value>
                <value>
                    <fullName>Meter Owner Attributes</fullName>
                </value>
                <value>
                    <fullName>Meter Reader Attributes</fullName>
                </value>
                <value>
                    <fullName>Meter Removal</fullName>
                </value>
                <value>
                    <fullName>Meter Service Delivery Point</fullName>
                </value>
                <value>
                    <fullName>Meter Type</fullName>
                </value>
                <value>
                    <fullName>MSP Attributes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meter</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Meter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EDITransformationUtil.cls
public class EDITransformationUtil {
    public static final String VAL_ELECTRIC = 'Electric';
    public static final String VAL_UNITED_STATES = 'UNITED STATES';
    public static final String VAL_USA = 'USA';
    public static final String VAL_GAS = 'Gas';
    public static final String VAL_INTERVAL = 'Interval';
    public static final String VAL_SUMMARY = 'Summary';
    public static final String CODE_US = 'US';
    public static final String CODE_INTERVAL = 'N';
    public static final String CODE_SUMMARY = 'Y';
    public static final String CODE_ELECTRIC = 'E';
    public static final String CODE_GAS = 'G';
    public static final String CHNG_RSN_CODE_SERV_IND = 'REF17';

    public static String convUSAValToCode(String countryName)
    {
        String val;
        if(countryName == null || String.isEmpty(countryName))
        {
            return CODE_US;
        }
        if(countryName.trim().length() == 2)
        {
            return countryName.toUpperCase();
        }
        if(countryName.equalsIgnoreCase(VAL_UNITED_STATES) || countryName.equalsIgnoreCase(VAL_USA))
        {
           val = CODE_US; 
        }
        return val;
    }
    
    public static String convStateValToCode(String stateName)
    {
        String val;
        if(stateName == null || String.isEmpty(stateName))
        {
            return null;
        }
        if(stateName.trim().length() == 2)
        {
            return stateName.toUpperCase();
        }
        val = StateCountryUtil.getStateCodeForVal(val,'United States');
        return val;
    }
    public static String convCommodityCodeToVal(String code)
    {
        String val;
        if(code == null || String.isEmpty(code))
        {
            return null;
        }
        if(code.trim().equalsIgnoreCase(CODE_ELECTRIC))
        {
            val = EDITransformationUtil.VAL_ELECTRIC;
        }else if(code.trim().equalsIgnoreCase(CODE_GAS))
        {
            val = EDITransformationUtil.VAL_GAS;
        }
        return val;
    }
    public static String convCommodityValToCode(String val)
    {
        String code;
        if(val == null || String.isEmpty(val))
        {
            return null;
        }
        if(val.trim().equalsIgnoreCase(VAL_ELECTRIC))
        {
            code = EDITransformationUtil.CODE_ELECTRIC;
        }else if(val.trim().equalsIgnoreCase(VAL_GAS))
        {
            code = EDITransformationUtil.CODE_GAS;
        }
        return code;
    }
    
    public static String convUsageCodeToVal(String code)
    {
        String val;
        if(code == null || String.isEmpty(code))
        {
            return null;
        }
        if(code.trim().equalsIgnoreCase(CODE_SUMMARY))
        {
            val = EDITransformationUtil.VAL_SUMMARY;
        }else if(code.trim().equalsIgnoreCase(CODE_INTERVAL))
        {
            val = EDITransformationUtil.VAL_INTERVAL;
        }
        return val;
    }
    public static String convUsageValToCode(String val)
    {
        String code;
        if(val == null || String.isEmpty(val))
        {
            return null;
        }
        if(val.trim().equalsIgnoreCase(VAL_INTERVAL))
        {
            code = EDITransformationUtil.CODE_INTERVAL;
        }else if(val.trim().equalsIgnoreCase(VAL_SUMMARY))
        {
            code = EDITransformationUtil.CODE_SUMMARY;
        }
        return code;
    }
    public static String getUsageValue(DASR_Request__c vDASR, LDC_Account__c vldcAccnt,Supplier__c vSupplier,LDC_Vendor__c vVendor,List<Meter__c> vMeterList,Account vCustomer,Contract vContract, List<Contract_Term__c> vContractTerm)
    {
        String val = EDIIntegrationConfigUtil.getIntRequestCode();
        if(vDASR == null)
        {
            return val;
        }
        String dasrUsageType = vDASR.Interval_Usage__c != null && vDASR.Interval_Usage__c != '' ? vDASR.Interval_Usage__c : vldcAccnt.Interval_Usage__c;
        String contUsageType = vContract != null ? vContract.Interval_Usage__c : null;
        String contBillMethod = vContract != null ? vContract.Bill_Method__c : null;
        String chngRsnCode = ChangeReasonUtil.getChgRsnCodeForVal(vDASR.Change_Reason__c,'LDC_Account__c');
        if(contBillMethod != null && contBillMethod.equalsIgnoreCase('DUAL') && (chngRsnCode == null || !chngRsnCode.equalsIgnoreCase(CHNG_RSN_CODE_SERV_IND)))
        {
            return val;
        }        
        if(contUsageType != null && !string.isEmpty(contUsageType) && (chngRsnCode == null || !chngRsnCode.equalsIgnoreCase(CHNG_RSN_CODE_SERV_IND)))
        {
            val = convUsageValToCode(contUsageType);
        }
        if(chngRsnCode != null && chngRsnCode.equalsIgnoreCase(CHNG_RSN_CODE_SERV_IND))
        {
            val = dasrUsageType != null ? convUsageValToCode(dasrUsageType) : null;   
        }
        if(val == null || String.isEmpty(val))
        {
            val = EDIIntegrationConfigUtil.getIntRequestCode();
        }
        
        return val;
        
    }
}