src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Business Account for Person Account (Used for MuniAgg, MassMarket etc)</description>
        <inlineHelpText>Related Business Customer for Individual Customer (Used for MuniAgg, MassMarket etc)</inlineHelpText>
        <label>Business Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Mass_Market_Offer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Muni_Agg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>BusinessAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LodeStar_Integration_Status__c</fullName>
        <description>The Status of this record as it relates to LodeStar having the most up-to-date information.</description>
        <inlineHelpText>Indicates the data was sent to Lodestar, but does not confirm it was received successfully.  The field must be in &quot;Not Synchronized.&quot; See Document &quot;SF to LS Integration.docx&quot; for more details.</inlineHelpText>
        <label>LodeStar Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Synchronized</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Synchronized</fullName>
                </value>
                <value>
                    <fullName>Test Synchronized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSynchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</description>
        <inlineHelpText>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</inlineHelpText>
        <label>Is Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <description>LDC Account Number</description>
        <formula>LDC_Account__r.LDC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LDC Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <label>Term Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Term_Stop_Date__c</fullName>
        <label>Term Stop Date</label>
        <type>DateTime</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_Id__c</fullName>
        <externalId>true</externalId>
        <label>CRM ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastSent_to_Lodestar__c</fullName>
        <label>Last Sent to Lodestar</label>
        <type>DateTime</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountResetForLodestar.cls
/** 
 * Name: AccountResetForLodestar
 * Type: Apex Class
 * Test Class: AccountResetForLodestarTest
 * Description:  This batch job updates the Contract LDC's underneath the Accounts if any of these fields that needs to be triggered
 				 for lodestar using ldc account number . 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Prasad Paladugu              06/30/2016       1. Initial Version created
 **/
 
 global class AccountResetForLodestar implements schedulable,Database.Batchable <sobject>,Database.Stateful{
    
    global void execute (schedulablecontext sc){
        AccountResetForLodestar acctolStar = new AccountResetForLodestar(ldcnumstr);
        Id bid = Database.executeBatch( acctolStar,20);
    }
    global AccountResetForLodestar(){

    }
    
    global final string accoffer;
    global final string ldcnumstr;
    global list<string> ldcnumlst;
    global AccountResetForLodestar(string ldcnum){
        ldcnumstr = ldcnum;
    }
    
    string query;
    
    global Database.QueryLocator start (Database.BatchableContext bc){
        ldcnumlst = ldcnumstr.split(',');
        system.debug('List size : '+ldcnumlst.size()+' : '+ldcnumlst);
        query='SELECT Account__c,Account__r.Business_Account__c,CRM_Id__c,Id,LastSent_to_Lodestar__c,LDC_Account_Number__c,Name FROM LDC_Account__c WHERE LDC_Account_Number__c IN: ldcnumlst ';
        return Database.getQueryLocator(query);
    }
     
    global void execute (Database.BatchableContext bc, list<sobject> scope ){
        list<LDC_Account__c> ldcacclst = (list<LDC_Account__c>)scope;
        system.debug('LDC Account size : '+ldcacclst.size());
        set<id> ldcid = new set<id>();
        set<id> accid = new set<id>();
        for(ldc_account__c ldcacc : ldcacclst){
            ldcid.add(ldcacc.id);
            accid.add(ldcacc.Account__c);
        }
        
        list<account> acclst = [select id,Business_Account__c,LodeStar_Integration_Status__c from account where id IN : accid];
        system.debug('Account size : '+acclst.size());
        for(Account acc : acclst){
            acc.LodeStar_Integration_Status__c='Not Synchronized';
        }
        update acclst;
        
        list<contract_ldc__c> cldclst = [SELECT Active__c,Contract__c,Id,IsSynchronized__c,LDC_Account_Number__c,LDC_Account__c,Name,Term_Start_Date__c,Term_Stop_Date__c FROM Contract_LDC__c WHERE LDC_Account_Number__c IN : ldcnumlst AND LDC_Account__c IN : ldcid and active__c = true];
        system.debug('Contract LDC size : '+ cldclst.size());
        for(contract_ldc__c cldc : cldclst){
            if(cldc.IsSynchronized__c != false)
                cldc.IsSynchronized__c = false;
        }
        update cldclst;
    }
    
    global void finish (Database.BatchableContext bc){
        
    }
    
}