src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Energy__c</fullName>
        <label>Energy</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Request Status</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waiting on Load Data</fullName>
                </value>
                <value>
                    <fullName>Manual Pricing in Process</fullName>
                </value>
                <value>
                    <fullName>Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Pricing Complete</fullName>
                </value>
                <value>
                    <fullName>Error-Invalid Account</fullName>
                </value>
                <value>
                    <fullName>Error Utility Web-Service Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Error - Price Curve Invalid</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/classes/GetExecutablePriceControllerTest.cls
/* 
 * Name: GetExecutablePriceControllerTest
 * Type: Test Class
 * Apex Class: GetExecutablePriceController
 * Description: Test class for code coverage of GetExecutablePriceController. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0        Sneha Gadde        03/14/2016       1. Initial Version created
 */

@isTest(SeeAllData=false)
public class GetExecutablePriceControllerTest {

 private static testmethod void ExecutablePriceController_UnitTest()
 {
   Test.startTest();  
      RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];
        Account acc = new Account();
        acc.name = 'Test Acc';
        acc.Billing_Entity__c='Dynegy';
        insert acc;
       Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       opp.Accountid = acc.id;
       opp.RecordTypeId = rec.id;
       insert opp;
       
       Retail_Quote__c rq = new Retail_Quote__c();
       rq.Opportunity__c = opp.id;
       rq.Energy__c = 5.8;   
       rq.Request_Status__c = ConstantUtility.STATUS_PRICING_COMPLETE;
       rq.RecordTypeId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_EXECUTABLE); 
       rq.Utility_Settlement_Zone__c = 'Test Utility';
       insert rq;
     
     
      ApexPages.StandardController sc = new ApexPages.StandardController(opp);
      GetExecutablePriceController cntrl = new GetExecutablePriceController(sc);
      cntrl.cancelRequest();
      cntrl.sendNewQuotes();
       rq.RecordTypeId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_INDICATIVE);
       update rq;
      cntrl.createRequest();
    
     
      cntrl.getOptyView();
     Set<id> qtIdLst = new Set<id>();
     qtIdLst.add(rq.id);
     GetExecutablePriceController.sendQuotesForPricing(qtIdLst,opp.id);
     
   Test.stopTest();  
 }
     private static testmethod void testExecutablePriceController1()
 {
   Test.startTest();  
      RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];
        Account acc = new Account();
        acc.name = 'Test Acc';
        acc.Billing_Entity__c='Dynegy';
        insert acc;
       Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       opp.Accountid = acc.id;
       opp.RecordTypeId = rec.id;
       insert opp;
       
       Retail_Quote__c rq = new Retail_Quote__c();
       rq.Opportunity__c = opp.id;
       rq.Energy__c = 5.8;   
       rq.Request_Status__c = ConstantUtility.STATUS_PRICING_COMPLETE;
       rq.RecordTypeId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_INDICATIVE); 
       rq.Utility_Settlement_Zone__c = 'Test Utility';
       insert rq;
     
     
      ApexPages.StandardController sc = new ApexPages.StandardController(opp);
      GetExecutablePriceController cntrl = new GetExecutablePriceController(sc);
      cntrl.cancelRequest();
      cntrl.sendNewQuotes();
     List<GetExecutablePriceController.RetailQuoteWrapper> retQuoteWrapList = new List<GetExecutablePriceController.RetailQuoteWrapper>();
     GetExecutablePriceController.RetailQuoteWrapper rtquoteWrapper = new GetExecutablePriceController.RetailQuoteWrapper(rq);
     rtquoteWrapper.selected = true;
     
     retQuoteWrapList.add(rtquoteWrapper);
     cntrl.retQuoteWrapList = retQuoteWrapList;
        cntrl.createRequest();   
     Map<id,Retail_Quote__c> rqMap = new Map<id,Retail_Quote__c>([select id,name from Retail_Quote__c]);
  
     GetExecutablePriceController.sendQuotesForPricing(rqMap.keySet(),opp.id);
   Test.stopTest();  
 }
    
}