src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contracting_Entity__c</fullName>
        <label>Contracting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DES</fullName>
                </value>
                <value>
                    <fullName>DES-EAST</fullName>
                </value>
                <value>
                    <fullName>Homefield Energy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Broker_Fee__c</fullName>
        <label>Broker Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Margin__c</fullName>
        <label>Index Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Cost__c</fullName>
        <label>Marketing Cost</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Municipality_Fee__c</fullName>
        <label>Municipality Fee</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Retail_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Quote</label>
        <referenceTo>Retail_Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account__r.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <label>Offer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Indicative</fullName>
                </value>
                <value>
                    <fullName>Executable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Desk_Contact__c</fullName>
        <label>Pricing Desk Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Due_Date__c</fullName>
        <label>Pricing Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricing_Type__c</fullName>
        <label>Pricing Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Refresh</fullName>
                </value>
                <value>
                    <fullName>Addendum Account Add</fullName>
                </value>
                <value>
                    <fullName>Addendum Product Change</fullName>
                </value>
                <value>
                    <fullName>Addendum Block Purchase</fullName>
                </value>
                <value>
                    <fullName>Addendum % Energy Purchase</fullName>
                </value>
                <value>
                    <fullName>Amendment Extend Term</fullName>
                </value>
                <value>
                    <fullName>Amendment Drop Account</fullName>
                </value>
                <value>
                    <fullName>Renewal Evergreen</fullName>
                </value>
                <value>
                    <fullName>Renewal MTM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Pricing_Instructions__c</fullName>
        <label>Special Pricing Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Price__c</fullName>
        <inlineHelpText>($/kWh)</inlineHelpText>
        <label>Target Price</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Workbook_Location__c</fullName>
        <label>Workbook Location</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Broker_Fee_Allocation__c</fullName>
        <label>Broker Fee Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/MWh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Broker_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Broker Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Term__c</fullName>
        <formula>DATE(
    YEAR(Start_Term__c) +
    FLOOR((Term__c + MONTH(Start_Term__c)) / 12) -
    IF (MOD(MONTH(Start_Term__c) + Term__c, 12) = 0,
        1,
        0),

    MOD((Term__c + MONTH(Start_Term__c) - 1), 12) + 1,

    DAY(Start_Term__c)
)</formula>
        <label>End Term</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Energy_Fixed__c</fullName>
        <label>% Energy Fixed</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Index_Margin_Allocation__c</fullName>
        <label>Index Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/MWh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin__c</fullName>
        <description>Changed from Text to Currency</description>
        <inlineHelpText>This field was previously labeled as &quot;Index Margin.&quot;  It was changed per ticket T-000122.</inlineHelpText>
        <label>Energy Adder Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin_Allocation__c</fullName>
        <label>Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Cost_Allocation__c</fullName>
        <label>Marketing Cost Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Cost__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Marketing Cost</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Municipality_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Municipality Fee</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Off_Peak_Block_Size__c</fullName>
        <label>Off Peak Block Size</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Peak_Block_Size__c</fullName>
        <label>On Peak Block Size</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Price__c</fullName>
        <inlineHelpText>($/kWh)</inlineHelpText>
        <label>Target Price</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>Term in Months</description>
        <label>Term (Whole Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Voluntary_REC__c</fullName>
        <label>Voluntary REC %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/PricingWSHelper.cls
/* 
 * Name: PricingWSHelper
 * Type: Apex Class
 * Test Class: Covered under the respective main classes
 * Description:  This class contains the helper functions for generating VO's and make WS calls. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti        01/17/2016       1. Initial Version created
 */
public with sharing class PricingWSHelper {
    public static void sendQuotesForPricing(List<Retail_Quote__c> lstRetQt,Opportunity opp, Account acc){
        
        system.debug('>>>>>>>> FOR PRICING ENGINE : ' + lstRetQt);
         String quoteRecType = '';
        if(lstRetQt!= null && !lstRetQt.isEmpty() )
        {
          RecordType rec = [select id,name from RecordType where id=:lstRetQt[0].recordtypeid];
          quoteRecType = rec.name;
          opp.Offer_Type__c = quoteRecType;
        }
        
        dynegyComServices_new.SforcePricingRequest reqOppQuote = new dynegyComServices_new.SforcePricingRequest();
        reqOppQuote.Opportunity = getOpportunityVO(opp,acc);
        reqOppQuote.Quotes = getQuotesVO(lstRetQt);        
        reqOppQuote.LDCAccounts = getLDCAccounts(opp);
        
        system.debug('>>>>>>>> getOpportunityVO : ' + reqOppQuote.Opportunity);
        system.debug('>>>>>>>> getQuotesVO : ' + reqOppQuote.Quotes);
        system.debug('>>>>>>>> LDCAccounts : ' + reqOppQuote.LDCAccounts);
        system.debug('****Pricing Request'+reqOppQuote);
        
        dynegyComServices_new.BasicHttpBinding_IRetailWS tOrg = new dynegyComServices_new.BasicHttpBinding_IRetailWS();
        try{
            String pResp = tOrg.RequestPricing(reqOppQuote);
            system.debug('>>>>>>>> pResp : ' + pResp);
        }
        catch(exception e){
            system.debug('>>>> ERROR In Web Service Call: ' + e.getMessage());
        }
        
        
    }

    public static string getQuotesforPricing(List<Retail_Quote__c> lstRetQt,Opportunity opp, Account acc){
        system.debug('>>>>>>>> FOR PRICING ENGINE : ' + lstRetQt);
        
          String quoteRecType = '';
        if(lstRetQt!= null && !lstRetQt.isEmpty() )
        {
        
          RecordType rec = [select id,name from RecordType where id=:lstRetQt[0].recordtypeid];
          quoteRecType = rec.name;
          opp.Offer_Type__c = quoteRecType;
        }
         
        dynegyComServices_new.SforcePricingRequest reqOppQuote = new dynegyComServices_new.SforcePricingRequest();
        reqOppQuote.Opportunity = getOpportunityVO(opp,acc);
        reqOppQuote.Quotes = getQuotesVO(lstRetQt);        
        reqOppQuote.LDCAccounts = getLDCAccounts(opp);
        
        system.debug('>>>>>>>> getOpportunityVO : ' + reqOppQuote.Opportunity);
        system.debug('>>>>>>>> getQuotesVO : ' + reqOppQuote.Quotes);
        system.debug('>>>>>>>> LDCAccounts : ' + reqOppQuote.LDCAccounts);
        system.debug('****Pricing Request'+reqOppQuote);
         system.debug('****Pricing Request JSON '+JSON.serialize(reqOppQuote));
        
       return JSON.serialize(reqOppQuote);

    }

    @future(CallOut=true)
    public  Static void  sendQuotesForPricingFuture(string request){

        dynegyComServices_new.BasicHttpBinding_IRetailWS tOrg = new dynegyComServices_new.BasicHttpBinding_IRetailWS();
        try{
           
            String pResp = tOrg.RequestPricing((dynegyComServices_new.SforcePricingRequest)json.deserialize(request, dynegyComServices_new.SforcePricingRequest.class));
            system.debug('>>>>>>>> pResp : ' + pResp);
           //PricingWSHelper.onPricingFailure(request);
        }
        catch(exception e){
            system.debug('>>>> ERROR In Web Service Call: ' + e.getMessage());
        }
        
        
    }

    public static void onPricingFailure(string request){

        Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(request);
        system.debug('****'+m);
        Map<string,Object> m2=(Map<String, Object>)m.get('SforceQuote');
        system.debug('****'+m2);
    }
    
    public static dynegyComServices_new.SforceOpportunity getOpportunityVO(Opportunity opp, Account acc){
        dynegyComServices_new.SforceOpportunity opportunityVO = new dynegyComServices_new.SforceOpportunity();
        opportunityVO.OpportunityName = opp.Name;
        opportunityVO.OpportunityId = opp.Id;
        opportunityVO.CustomerName = acc.Name;
        opportunityVO.ContractingEntity = acc.Contracting_Entity__c;
        opportunityVO.SalesforceAccountID = acc.Id;
        opportunityVO.CustomerType = opp.Type;
        opportunityVO.CustomerCategory = acc.Industry;
        opportunityVO.ServiceTerritory = opp.Service_Territory__c;
        opportunityVO.OfferType = opp.Offer_Type__c;
        opportunityVO.PricingType = opp.Pricing_Type__c;
        opportunityVO.SalesExec = opp.CreatedBy.Name;
        opportunityVO.PricingDueDate = opp.Pricing_Due_Date__c;
        opportunityVO.PricingDeskContact = opp.Pricing_Desk_Contact__c;
        opportunityVO.SupplierDUNS = opp.Supplier_DUNS__c;
        opportunityVO.WorkbookLocation = opp.Workbook_Location__c;
        opportunityVO.SpecialPricingInstructions = opp.Special_Pricing_Instructions__c;
        opportunityVO.TargetPrice = opp.Target_Price__c;
        opportunityVO.ContractNumber = opp.Contract.ContractNumber;
        
        return opportunityVO;
    }
    
    public static dynegyComServices_new.ArrayOfSforceQuote getQuotesVO(List<Retail_Quote__c> lstRetQt){
        system.debug('****Retail Quote'+lstRetQt);
        List<dynegyComServices_new.SforceQuote> lstQuotes = new List<dynegyComServices_new.SforceQuote>();
        dynegyComServices_new.ArrayOfSforceQuote arrQuotes = new dynegyComServices_new.ArrayOfSforceQuote();
        dynegyComServices_new.SforceQuote quoteVO;
        for(Retail_Quote__c recQuote :lstRetQt){
            quoteVO = new dynegyComServices_new.SforceQuote();
            quoteVO.ProductCode = recQuote.Product__r.Name;
            System.debug('**** recQuote.Product__r.Name: ' + recQuote.Product__r.Name);
            quoteVO.EndTerm = recQuote.End_Term__c;
            quoteVO.PaymentTerms = (recQuote.Payment_Terms__c != null)?Integer.ValueOf(recQuote.Payment_Terms__c):null;
            quoteVO.StartTerm = recQuote.Start_Term__c;
            quoteVo.TargetPrice = recQuote.Target_Price__c;
            quoteVO.BrokerFee = recQuote.Broker_Fee__c;
            quoteVO.IndexMargin = recQuote.Index_Margin__c;
            quoteVO.Margin = recQuote.Margin__c;
            quoteVO.MarketingCost = recQuote.Marketing_Cost__c;
            quoteVO.MuniFee = recQuote.Municipality_Fee__c;
            quoteVO.OffPeakBlockSize = recQuote.Off_Peak_Block_Size__c;
            quoteVO.OnPeakBlockSize = recQuote.On_Peak_Block_Size__c;
            quoteVO.PercentEnergyFixed = recQuote.Energy_Fixed__c;
            quoteVO.VoluntaryRecPercent = recQuote.Voluntary_REC__c;
            quoteVO.QuoteID = recQuote.Id;
            quoteVO.TermLength = Integer.valueOf(recQuote.Term__c);
            quoteVO.BrokerFeeAlloc = recQuote.Broker_Fee_Allocation__c;
            quoteVO.IndexMarginAlloc = recQuote.Index_Margin_Allocation__c;
            quoteVO.MarginAlloc = recQuote.Margin_Allocation__c;
            quoteVO.MarketingCostAlloc = recQuote.Marketing_Cost_Allocation__c;
            quoteVO.MuniFeeAlloc = recQuote.Municipality_Fee_Allocation__c;
            quoteVO.VoluntaryRecGeoLocation = recQuote.Voluntary_REC_Geographic_Location__c;
            quoteVO.VoluntaryRecType = recQuote.Voluntary_REC_Generator_Type__c; 
            quoteVO.HoldingDays = recQuote.Holding_Days__c;                       
            lstQuotes.add(quoteVO);
        }
        arrQuotes.SforceQuote = lstQuotes;        
        return arrQuotes;
    }
    
    public static dynegyComServices_new.ArrayOfSforceAccount getLDCAccounts(Opportunity opp){
        List<dynegyComServices_new.SforceAccount> lstLDCAccount = new List<dynegyComServices_new.SforceAccount>();
        dynegyComServices_new.ArrayOfSforceAccount arrLDCAccount = new dynegyComServices_new.ArrayOfSforceAccount();
        dynegyComServices_new.SforceAccount LDCAccountVO;

        List<Opportunity_LDC__c> oll = new List<Opportunity_LDC__c>([select LDC_Account__c from Opportunity_LDC__c where Opportunity__c =: opp.Id]);
              
        set<String> ldcAccountNumber = new set<String>();
        for(Opportunity_LDC__c ol:oll ){
            ldcAccountNumber.add( ol.LDC_Account__c);
        }
        
        List<LDC_Account__c> ldcList = [select id,LDC_Account_Number__c,LDC_Vendor__c,LDC_Vendor__r.DUNS__c,LDC_Vendor__r.Utility_Code__c  from LDC_Account__c where id in: ldcAccountNumber];
         
        for(LDC_Account__c ldc :ldcList){            
            LDCAccountVO = new dynegyComServices_new.SforceAccount();
            LDCAccountVO.SforceLdcId = ldc.Id;
            LDCAccountVO.LDCAccountNumber = ldc.LDC_Account_Number__c;
            LDCAccountVO.UtilityDUNS = (ldc.LDC_Vendor__r.DUNS__c != null)?String.valueOf(ldc.LDC_Vendor__r.DUNS__c):'';
            LDCAccountVO.UtilityCode = ldc.LDC_Vendor__r.Utility_Code__c;
            lstLDCAccount.add(LDCAccountVO);             
        }
        
        arrLDCAccount.SforceAccount = lstLDCAccount;
        return arrLDCAccount;
    }           


}