src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bill_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bill Method</label>
</CustomObject>

src/objects/Billing_Group__c.object
<CustomObject>
    <description>Object supports the ability to group accounts for billing by contract.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Address_Line1__c</fullName>
        <label>Group Address Line1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Address_Line3__c</fullName>
        <label>Group Address Line3 (ICo)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>If Start Date is Unknown, please select the contract Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Synchronized__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Select Contract Related to Business Customer by Name &amp; ContractNumber only</errorMessage>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Searches only Related Contracts by Name &amp; ContractNumber only</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Billing Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Group_Ldc__c.object
<CustomObject>
    <description>Object supports the relationship between LDC Accounts and Billing Group.</description>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Billing Group Ldc</relationshipLabel>
        <relationshipName>Billing_Group_Ldc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <formula>LDC_Account__r.LDC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LDC Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Billing Group Ldc</relationshipLabel>
        <relationshipName>Billing_Group_Ldc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Group Ldc</label>
    <nameField>
        <displayFormat>BGLDC-{0000000}</displayFormat>
        <label>Billing Group Ldc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Group Ldcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <description>This field is created to store the bill method at the contract ldc level</description>
        <inlineHelpText>DUAL
Rate Ready
Bill Ready
SBO/ESP</inlineHelpText>
        <label>LDC Bill Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <description>LDC Account Number</description>
        <formula>LDC_Account__r.LDC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LDC Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/BillingLDCTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class BillingLDCTest {

    public static testMethod void BillingLDCTest_1() {
        // TO DO: implement unit test
       
       RecordType rec =[select id,name from RecordType where sObjectType = 'Account' and name = 'C&I Customer']; 
       Account acc = new Account();
       acc.name = 'Test Acc';
       acc.Billing_Entity__c = 'Dynegy';
       acc.RecordTypeId = rec.id;
       insert acc;
       
       Contract cnt = new Contract(AccountId=acc.Id,Name='',Status='Draft',StartDate = Date.newInstance(Date.today().year(),Date.today().month(),1),
                                ContractTerm = 12,Bill_Method__c = 'DUAL', Rate_Code__c = 'DK98',Service_Territory__c='AEPOHIO');        //,Contract_Type__c = 'COST_BASED'
       insert cnt;
       
       cnt.status='Activated';
       update cnt;
       
       Contract cnt2 = new Contract(AccountId=acc.Id,Name='',Status='Draft',StartDate = Date.newInstance(Date.today().addyears(-1).year(),Date.today().month(),1),
                                ContractTerm = 12,Bill_Method__c = 'DUAL', Rate_Code__c = 'DK98',Service_Territory__c='AEPOHIO');        //,Contract_Type__c = 'COST_BASED'
       insert cnt2;
       
       cnt2.status='Activated';
       update cnt2;
       
       Contract cnt3 = new Contract(AccountId=acc.Id,Name='',Status='Draft',StartDate = Date.newInstance(Date.today().addyears(1).year(),Date.today().month(),1),
                                ContractTerm = 12,Bill_Method__c = 'DUAL', Rate_Code__c = 'DK98',Service_Territory__c='AEPOHIO');        //,Contract_Type__c = 'COST_BASED'
       insert cnt3;
       
       cnt3.status='Activated';
       update cnt3;
       
       Billing_Group__c bg1 = new Billing_Group__c();
       bg1.Name = 'Test BG 1';
       bg1.account__c = acc.id;
       bg1.contract__c = cnt.id;  
       bg1.Group_Address_Line1__c='Test add1';
       bg1.start_Date__c = date.today(); 
       
       Billing_Group__c bg2 = new Billing_Group__c();
       bg2.Name = 'Test BG 2';
       bg2.account__c = acc.id;
       bg2.contract__c = cnt.id;  
       bg2.Group_Address_Line1__c='Test add1';
       bg2.start_Date__c = date.today();  
       
       Billing_Group__c bg3 = new Billing_Group__c();
       bg3.Name = 'Test BG 3';
       bg3.account__c = acc.id;
       bg3.contract__c = cnt2.id;  
       bg3.Group_Address_Line1__c='Test add1';
       bg3.start_Date__c = date.today();
       
       Billing_Group__c bg4 = new Billing_Group__c();
       bg4.Name = 'Test BG 4';
       bg4.account__c = acc.id;
       bg4.contract__c = cnt3.id;  
       bg4.Group_Address_Line1__c='Test add1';
       bg4.start_Date__c = date.today();
       
       insert new list<Billing_Group__c>{bg1,bg2,bg3,bg4};   
       
       ApexPages.currentPage().getParameters().put('BGID',bg1.id);
       BillingLDC bg = new BillingLDC();
       ApexPages.currentPage().getParameters().put('BGID',null);
       ApexPages.currentPage().getParameters().put('UBGID',bg2.id);
       BillingLDC bgd = new BillingLDC();
       ApexPages.currentPage().getParameters().put('UBGID',null);
       BillingLDC bgd1 = new BillingLDC();
       
       LDC_Account__c lacc1 = new LDC_Account__c();
       lacc1.name  ='Test LDC acc';
       lacc1.Account__c = acc.id;
       lacc1.Service_Territory__c = 'AEPOHIO';
       lacc1.LDC_Account_Number__c = '1234';
       
       LDC_Account__c lacc2 = new LDC_Account__c();
       lacc2.name  ='Test LDC acc1';
       lacc2.Account__c = acc.id;
       lacc2.Service_Territory__c = 'AEPOHIO';
       lacc2.LDC_Account_Number__c = '2345';
       
       LDC_Account__c lacc3 = new LDC_Account__c();
       lacc3.name  ='Test LDC acc';
       lacc3.Account__c = acc.id;
       lacc3.Service_Territory__c = 'AEPOHIO';
       lacc3.LDC_Account_Number__c = '3456';
       
       LDC_Account__c lacc4 = new LDC_Account__c();
       lacc4.name  ='Test LDC acc1';
       lacc4.Account__c = acc.id;
       lacc4.Service_Territory__c = 'AEPOHIO';
       lacc4.LDC_Account_Number__c = '4567';
       
       insert new list<ldc_account__c>{lacc1,lacc2,lacc3,lacc4};
       
       contract_ldc__c cldc1 = new contract_ldc__c();
       cldc1.name='Test Cldc1';
       cldc1.ldc_account__c = lacc1.id;
       cldc1.contract__c = cnt.id;
       
       contract_ldc__c cldc2 = new contract_ldc__c();
       cldc2.name='Test Cldc2';
       cldc2.ldc_account__c = lacc2.id;
       cldc2.contract__c = cnt.id;
       
       contract_ldc__c cldc3 = new contract_ldc__c();
       cldc3.name='Test Cldc3';
       cldc3.ldc_account__c = lacc3.id;
       cldc3.contract__c = cnt.id;
       
       contract_ldc__c cldc4 = new contract_ldc__c();
       cldc4.name='Test Cldc4';
       cldc4.ldc_account__c = lacc4.id;
       cldc4.contract__c = cnt.id;
       
       insert new list<contract_ldc__c>{cldc1,cldc2,cldc3,cldc4};
       
       ApexPages.currentPage().getParameters().put('BGID',bg1.id);
       BillingLDC bgadd = new BillingLDC();
       bgadd.selectionId = lacc1.id;
       bgadd.selectionId = lacc2.id;
       bgadd.addSelectedId();
       bgadd.addAccounts();
       bgadd.getLDCAccounts(); 
       bgadd.setHeaderValue();
       bgadd.cancel();
       bgadd.getSelectedCount();
       bgadd.getPagenumber();
       bgadd.getTotalpages();
       bgadd.getHasPrevious();
       bgadd.getHasNext();
       bgadd.doNext();
       bgadd.doPrevious();
       
       bgadd.selectionId = null;
       bgadd.addSelectedId();
       bgadd.addAccounts();
       
       ApexPages.currentPage().getParameters().put('BGID',null);
       ApexPages.currentPage().getParameters().put('UBGID',bg1.id);
       BillingLDC bgdel = new BillingLDC();
       bgdel.selectionId = lacc2.id;
       bgdel.addSelectedId();
       bgdel.addAccounts();
       bgdel.delAccounts();
       bgdel.removeSelectedId();
       
       bgdel.selectionId = lacc2.id;
       bgdel.addSelectedId();
       bgdel.addAccounts();
       bgdel.selectionId = null;
       bgdel.removeSelectedId();
       bgdel.delAccounts();
       
       Billing_Group_Ldc__c bgldc = new Billing_Group_Ldc__c();
       bgldc.billing_group__c = bg2.id;
       bgldc.ldc_account__c = lacc4.id;
       bgldc.synchronized__c = true;
       insert bgldc;
       
       bg2.Group_Address_Line3__c = 'In Care of # Billing group 2';
       update bg2;
       
       ApexPages.currentPage().getParameters().put('BGID',bg3.id);
       BillingLDC bgadd1 = new BillingLDC();
       bgadd1.selectionId = lacc1.id;
       bgadd1.selectionId = lacc2.id;
       bgadd1.addSelectedId();
       bgadd1.addAccounts();
       
       ApexPages.currentPage().getParameters().put('BGID',bg4.id);
       BillingLDC bgadd2 = new BillingLDC();
       bgadd2.selectionId = lacc1.id;
       bgadd2.selectionId = lacc2.id;
       bgadd2.addSelectedId();
       bgadd2.addAccounts();
        
    }
}