src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Energy__c</fullName>
        <label>Energy</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Indicative</fullName>
        <active>true</active>
        <label>Indicative</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/CreateMultipleOptyLDC_Test.cls
@isTest
public class CreateMultipleOptyLDC_Test {
 private static testmethod void createMultipleOptyLDCTest()
 {
    Test.startTest(); 
      RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];
      List<Account> accLst = new List<Account>();
       Account acc = new Account();
       acc.name = 'Test Acc';
       acc.Billing_Entity__c='Dynegy';
       Account acc1 = new Account();
       acc1.name = 'Test Acc1';
       acc1.Billing_Entity__c='Dynegy';
       accLst.add(acc);
       accLst.add(acc1);
       insert accLst;
     
       Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       opp.Accountid = acc.id;
       opp.Service_Territory__c = 'AEPOHIO';
       opp.RecordTypeId = rec.id;
       insert opp;
       
       Retail_Quote__c rq = new Retail_Quote__c();
       rq.Opportunity__c = opp.id;
       rq.Energy__c = 5.8;   
       rq.RecordTypeId = ConstantUtility.getRecordTypeIdbyName('Retail_Quote__c','Indicative');
       rq.Utility_Settlement_Zone__c = 'Test Utility';
       insert rq;
       
       LDC_Account__c lacc = new LDC_Account__c();
       lacc.name  ='Test LDC acc';
       lacc.Account__c = acc.id;
       lacc.Service_Territory__c = 'AEPOHIO';
       lacc.LDC_Account_Number__c = '1234';
       insert lacc;
       LDC_Account__c lacc1 = new LDC_Account__c();
       lacc1.name  ='Test LDC acc1';
       lacc1.Account__c = acc.id;
       lacc1.Service_Territory__c = 'AEPOHIO';
       lacc1.LDC_Account_Number__c = '2345';
       insert lacc1;
       /*Opportunity_LDC__c oppLdc = new Opportunity_LDC__c();
       oppLdc.name = 'Test LDC Acc';
       oppLdc.LDC_Account__c = lacc1.id;   
       oppLdc.Opportunity__c = opp.id;
       insert oppLdc;*/
       ApexPages.currentPage().getParameters().put('masterId',opp.id);
       CreateMultipleOptyLDC cntrl = new CreateMultipleOptyLDC();
       cntrl.cancel();
       cntrl.doNext();
       cntrl.doPrevious();
       cntrl.selectionId = lacc.id;
       cntrl.addSelectedId();
       cntrl.save();
       cntrl.removeSelectedId();
       cntrl.getSelectedCount();
      
       cntrl.getLDCAccounts(); 
       cntrl.getHasPrevious();
       cntrl.getHasNext();
       cntrl.getPageNumber();
       cntrl.getTotalPages();
       cntrl.setHeaderValue();
      cntrl.selectionId = null;
       cntrl.addSelectedId();
       cntrl.removeSelectedId();
    Test.stopTest(); 
 }
  private static testmethod void createMultipleOptyLDCTest1()
 {
    Test.startTest(); 
      RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];
      List<Account> accLst = new List<Account>();
       Account acc = new Account();
       acc.name = 'Test Acc';
       acc.Billing_Entity__c='Dynegy';
       Account acc1 = new Account();
       acc1.name = 'Test Acc1';
       acc1.Billing_Entity__c='Dynegy';
       accLst.add(acc);
       accLst.add(acc1);
       insert accLst;
     
       Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       opp.Accountid = acc.id;
       opp.Service_Territory__c = 'AEPOHIO';
       opp.RecordTypeId = rec.id;
       insert opp;
       
       ApexPages.currentPage().getParameters().put('masterId',opp.id);
       CreateMultipleOptyLDC cntrl = new CreateMultipleOptyLDC();
      
    Test.stopTest(); 
 }
}