src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to store the supplier information at contract level</description>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <description>Rate Ready
DUAL</description>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account__r.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meter__c.object
<CustomObject>
    <description>Custom Object for Meter</description>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Meter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Point__c.object
<CustomObject>
    <description>Object supports service point at the account level with the ability to specify multiple meters.</description>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service Point</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Service Point</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <defaultValue>&quot;1871754&quot;</defaultValue>
        <description>This is Dynergy number and will not change.</description>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Identifier_Code__c</fullName>
        <label>Organization Identifier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Meter__c.object
<CustomObject>
    <description>Object captures vendor meter from the utility.</description>
    <fields>
        <fullName>DASR_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DASR Request</label>
        <referenceTo>DASR_Request__c</referenceTo>
        <relationshipLabel>Vendor Meter</relationshipLabel>
        <relationshipName>Vendor_Meter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Vendor Meter</relationshipLabel>
        <relationshipName>Vendor_Meter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Meter</label>
    <nameField>
        <displayFormat>M-{00000000}</displayFormat>
        <label>Meter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Meter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Meter_Exception__c.object
<CustomObject>
    <description>Object captures vendor meter exceptions from the utility.</description>
    <fields>
        <fullName>DASR_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DASR Request</label>
        <referenceTo>DASR_Request__c</referenceTo>
        <relationshipLabel>Vendor Meter Exceptions</relationshipLabel>
        <relationshipName>Vendor_Meter_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Vendor Meter Exceptions</relationshipLabel>
        <relationshipName>Vendor_Meter_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Meter Exception</label>
    <nameField>
        <displayFormat>VE-{0000000000}</displayFormat>
        <label>Vendor Meter Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Meter Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/updateMeterObjectTest.cls
@isTest(SeeAllData=false)
public class updateMeterObjectTest {
    static  DASR_Request__c reqGAAC;
    static  LDC_Account__c lacc1;
    
    
   static void createTestData(){
        
        Supplier__c testOperatingCompany = new Supplier__c(
                                                        Name='Test Supplier',
                                                        Supplier_DUNS__c = 'DUNSTEST',
                                                        Legacy_ID__c = 'TEST',
                                                        Master_DUNS__c = 'DUNSTEST',
                                                        Organization_Identifier_Code__c = 'TESTSUP',
                                                        Supplier_Code__c = 'TEST',
                                                        ESP_Account_Number__c = 'TEST',
                                                        Active__c = true
                                                      );
        insert testOperatingCompany;
        Account acc = new Account();
        acc.name = 'Test Acc';
        acc.Billing_Entity__c = 'Dynegy' ;
        insert acc;
        
        account acc2 = [select id,name from account where id =: acc.id];
        system.debug('***FirstAssert' + acc2);
        System.assertEquals(acc.name,'Test Acc');
        
        
        Contract testContr = new Contract(
                                                AccountId=acc.Id,
                                                Status='Draft',
                                                StartDate = Date.newInstance(Date.today().year(),Date.today().month(),1),
                                                ContractTerm = 12,
                                                Bill_Method__c = 'DUAL',
                                                Rate_Code__c = 'TEST123',
                                                supplier__c = testOperatingCompany.id,
                                                Contract_Type__c = 'COST_BASED',
                                                Service_Territory__c='AEPOHIO'
                                            );
        insert testContr;
        
        contract testContr2 = [select id,Rate_Code__c  from Contract where id =: testContr.id];
        System.assertEquals(testContr.Rate_Code__c ,'TEST123');
        
        testContr.Status = 'Activated';
        testContr.Contract_Counter_Signed_Date__c = datetime.now();
        update testContr;
        
        lacc1 = new LDC_Account__c();
        lacc1.name  ='Test LDC acc';
        lacc1.Account__c = acc.id;
        lacc1.LDC_Account_Number__c = '12345';
        
        insert lacc1;
        
        LDC_Account__c lacc2 = [select id,name from LDC_Account__c where id =: lacc1.id];
        System.assertEquals(lacc2.name ,'Test LDC acc');

        reqGAAC = new DASR_Request__c();
        reqGAAC.Change_Reason__c = 'Test Reason';
        reqGAAC.LDC_Account__c = lacc1.id;
        reqGAAC.Billing_Entity__c = 'Dynegy';
        reqGAAC.Contract__c = testContr.Id;
        reqGAAC.Integration_Status__c = 'Waiting For Response';
        reqGAAC.DASR_Submit_Date__c = date.today();
        reqGAAC.Change_Effective_Date__c = date.today();
        reqGAAC.DASR_Type__c = 'GAAC';
        insert reqGAAC;
        
        DASR_Request__c reqGAAC2 = [select id,DASR_Type__c  from DASR_Request__c where id =: reqGAAC.id];
        System.assertEquals(reqGAAC2.DASR_Type__c ,'GAAC');
    }
    
    private static testmethod void updateMeterObject_UnitTestForUpdate() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = '123456';
        meter.Meter_Type_Code__c = 'KHMON';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'123456');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'REF4P';
        venException6.Meter_Number__c = '123456';
        insert venException6;
               
        Vendor_Meter_Exception__c venExceptionAssert6 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException6.id];
        System.assertEquals(venExceptionAssert6.Meter_Number__c ,'123456');

        venException6.Reason_Code__c = 'REFLO';
        venException6.Meter_Number__c = 'ALL';
        
        update venException6;
        
        Vendor_Meter_Exception__c venExceptionAssert7 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException6.id];
        System.assertEquals(venExceptionAssert7.Meter_Number__c ,'ALL');
       
        
        Test.stopTest();
        
        
      }
    
     private static testmethod void updateMeterObject_UnitTest3() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = '123456';
        meter.Meter_Type_Code__c = 'KHMON';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'123456');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'REFTU';
        venException6.Meter_Number__c = '123456';
        insert venException6;
               
        Vendor_Meter_Exception__c venExceptionAssert6 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException6.id];
        System.assertEquals(venExceptionAssert6.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException7 = new Vendor_Meter_Exception__c();
        venException7.DASR_Request__c = reqGAAC.id;
        venException7.LDC_Account__c = lacc1.id;
        venException7.Reason_Code__c = 'REFLF';
        venException7.Meter_Number__c = '123456';
        insert venException7;
        
        Vendor_Meter_Exception__c venExceptionAssert7 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException7.id];
        System.assertEquals(venExceptionAssert7.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException8 = new Vendor_Meter_Exception__c();
        venException8.DASR_Request__c = reqGAAC.id;
        venException8.LDC_Account__c = lacc1.id;
        venException8.Reason_Code__c = 'REFSV';
        venException8.Meter_Number__c = '123456';
        insert venException8;
        
        Vendor_Meter_Exception__c venExceptionAssert8 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException8.id];
        System.assertEquals(venExceptionAssert8.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException9 = new Vendor_Meter_Exception__c();
        venException9.DASR_Request__c = reqGAAC.id;
        venException9.LDC_Account__c = lacc1.id;
        venException9.Reason_Code__c = 'NM1MX';
        venException9.Meter_Number__c = '123456';
        insert venException9;
        
        Vendor_Meter_Exception__c venExceptionAssert9 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException9.id];
        System.assertEquals(venExceptionAssert9.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException10 = new Vendor_Meter_Exception__c();
        venException10.DASR_Request__c = reqGAAC.id;
        venException10.LDC_Account__c = lacc1.id;
        venException10.Reason_Code__c = 'NM1MA';
        venException10.Meter_Number__c = '123456';
        insert venException10;
        
        Vendor_Meter_Exception__c venExceptionAssert10 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException10.id];
        System.assertEquals(venExceptionAssert10.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException11 = new Vendor_Meter_Exception__c();
        venException11.DASR_Request__c = reqGAAC.id;
        venException11.LDC_Account__c = lacc1.id;
        venException11.Reason_Code__c = 'REFMT';
        venException11.Meter_Number__c = '123456';
        insert venException11;
        
        Vendor_Meter_Exception__c venExceptionAssert11 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException11.id];
        System.assertEquals(venExceptionAssert11.Meter_Number__c ,'123456');
        
        
        Vendor_Meter_Exception__c venException5 = new Vendor_Meter_Exception__c();
        venException5.DASR_Request__c = reqGAAC.id;
        venException5.LDC_Account__c = lacc1.id;
        venException5.Reason_Code__c = 'NM1MA';
        venException5.Meter_Number__c = '123456';
        insert venException5;
        
        Vendor_Meter_Exception__c venExceptionAssert5 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException5.id];
        System.assertEquals(venExceptionAssert5.Meter_Number__c ,'123456');
        
         Vendor_Meter_Exception__c venException4 = new Vendor_Meter_Exception__c();
        venException4.DASR_Request__c = reqGAAC.id;
        venException4.LDC_Account__c = lacc1.id;
        venException4.Reason_Code__c = 'NM1MX';
        venException4.Meter_Number__c = '123456';
        insert venException4;
        
        Vendor_Meter_Exception__c venExceptionAssert4 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException4.id];
        System.assertEquals(venExceptionAssert4.Meter_Number__c ,'123456');
        
                   
        Test.stopTest();
    }
    
    private static testmethod void updateMeterObject_UnitTest7() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = '123456';
        meter.Meter_Type_Code__c = 'KHMON';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'123456');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'REFTU';
        venException6.Meter_Number__c = '123456';
        
               
        
        
        Vendor_Meter_Exception__c venException7 = new Vendor_Meter_Exception__c();
        venException7.DASR_Request__c = reqGAAC.id;
        venException7.LDC_Account__c = lacc1.id;
        venException7.Reason_Code__c = 'REFLF';
        venException7.Meter_Number__c = '123456';
        
        
        
        
        Vendor_Meter_Exception__c venException8 = new Vendor_Meter_Exception__c();
        venException8.DASR_Request__c = reqGAAC.id;
        venException8.LDC_Account__c = lacc1.id;
        venException8.Reason_Code__c = 'REFSV';
        venException8.Meter_Number__c = '123456';
        
        
        
        
        Vendor_Meter_Exception__c venException9 = new Vendor_Meter_Exception__c();
        venException9.DASR_Request__c = reqGAAC.id;
        venException9.LDC_Account__c = lacc1.id;
        venException9.Reason_Code__c = 'NM1MX';
        venException9.Meter_Number__c = '123456';
       
        
        
        
        Vendor_Meter_Exception__c venException10 = new Vendor_Meter_Exception__c();
        venException10.DASR_Request__c = reqGAAC.id;
        venException10.LDC_Account__c = lacc1.id;
        venException10.Reason_Code__c = 'NM1MA';
        venException10.Meter_Number__c = '123456';
        
        
        
        
        Vendor_Meter_Exception__c venException11 = new Vendor_Meter_Exception__c();
        venException11.DASR_Request__c = reqGAAC.id;
        venException11.LDC_Account__c = lacc1.id;
        venException11.Reason_Code__c = 'REFMT';
        venException11.Meter_Number__c = '123456';
        
        
        
        
        
        Vendor_Meter_Exception__c venException5 = new Vendor_Meter_Exception__c();
        venException5.DASR_Request__c = reqGAAC.id;
        venException5.LDC_Account__c = lacc1.id;
        venException5.Reason_Code__c = 'NM1MA';
        venException5.Meter_Number__c = '123456';
        
        
        
        
         Vendor_Meter_Exception__c venException4 = new Vendor_Meter_Exception__c();
        venException4.DASR_Request__c = reqGAAC.id;
        venException4.LDC_Account__c = lacc1.id;
        venException4.Reason_Code__c = 'NM1MX';
        venException4.Meter_Number__c = '123456';
        
        
        insert new List<Vendor_Meter_Exception__c> {venException6,venException7,venException8,venException9,venException10,venException11,venException5,venException4};
        
                   
        Test.stopTest();
    }
    
    // This test method to test any meter number on vendor meter and meter objects
    private static testmethod void updateMeterObject_UnitTest2() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = '123456';
        meter.Meter_Type_Code__c = 'KHMON';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'123456');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        // insert vendor meter exception
        
        Vendor_Meter_Exception__c venException = new Vendor_Meter_Exception__c();
        venException.DASR_Request__c = reqGAAC.id;
        venException.LDC_Account__c = lacc1.id;
        venException.Reason_Code__c = 'REFTZ';
        venException.Meter_Number__c = '123456';
        insert venException;
        
        Vendor_Meter_Exception__c venExceptionAssert1 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException.id];
        System.assertEquals(venExceptionAssert1.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException2 = new Vendor_Meter_Exception__c();
        venException2.DASR_Request__c = reqGAAC.id;
        venException2.LDC_Account__c = lacc1.id;
        venException2.Reason_Code__c = 'REFNH';
        venException2.Meter_Number__c = '123456';
        insert venException2;
        
        Vendor_Meter_Exception__c venExceptionAssert2 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException2.id];
        System.assertEquals(venExceptionAssert2.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException3 = new Vendor_Meter_Exception__c();
        venException3.DASR_Request__c = reqGAAC.id;
        venException3.LDC_Account__c = lacc1.id;
        venException3.Reason_Code__c = 'REFPR';
        venException3.Meter_Number__c = '123456';
        insert venException3;
        
        Vendor_Meter_Exception__c venExceptionAssert3 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException3.id];
        System.assertEquals(venExceptionAssert3.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException4 = new Vendor_Meter_Exception__c();
        venException4.DASR_Request__c = reqGAAC.id;
        venException4.LDC_Account__c = lacc1.id;
        venException4.Reason_Code__c = 'REFLO';
        venException4.Meter_Number__c = '123456';
        insert venException4;
        
        Vendor_Meter_Exception__c venExceptionAssert4 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException4.id];
        System.assertEquals(venExceptionAssert4.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException5 = new Vendor_Meter_Exception__c();
        venException5.DASR_Request__c = reqGAAC.id;
        venException5.LDC_Account__c = lacc1.id;
        venException5.Reason_Code__c = 'NM1MQ';
        venException5.Meter_Number__c = '123456';
        insert venException5;
        
        Vendor_Meter_Exception__c venExceptionAssert5 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException5.id];
        System.assertEquals(venExceptionAssert5.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'REF4P';
        venException6.Meter_Number__c = '123456';
        insert venException6;
        
        Vendor_Meter_Exception__c venException11 = new Vendor_Meter_Exception__c();
        venException11.DASR_Request__c = reqGAAC.id;
        venException11.LDC_Account__c = lacc1.id;
        venException11.Reason_Code__c = 'REFIX';
        venException11.Meter_Number__c = '123456';
        insert venException11;
        
        Vendor_Meter_Exception__c venExceptionAssert11 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException11.id];
        System.assertEquals(venExceptionAssert11.Meter_Number__c ,'123456');
        
        
        Vendor_Meter_Exception__c venException12 = new Vendor_Meter_Exception__c();
        venException12.DASR_Request__c = reqGAAC.id;
        venException12.LDC_Account__c = lacc1.id;
        venException12.Reason_Code__c = 'NM1MR';
        venException12.Meter_Number__c = '123456';
        insert venException12;
        
        Vendor_Meter_Exception__c venExceptionAssert12 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException12.id];
        System.assertEquals(venExceptionAssert12.Meter_Number__c ,'123456');       
        
        
                  
        Test.stopTest();
    }
    
    
    private static testmethod void updateMeterObject_UnitTest4() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = 'ALL';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'ALL');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        Vendor_Meter_Exception__c venException5 = new Vendor_Meter_Exception__c();
        venException5.DASR_Request__c = reqGAAC.id;
        venException5.LDC_Account__c = lacc1.id;
        venException5.Reason_Code__c = 'NM1MQ';
        venException5.Meter_Number__c = 'ALL';
        insert venException5;
        
        Vendor_Meter_Exception__c venExceptionAssert5 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException5.id];
        System.assertEquals(venExceptionAssert5.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'REF4P';
        venException6.Meter_Number__c = 'ALL';
        insert venException6;
        
        Vendor_Meter_Exception__c venExceptionAssert6 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException6.id];
        System.assertEquals(venExceptionAssert6.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException7 = new Vendor_Meter_Exception__c();
        venException7.DASR_Request__c = reqGAAC.id;
        venException7.LDC_Account__c = lacc1.id;
        venException7.Reason_Code__c = 'REFLF';
        venException7.Meter_Number__c = 'ALL';
        insert venException7;
        
        Vendor_Meter_Exception__c venExceptionAssert7 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException7.id];
        System.assertEquals(venExceptionAssert7.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException8 = new Vendor_Meter_Exception__c();
        venException8.DASR_Request__c = reqGAAC.id;
        venException8.LDC_Account__c = lacc1.id;
        venException8.Reason_Code__c = 'REFSV';
        venException8.Meter_Number__c = 'ALL';
        insert venException8;
        
        Vendor_Meter_Exception__c venExceptionAssert8 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException8.id];
        System.assertEquals(venExceptionAssert8.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException9 = new Vendor_Meter_Exception__c();
        venException9.DASR_Request__c = reqGAAC.id;
        venException9.LDC_Account__c = lacc1.id;
        venException9.Reason_Code__c = 'REFMT';
        venException9.Meter_Number__c = 'ALL';
        insert venException9;
        
        Vendor_Meter_Exception__c venExceptionAssert9 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException9.id];
        System.assertEquals(venExceptionAssert9.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException10 = new Vendor_Meter_Exception__c();
        venException10.DASR_Request__c = reqGAAC.id;
        venException10.LDC_Account__c = lacc1.id;
        venException10.Reason_Code__c = 'REFTU';
        venException10.Meter_Number__c = 'ALL';
        insert venException10;
        
        Vendor_Meter_Exception__c venExceptionAssert10 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException10.id];
        System.assertEquals(venExceptionAssert10.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException11 = new Vendor_Meter_Exception__c();
        venException11.DASR_Request__c = reqGAAC.id;
        venException11.LDC_Account__c = lacc1.id;
        venException11.Reason_Code__c = 'REFIX';
        venException11.Meter_Number__c = 'ALL';
        insert venException11;
        
        Vendor_Meter_Exception__c venExceptionAssert11 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException11.id];
        System.assertEquals(venExceptionAssert11.Meter_Number__c ,'ALL');
        
        
        Vendor_Meter_Exception__c venException12 = new Vendor_Meter_Exception__c();
        venException12.DASR_Request__c = reqGAAC.id;
        venException12.LDC_Account__c = lacc1.id;
        venException12.Reason_Code__c = 'NM1MR';
        venException12.Meter_Number__c = 'ALL';
        insert venException12;
        
        Vendor_Meter_Exception__c venExceptionAssert12 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException12.id];
        System.assertEquals(venExceptionAssert12.Meter_Number__c ,'ALL');
        
                   
        Test.stopTest();
    }
    
    // This test method to test where meter number equals ALL on vendor meter
    private static testmethod void updateMeterObject_UnitTest() 
    {
        Test.startTest();
        
        createTestData();
        
        //insert vendor meter
        Vendor_Meter__c meter = new Vendor_Meter__c();
        meter.DASR_Request__c = reqGAAC.id;
        meter.LDC_Account__c = lacc1.id;
        meter.Meter_Number__c = 'ALL';
        insert meter;
        
        Vendor_Meter__c meter2 = [select id,Meter_Number__c from Vendor_Meter__c where id =: meter.id];
        System.assertEquals(meter2.Meter_Number__c,'ALL');
        
        //insert Service_Point__c
        Service_Point__c point = new Service_Point__c();
        point.LDC_Account_Number__c = lacc1.id;
        point.Service_Point_Number__c = 'Test9848484';
        insert point;
        
        Service_Point__c point2 = [select id,Service_Point_Number__c  from Service_Point__c where id =: point.id];
        System.assertEquals(point2.Service_Point_Number__c ,'Test9848484');
        
        //insert meter Meter__c
        
        Meter__c meterObj = new Meter__c();
        meterObj.Service_Point__c = point.id;
        meterObj.Meter_Number__c = '123456';
        insert meterObj;
        
        Meter__c meterObj2 = [select id,Meter_Number__c  from Meter__c where id =: meterObj.id];
        System.assertEquals(meterObj2.Meter_Number__c ,'123456');
        
        // insert vendor meter exception
        
        Vendor_Meter_Exception__c venException = new Vendor_Meter_Exception__c();
        venException.DASR_Request__c = reqGAAC.id;
        venException.LDC_Account__c = lacc1.id;
        venException.Reason_Code__c = 'REFNH';
        venException.Meter_Number__c = 'ALL';
        insert venException;
        
        Vendor_Meter_Exception__c venExceptionAssert1 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException.id];
        System.assertEquals(venExceptionAssert1.Meter_Number__c ,'ALL');
        
               
        Vendor_Meter_Exception__c venException2 = new Vendor_Meter_Exception__c();
        venException2.DASR_Request__c = reqGAAC.id;
        venException2.LDC_Account__c = lacc1.id;
        venException2.Reason_Code__c = 'REFTZ';
        venException2.Meter_Number__c = 'ALL';
        insert venException2;
        
        Vendor_Meter_Exception__c venExceptionAssert2 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException2.id];
        System.assertEquals(venExceptionAssert2.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException3 = new Vendor_Meter_Exception__c();
        venException3.DASR_Request__c = reqGAAC.id;
        venException3.LDC_Account__c = lacc1.id;
        venException3.Reason_Code__c = 'REFPR';
        venException3.Meter_Number__c = 'ALL';
        insert venException3;
        
        Vendor_Meter_Exception__c venExceptionAssert3 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException3.id];
        System.assertEquals(venExceptionAssert3.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException4 = new Vendor_Meter_Exception__c();
        venException4.DASR_Request__c = reqGAAC.id;
        venException4.LDC_Account__c = lacc1.id;
        venException4.Reason_Code__c = 'REFLO';
        venException4.Meter_Number__c = 'ALL';
        insert venException4;
        
        Vendor_Meter_Exception__c venExceptionAssert4 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException4.id];
        System.assertEquals(venExceptionAssert4.Meter_Number__c ,'ALL');
        
        Vendor_Meter_Exception__c venException5 = new Vendor_Meter_Exception__c();
        venException5.DASR_Request__c = reqGAAC.id;
        venException5.LDC_Account__c = lacc1.id;
        venException5.Reason_Code__c = 'NM1MA';
        venException5.Meter_Number__c = 'ALL';
        insert venException5;
        
        Vendor_Meter_Exception__c venExceptionAssert5 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException5.id];
        System.assertEquals(venExceptionAssert5.Meter_Number__c ,'ALL');
        
         Vendor_Meter_Exception__c venException6 = new Vendor_Meter_Exception__c();
        venException6.DASR_Request__c = reqGAAC.id;
        venException6.LDC_Account__c = lacc1.id;
        venException6.Reason_Code__c = 'NM1MX';
        venException6.Meter_Number__c = 'ALL';
        insert venException6;
        
        Vendor_Meter_Exception__c venExceptionAssert6 = [select id,Meter_Number__c from Vendor_Meter_Exception__c where id =: venException6.id];
        System.assertEquals(venExceptionAssert6.Meter_Number__c ,'ALL');
               
        
        Test.stopTest();
        
    }    
}