src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>This field is created during the iAve conversion.</description>
        <label>Service State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Retail_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Quote</label>
        <referenceTo>Retail_Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Type_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a matrix of Contract Type selections based on Service Territory and Bill Method
Defining Below As Name field Length is limited to 40
CT1 - Small Stable Contract - Evergreen
CT2 - Small Stable Contract - MTM Renewal
CT3 - Large Stable Contract
CT4 - Large Stable PT-C Contract
CT5 - Hybrid
CT6 - Block and Index</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contract Type Setting</label>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>Service State Address State for LDC Account</description>
        <label>Service State</label>
        <length>165</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK         </fullName>
                </value>
                <value>
                    <fullName>AL          </fullName>
                </value>
                <value>
                    <fullName>AR         </fullName>
                </value>
                <value>
                    <fullName>AZ          </fullName>
                </value>
                <value>
                    <fullName>CA         </fullName>
                </value>
                <value>
                    <fullName>CO         </fullName>
                </value>
                <value>
                    <fullName>CT          </fullName>
                </value>
                <value>
                    <fullName>DC         </fullName>
                </value>
                <value>
                    <fullName>DE          </fullName>
                </value>
                <value>
                    <fullName>FL           </fullName>
                </value>
                <value>
                    <fullName>GA         </fullName>
                </value>
                <value>
                    <fullName>HI           </fullName>
                </value>
                <value>
                    <fullName>IA           </fullName>
                </value>
                <value>
                    <fullName>ID           </fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN          </fullName>
                </value>
                <value>
                    <fullName>KS          </fullName>
                </value>
                <value>
                    <fullName>KY          </fullName>
                </value>
                <value>
                    <fullName>LA          </fullName>
                </value>
                <value>
                    <fullName>MA        </fullName>
                </value>
                <value>
                    <fullName>MD        </fullName>
                </value>
                <value>
                    <fullName>ME         </fullName>
                </value>
                <value>
                    <fullName>MI          </fullName>
                </value>
                <value>
                    <fullName>MN        </fullName>
                </value>
                <value>
                    <fullName>MO        </fullName>
                </value>
                <value>
                    <fullName>MS         </fullName>
                </value>
                <value>
                    <fullName>MT         </fullName>
                </value>
                <value>
                    <fullName>NC         </fullName>
                </value>
                <value>
                    <fullName>ND         </fullName>
                </value>
                <value>
                    <fullName>NE         </fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <label>Utility Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Amendment</fullName>
        <active>true</active>
        <businessProcess>Dynegy</businessProcess>
        <description>Used to create an Amendment Opportunity</description>
        <label>Amendment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/CreateContractFromQuoteControllerTest.cls
/* 
 * Name: CreateContractFromQuoteControllerTest
 * Type: Apex Test Coverage  
 * Description: Test coverage for the CreateContractFromQuoteController Apex Controller.         
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         03/21/2016       1. Initial Version created
 */
@isTest
private class CreateContractFromQuoteControllerTest {

    static testMethod void CreateContractFromQuoteController_UnitTest() {
       ID optyRecId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Standard Opportunity').RecordTypeId;
       ID optyRecAmndId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Amendment').RecordTypeId;
       RecordType rtExec = [select id,name from RecordType where name='Executable' and sobjectType='Retail_Quote__c' limit 1];
        
       Account tstAccRec=new Account(Name='Test Account 001',Billing_Entity__c='Dynegy');
       Insert tstAccRec;
       
       Opportunity tstOppRec = new Opportunity(Name='Test Opty 001', Service_Territory__c='DAYTON', StageName='New',AccountId=tstAccRec.id,RecordTypeId=optyRecId,CloseDate = date.today().addDays(7));
       Insert tstOppRec;
       
       LDC_Vendor__c tstRecLDCVendor=new LDC_Vendor__c(Name='Test Vendor CCQ001',Service_Territory__c='DAYTON',DUNS__c='CCQ001',Utility_Code__c='CCQ0001',Service_State__c='OH');
       Insert tstRecLDCVendor;
       
       LDC_Account__c tstRecLDCAcc=new LDC_Account__c(Name='Test LDC Account CCQ001',Account__c=tstAccRec.Id,Service_Territory__c='DAYTON',LDC_Vendor__c=tstRecLDCVendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='TSTCCQ0001');
       Insert tstRecLDCAcc;
       
       Opportunity_LDC__c tstOLDCRec = new Opportunity_LDC__c(LDC_Account__c=tstRecLDCAcc.id,Opportunity__c=tstOppRec.id);
       Insert tstOLDCRec;
       
       Rate_Code__c tstRCRec = new Rate_Code__c(Name='TSTRC001',Price__c=0.00501,Service_Territory__c='DAYTON');
       Insert tstRCRec;
       
       Retail_Quote__c tstRQRec = new Retail_Quote__c(Opportunity__c=tstOppRec.id,RecordTypeId=rtExec.id,Request_Status__c = 'Pricing Complete',Quote_Price_KWH__c=0.00501,Term__c=12,Utility_Settlement_Zone__c = 'Test Utility');
       insert tstRQRec;
       
       String OptyContract = CreateContractFromQuoteController.contractExists(null);
       system.assertEquals(OptyContract,'NA');
       String RQContract = CreateContractFromQuoteController.contractExistsOnQuote(null);
       system.assertEquals(RQContract,'NA');
       
       OptyContract = CreateContractFromQuoteController.contractExists(tstOppRec.id);
       system.assertEquals(OptyContract,'NO');
       RQContract = CreateContractFromQuoteController.contractExistsOnQuote(tstRQRec.id);
       system.assertEquals(RQContract,'NO');
       
       Test.startTest();
       PageReference pageRef = Page.CreateContractFromQuote;
       Test.setCurrentPage(pageRef);
       
       ApexPages.StandardController sc = new ApexPages.StandardController(tstRQRec);
       CreateContractFromQuoteController CCQcontroller = new CreateContractFromQuoteController(sc);
       CCQcontroller.finishRequest();
       
       CCQcontroller.contractName = 'Test Contract CCQ001';
       CCQcontroller.quoteContract.Contract_Type__c = 'COST_BASED';
       CCQcontroller.quoteContract.Bill_Method__c = 'UCB';
       CCQcontroller.quoteContract.Contract_Counter_Signed_Date__c = system.now();
       
       CCQcontroller.finishRequest();
       CCQcontroller.exitRequest();
       
       PageReference tstRef = CCQcontroller.cancelCode();
       tstRef = CCQcontroller.submitCode();
       tstRef = CCQcontroller.findRateCode();
       
       
        
    }
    
    static testMethod void CreateContractFromQuoteController_UnitTest2() {
       ID optyRecAmndId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Amendment').RecordTypeId;
       RecordType rtExec = [select id,name from RecordType where name='Executable' and sobjectType='Retail_Quote__c' limit 1];
        
       Account tstAccRec=new Account(Name='Test Account 001',Billing_Entity__c='Dynegy');
       Insert tstAccRec;
       
       Contract ct=new Contract(Name='Test Contract 2',StartDate=Date.today().addmonths(-1),Status='Draft',AccountId=tstAccRec.Id,contractTerm=12);
       insert ct;
        
       ct.Status='Activated';
       ct.Contract_Counter_Signed_Date__c = datetime.now();
       update ct;
    
       ct = [select id,name,contractnumber from contract];
       
       Opportunity tstOppRec = new Opportunity(Name='Test Opty Amnd', Service_Territory__c='DAYTON', StageName='New',AccountId=tstAccRec.id,RecordTypeId=optyRecAmndId,CloseDate = date.today().addDays(7),contractid=ct.id);
       insert tstOppRec;
       
       LDC_Vendor__c tstRecLDCVendor=new LDC_Vendor__c(Name='Test Vendor CCQ001',Service_Territory__c='DAYTON',DUNS__c='CCQ001',Utility_Code__c='CCQ0001',Service_State__c='OH');
       insert tstRecLDCVendor;
       
       LDC_Account__c tstRecLDCAcc=new LDC_Account__c(Name='Test LDC Account CCQ002',Account__c=tstAccRec.Id,Service_Territory__c='DAYTON',LDC_Vendor__c=tstRecLDCVendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='TSTCCQ0002');
       insert tstRecLDCAcc;
       
       Opportunity_LDC__c tstOLDCRec = new Opportunity_LDC__c(LDC_Account__c=tstRecLDCAcc.id,Opportunity__c=tstOppRec.id);
       insert tstOLDCRec;
    
       Retail_Quote__c tstRQRec = new Retail_Quote__c(Opportunity__c=tstOppRec.id,RecordTypeId=rtExec.id,Request_Status__c = 'Pricing Complete',Quote_Price_KWH__c=0.05501,Term__c=12,Utility_Settlement_Zone__c = 'Test Utility');
       insert tstRQRec;
       
       Contract_Type_Setting__c ctypes = new Contract_Type_Setting__c(Name='DAYTON-DUAL',Bill_Method__c='DUAL',Contract_Type__c='UCBNONPOR',Service_Territory__c='DAYTON');
       insert ctypes;
       
       Test.startTest();
       PageReference pageRef = Page.CreateContractFromQuote;
       Test.setCurrentPage(pageRef);
       
       ApexPages.StandardController sc = new ApexPages.StandardController(tstRQRec);
       CreateContractFromQuoteController CCQcontroller = new CreateContractFromQuoteController(sc);
       
       CCQcontroller.contractName = 'Test Contract CCQ002';
       CCQcontroller.quoteContract.Bill_Method__c = 'DUAL';
       //Contract_Type_Setting__c cts = Contract_Type_Setting__c.getvalues('DAYTON-DUAL');
       CCQcontroller.finishRequest();
       
       CCQcontroller.quoteContract.Contract_Type__c = 'COST_BASED';
       CCQcontroller.quoteContract.Bill_Method__c = 'UCB';
       CCQcontroller.quoteContract.Contract_Counter_Signed_Date__c = system.now();
       CCQcontroller.finishRequest();
    
       Test.stopTest();
        
    }
}