src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>This field is created during the iAve conversion.</description>
        <label>Service State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CnI</fullName>
        <active>true</active>
        <description>For Commercial and Industrial Customer</description>
        <label>C&amp;I Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Type_Settings__c.object
<CustomObject>
    <description>Object supports Account Type mapping from Contract, Contract Type, Bill Method and Service Territory.</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Account Type Settings</label>
    <nameField>
        <displayFormat>ATS-{0000}</displayFormat>
        <label>Account Type Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Type Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to store the supplier information at contract level</description>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>Service State Address State for LDC Account</description>
        <label>Service State</label>
        <length>165</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account__r.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <label>Utility Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Type__c</fullName>
        <description>Types of LDC Vendor</description>
        <label>Vendor Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ESP</fullName>
                </value>
                <value>
                    <fullName>LDC</fullName>
                </value>
                <value>
                    <fullName>MDMA</fullName>
                </value>
                <value>
                    <fullName>Meter Installer</fullName>
                </value>
                <value>
                    <fullName>Meter Owner</fullName>
                </value>
                <value>
                    <fullName>Meter Reader</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>Registration Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <defaultValue>&quot;1871754&quot;</defaultValue>
        <description>This is Dynergy number and will not change.</description>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Identifier_Code__c</fullName>
        <label>Organization Identifier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/Flow_SetActLDCActTypeCodeTest.cls
/**
 * The purpose of this class is to provide code coverage to the
 * Flow_SetAccountLDCAcctTypeCode class
 *
 * @author Chris Gary <cgary@cloudperformer.com>
 * @version 1.0
 **/
@isTest
public class Flow_SetActLDCActTypeCodeTest{
    private static void SetupTestData(){
      //first we need to create a test Account
        Schema.DescribeSObjectResult dsr = Account.SObjectType.getDescribe();
        Map<String,Schema.RecordTypeInfo> acctRecTypeMap = dsr.getRecordTypeInfosByName();
        Schema.RecordTypeInfo ciAcctRecType = acctRecTypeMap.get('C&I Customer');
        //we need to create a test operating company
        Supplier__c testOperatingCompany = new Supplier__c(
                                                        Name='Test Supplier',
                                                        Supplier_DUNS__c = 'DUNSTEST',
                                                        Legacy_ID__c = 'TEST',
                                                        Master_DUNS__c = 'DUNSTEST',
                                                        Organization_Identifier_Code__c = 'TESTSUP',
                                                        Supplier_Code__c = 'TEST',
                                                        ESP_Account_Number__c = 'TEST',
                                                        Active__c = true
                                                      );
        insert testOperatingCompany;
        LDC_Vendor__c testVendor = new LDC_Vendor__c(
                                                        Name='Test Vendor',
                                                        DUNS__c = 'U698DWJ9',
                                                        Legacy_ID__c = 'TVNDR',
                                                        Service_Territory__c = 'AEPOHIO',
                                                        Utility_Code__c = 'TST',
                                                        Vendor_Type__c = 'LDC',
                                                        Service_State__c = 'OH'
                                                    );
        insert testVendor;
        Account testAcct = new Account(
                                        Name='Test CnI',
                                        Supplier__c = testOperatingCompany.Id,
                                        BillingStreet = '2114 Bates Brothers Road',
                                        BillingCity = 'Westerville',
                                        BillingState = 'OH',
                                        BillingPostalCode = '43081',
                                        Billing_Entity__c='Dynegy'
                                        );
        insert testAcct;
        LDC_Account__c ldc1 = new LDC_Account__c(   Name = DynegyCommonUtils.generateRandomString(10),
                                                    Account__c=testAcct.Id,Service_Territory__c='AEPOHIO',
                                                    LDC_Account_Number__c = DynegyCommonUtils.generateRandomString(10),
                                                    Service_Street_1__c = '4048 Vineyard Drive',
                                                    Service_City__c = 'Solon',
                                                    Service_State__c = 'OH',
                                                    Service_Postal_Code__c = '44139'
                                                    );
        
        LDC_Account__c ldc2 = new LDC_Account__c(   Name = DynegyCommonUtils.generateRandomString(10),
                                                    Account__c=testAcct.Id,Service_Territory__c='AEPOHIO',
                                                    LDC_Account_Number__c = DynegyCommonUtils.generateRandomString(10),
                                                    Service_Street_1__c = '4048 Vineyard Drive',
                                                    Service_City__c = 'Solon',
                                                    Service_State__c = 'OH',
                                                    Service_Postal_Code__c = '44139'
                                                    );
        LDC_Account__c ldc3 = new LDC_Account__c(   Name = DynegyCommonUtils.generateRandomString(10),
                                                    Account__c=testAcct.Id,Service_Territory__c='AEPOHIO',
                                                    LDC_Account_Number__c = DynegyCommonUtils.generateRandomString(10),
                                                    Service_Street_1__c = '4048 Vineyard Drive',
                                                    Service_City__c = 'Solon',
                                                    Service_State__c = 'OH',
                                                    Service_Postal_Code__c = '44139'
                                                    );
        insert new list<LDC_Account__c>{ldc1,ldc2,ldc3};
        
        //create test Contract
        Contract cnt1 = new Contract(
                                                AccountId=testAcct.Id,
                                                Name='',
                                                Status='Draft',
                                                StartDate = Date.newInstance(Date.today().year(),Date.today().month(),1),
                                                ContractTerm = 12,
                                                Bill_Method__c = 'DUAL',
                                                Rate_Code__c = 'TEST123',
                                                Contract_Type__c = 'UCBNONPOR',
                                                Service_Territory__c='AEPOHIO'
                                            );
        Contract cnt2 = new Contract(
                                                AccountId=testAcct.Id,
                                                Name='',
                                                Status='Draft',
                                                StartDate = Date.newInstance(Date.today().year(),Date.today().month(),1),
                                                ContractTerm = 12,
                                                Bill_Method__c = 'DUAL',
                                                Rate_Code__c = 'TEST123',
                                                Contract_Type__c = 'Large Stable Contract',
                                                Service_Territory__c='AEPOHIO'
                                            );                                    
        Contract cnt3 = new Contract(
                                                AccountId=testAcct.Id,
                                                Name='',
                                                Status='Draft',
                                                StartDate = Date.newInstance(Date.today().year(),Date.today().month(),1),
                                                ContractTerm = 12,
                                                Bill_Method__c = 'DUAL',
                                                Rate_Code__c = 'TEST123',
                                                Contract_Type__c = 'Block and Index',
                                                Service_Territory__c='AEPOHIO'
                                            );
        insert new list<Contract>{cnt1,cnt2,cnt3};
        //activate the Contract
        cnt1.Status = 'Activated';
        cnt1.Contract_Counter_Signed_Date__c = datetime.now();
        cnt2.Status = 'Activated';
        cnt2.Contract_Counter_Signed_Date__c = datetime.now();
        cnt3.Status = 'Activated';
        cnt3.Contract_Counter_Signed_Date__c = datetime.now();
        update new list<Contract>{cnt1,cnt2,cnt3};
        //create Contract LDC Record
        Contract_LDC__c cldc1 = new Contract_LDC__c( LDC_Account__c=ldc1.Id,Contract__c = cnt1.Id);
        Contract_LDC__c cldc2 = new Contract_LDC__c( LDC_Account__c=ldc2.Id,Contract__c = cnt2.Id);
        Contract_LDC__c cldc3 = new Contract_LDC__c( LDC_Account__c=ldc3.Id,Contract__c = cnt3.Id);
        insert new list<Contract_LDC__c>{cldc1,cldc2,cldc3};
        //create DASR Record for enrollment
        DASR_Request__c dasr1 = new DASR_Request__c(Contract__c = cnt1.Id,LDC_Account__c = ldc1.Id,DASR_Type__c = 'GAAE',DASR_Submit_Date__c = Datetime.now(),
                                                            Integration_Status__c = 'Pending',Change_Effective_Date__c = Date.today(),Billing_Entity__c='Dynegy');
        
        DASR_Request__c dasr2 = new DASR_Request__c(Contract__c = cnt2.Id,LDC_Account__c = ldc2.Id,DASR_Type__c = 'GAAE',DASR_Submit_Date__c = Datetime.now(),
                                                            Integration_Status__c = 'Pending',Change_Effective_Date__c = Date.today(),Billing_Entity__c='Dynegy');
        
        DASR_Request__c dasr3 = new DASR_Request__c(Contract__c = cnt3.Id,LDC_Account__c = ldc3.Id,DASR_Type__c = 'GAAE',DASR_Submit_Date__c = Datetime.now(),
                                                            Integration_Status__c = 'Pending',Change_Effective_Date__c = Date.today(),Billing_Entity__c='Dynegy');
        insert new list<DASR_Request__c>{dasr1,dasr2,dasr3};
         //may need to create new custom setting record.
        Account_Type_Settings__c setting1  = new Account_Type_Settings__c(
                                
                                                                    Account_Type_Code__c = 'UCBNONPOR_RR',
                                                                    Contract_Type__c = 'UCBNONPOR',
                                                                    Service_Territory__c = 'AEPOHIO'
                                                                  );
        Account_Type_Settings__c setting2  = new Account_Type_Settings__c(
                                
                                                                    Account_Type_Code__c = 'RETAIL_STANDALONE',
                                                                    Contract_Type__c = 'Large Stable Contract',
                                                                    Service_Territory__c = 'AEPOHIO',
                                                                    Bill_Method__c = 'DUAL'
                                                                  );
        Account_Type_Settings__c setting3  = new Account_Type_Settings__c(
                                
                                                                    Account_Type_Code__c = 'UCBNONPOR',
                                                                    Contract_Type__c = 'Large Stable Contract',
                                                                    Service_Territory__c = 'AEPOHIO',
                                                                    Bill_Method__c = 'Rate Ready'
                                                                  );
        Account_Type_Settings__c setting4  = new Account_Type_Settings__c(
                                
                                                                    Account_Type_Code__c = 'RETAIL_STANDALONE',
                                                                    Contract_Type__c = 'Block and Index',
                                                                    Service_Territory__c = 'AEPOHIO',
                                                                    Bill_Method__c = 'DUAL'
                                                                  );
        insert new list<Account_Type_Settings__c>{setting1,setting2,setting3,setting4};
    }
    
    @isTest
    public static void SetAccountLDCInfoFROMContractLDC(){
      SetupTestData();
      
      Test.startTest();
      
      List<Id> testIdList = new List<Id>();
      for(Contract_LDC__c cldc : [SELECT Id,ldc_account__c,contract__c FROM Contract_LDC__c]){
        testIdList.add(cldc.Id);
      }
      
      Flow_SetAccountLDCAcctTypeCode.SetAccountLDCInfoFROMContractLDC(testIdList);
      
      Test.stopTest();
    }
}