src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LodeStar_Integration_Status__c</fullName>
        <description>The Status of this record as it relates to LodeStar having the most up-to-date information.</description>
        <inlineHelpText>Indicates the data was sent to Lodestar, but does not confirm it was received successfully.  The field must be in &quot;Not Synchronized.&quot; See Document &quot;SF to LS Integration.docx&quot; for more details.</inlineHelpText>
        <label>LodeStar Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Synchronized</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Synchronized</fullName>
                </value>
                <value>
                    <fullName>Test Synchronized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validation__c</fullName>
        <label>Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>LodeStar_Identifier__c</fullName>
        <description>A unique Field for Lode Star to Identify the Contracts</description>
        <label>LodeStar Identifier</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation__c</fullName>
        <label>Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSynchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</description>
        <inlineHelpText>Checkbox to represent whether Contract LDC Record ben synchronized with the Billing system.</inlineHelpText>
        <label>Is Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LodeStar_Identifier__c</fullName>
        <description>Unique Field To Identify Lodestar Transaction</description>
        <label>LodeStar Identifier</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <label>Term Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_End_Date__c</fullName>
        <description>End Date for the LDC</description>
        <label>LDC End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LDC_Start_Date__c</fullName>
        <description>Start Date of the LDC</description>
        <label>LDC Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <formula>Account__r.Short_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Short Code</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LodeStar_Errors__c.object
<CustomObject>
    <description>Object supports webservice failures by account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Related Account the Error is from.</description>
        <inlineHelpText>The related Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LodeStar Errors</relationshipLabel>
        <relationshipName>LodeStar_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ErrorMsg__c</fullName>
        <label>ErrorMsg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExceptionTime__c</fullName>
        <label>ExceptionTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ShortCode__c</fullName>
        <label>ShortCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>LodeStar Errors</label>
    <nameField>
        <label>LodeStar Errors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LodeStar Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/lodeStarValidator.cls
global class lodeStarValidator implements Database.Batchable<SObject>,System.Schedulable,Database.Stateful{
    global set<id> accountsNotsync;
    public lodeStarValidator(){       
        
    }
    
    global void execute (SchedulableContext sc){
        lodeStarValidator lsvsc = new lodeStarValidator();
        Database.executeBatch(lsvsc,1000);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
           //Changes for Ticket 565
        set<string> recordtypename = new set<string>();
        recordtypename = LodestarUtil.getrecordtype();
        system.debug('Return types : '+recordtypename);
        
        string ST1 = label.Lodestar_ServiceTerritory;
        List<string> st2 = new List<string>();
        st2 = ST1.split(';');
        system.debug('Service Territory : '+st2);
        
        string query ='SELECT Id, LDC_Account__r.Account__c,Contract__c, ldc_account__r.ldc_start_date__c, ldc_account__r.ldc_end_date__c FROM Contract_LDC__c '+
                        'WHERE LDC_Account__r.Account__r.LodeStar_Integration_Status__c = \'Not Synchronized\' AND  Contract__r.Validation__c = \'Validated\' '+
                        'AND (LDC_Account__r.LDC_Account_Status__c=\'ACTIVE\' OR LDC_Account__r.LDC_Account_Status__c=\'FINAL\' OR LDC_Account__r.LDC_Account_Status__c=\'NEVER_SERVED\') AND Term_Start_Date__c != null '+
                        'AND issynchronized__c = false '; // Term_Start_Date__c <= TODAY and 
       
        if(recordtypename != null && recordtypename.size()>0)
        query+= ' AND (LDC_Account__r.Account__r.RecordType.Name In: recordtypename or LDC_Account__r.Service_Territory__c In: st2) order by LDC_Account__r.Account__c';
        else 
        query+= '  order by LDC_Account__r.Account__c';             
                        
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        
        list<contract_ldc__c> cldclst = (list<contract_ldc__c>)scope;
        list<Account> accountsToUpdate = new list<Account>();
        list<LodeStar_Errors__c> lodeStarErrors = new list<LodeStar_Errors__c>();     
        set<id> Totalaccounts = new set<id>();
        set<id> ldcAccountsError = new set<id>();
        set<id> conLDCAll= new set<id>();
        set<id> ldcAccounts = new set<id>();
        set<id> cntrSet = new set<id>();
        set<id> cntError = new set<id>();   
        set<id> acntError = new set<id>();
        map<id,string> ldcmap = new map<id,string>(); 
        map<id,string> cntmap = new map<id,string>();
        map<id,string> accmap = new map<id,string>();
        string errstr='';
        if(accountsNotsync  == null)
            accountsNotsync = new set<id>();
        for(contract_ldc__c cldc : cldclst){
            ldcAccounts.add(cldc.ldc_account__C);
            conLDCAll.add(cldc.id);
            Totalaccounts.add(cldc.LDC_Account__r.Account__c);
            cntrset.add(cldc.Contract__c);         
        }
        list<contract_ldc__c> conldclst = [select id, term_start_date__C, ldc_account__c,ldc_account__r.account__r.id, issynchronized__c, contract__c from contract_ldc__c where ldc_account__c in :ldcAccounts and issynchronized__c = false and (contract__r.validation__c != 'Validated' or contract__r.validation__c = null)];
        system.debug('conldclst :'+conldclst);
        for(contract_ldc__c clst: conldclst){
            if(!conLDCAll.contains(clst.id)){
                accountsNotsync.add(clst.ldc_account__r.account__r.id);
            }
        }      
        system.debug('Accounts to set Notsync : '+accountsNotsync);
        system.debug(' Contract Set : '+cntrset);
          
        if(!cntrset.isEmpty()){ // update LodeStar_Identifier__c field for Unique identity
            list<contract> cntidentifier = new list<contract>(); 
            for(contract cnt : [select id,name,status,LodeStar_Identifier__c,accountId,account.name,opportunity__r.accountId,opportunity__r.account.name,contractnumber from contract where ID In : cntrset]){              
                if(cnt.opportunity__r.accountId != null && cnt.accountId != cnt.opportunity__r.accountId){
                    cntError.add(cnt.id);
                    errstr+='Contract\'s Account '+cnt.Account.name+' and Contract\'s Opportunity Account '+cnt.opportunity__r.account.name+'are mismatched for contract '+cnt.contractnumber+'\n';
                    system.debug('Contract Has a error : '+cnt.id+' : '+cnt.contractnumber);
                }
                
                if(cnt.status == 'Draft' || cnt.status == 'Cancelled'){
                    cntError.add(cnt.id);
                    errstr+=cnt.status+' status contracts cannot be sent to lodestar '+cnt.contractnumber+'\n';
                }
                
                if(cnt.LodeStar_Identifier__c == null){
                    cnt.LodeStar_Identifier__c=DynegyCommonUtils.generateRandomString(20);
                    cntidentifier.add(cnt);
                }
                cntmap.put(cnt.id,errstr);
            }
            if(!cntidentifier.isempty())  update cntidentifier;
        }
            
        for(contract_ldc__c cldc : cldclst){
            system.debug('Contract : '+cntError.size()+' : '+cntError+'-->'+cldc.contract__c);
            if(cntError.contains(cldc.contract__c)){
                acntError.add(cldc.LDC_Account__r.Account__c);
                accmap.put(cldc.LDC_Account__r.Account__c,cntmap.get(cldc.contract__c));
            }
        }
        system.debug('AccMap : '+accmap);
        system.debug(' Removing Account ID Set : '+acntError.size()+' : '+acntError);

        for(Account a:[SELECT Id, LodeStar_Integration_Status__c, Short_Code__c FROM Account WHERE Id IN :acntError]){
            string msg = accmap.get(a.id);
            a.LodeStar_Integration_Status__c = 'ERROR';
            accountsToUpdate.add(a);
            lodeStarErrors.add(new LodeStar_Errors__c(
                Name = 'Account Error',
                Account__c = a.Id,
                ErrorMsg__c = 'Errored before payload is generated : \n '+msg,
                ExceptionTime__c = Datetime.now(),
                ShortCode__c = a.Short_Code__c
            ));
        }
        if(!accountsToUpdate.isEmpty()) update accountsToUpdate;
        if(!lodeStarErrors.isEmpty()) insert lodeStarErrors;
       
    }
    
    global void finish(Database.BatchableContext bc){
        set<id> processedAccounts = new set<id>();
        AsyncApexJob aJob = new AsyncApexJob();
        system.debug('bid : '+BC.getJobId());
        aJob = [SELECT CompletedDate,CreatedDate,Id,JobItemsProcessed,JobType,LastProcessed,NumberOfErrors,ParentJobId, Status,TotalJobItems FROM AsyncApexJob WHERE Id =: BC.getJobId() ];
        system.debug('AsyncApexJob : '+aJob);
        if(aJob != null && aJob.status == 'Completed'){
            for(account acc : [select id from account where lastmodifieddate >= : aJob.createddate and lastmodifieddate <= : aJob.completedDate and lodestar_integration_status__c = 'ERROR']){
                processedAccounts.add(acc.id);
            }
            set<id> accToProcess = LodeStarActions.ObtainNonSynchronizedAccounts();
            System.debug('accountsNotsync :'+accountsNotsync);
            processedAccounts.addAll(accToProcess);
            if(!accToProcess.isempty() || accToProcess.size() >0){
                System.enqueueJob(new LodeStarIntegrationQueueJob(accToProcess,processedAccounts,accountsNotsync));
            }
            else{
                LodeStarIntegrationProcessor.sendmail(processedAccounts,false);
            }
        }
        else if(aJob == null){
          LodeStarIntegrationProcessor.sendmail(processedAccounts,false);
        }
    }
}