src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>ABC</fullName>
        <active>true</active>
        <description>Use to create a new Agent, Broker,  or Consultant Customer</description>
        <label>ABC</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pricing_Due_Date__c</fullName>
        <label>Pricing Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Broker_Fee_Allocation__c</fullName>
        <label>Broker Fee Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/MWh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Broker_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Broker Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Broker_Fee__c</fullName>
        <label>Contract Broker Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Energy_Off_PK__c</fullName>
        <label>Contract Energy Off PK</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Energy_On_PK__c</fullName>
        <label>Contract Energy On PK</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Municipality_Fee__c</fullName>
        <label>Contract Municipality Fee</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Energy_Fixed__c</fullName>
        <label>% Energy Fixed</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Index_Margin_Allocation__c</fullName>
        <label>Index Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/MWh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin__c</fullName>
        <description>Changed from Text to Currency</description>
        <inlineHelpText>This field was previously labeled as &quot;Index Margin.&quot;  It was changed per ticket T-000122.</inlineHelpText>
        <label>Energy Adder Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin_Allocation__c</fullName>
        <label>Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Cost_Allocation__c</fullName>
        <label>Marketing Cost Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Cost__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Marketing Cost</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Municipality_Fee_Allocation__c</fullName>
        <label>Municipality Fee Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Municipality_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Municipality Fee</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>Term in Months</description>
        <label>Term (Whole Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/contracttrigger_testutility.cls
/*****************************************Dynegy*************************************************************************************
 * Name: contracttrigger_testutility                                                                                                     *                                                                                                               *
 * Test Class:contracttrigger_test                                                                                                  *
 * Description:  This test class is used to provide test coverage for Contracttrigger and contracttriggerhandler class                                 *                                            
 * Change History:                                                                                                                  *
 *==================================================================================================================================*
 * Version     Author                       Date             Description                                                            *
 * 1.0         Mounika Duggirala            02/26/2017      Initial Version created                                                 *                            
 ************************************************************************************************************************************/
public class contracttrigger_testutility
{
  public id createaccount()
    { 
    Account Acc=new Account();
    acc.Industry='Government';
        acc.name='test acc';
        acc.Billing_Entity__c='Dynegy';
         insert acc;
        return acc.id;
        
    }
    public id createnecessaryrecords()
    {
       id accid=createaccount();
        
        RecordType rt = [select id,Name from RecordType where SobjectType='opportunity' and Name='standard Opportunity' Limit 1];
        
        Opportunity opp= new Opportunity();
        opp.RecordTypeId=rt.id;
        opp.name='test opp';
        opp.Accountid=accid;
        opp.type='Small Business';
        opp.closedate=system.today();
        opp.stagename='New';
        opp.Service_Territory__c='AEPOHIO';
        
        opp.Pricing_Due_Date__c=system.today();
        insert opp;
        
        
        
        product2 Fp_pro=new product2();
        Fp_pro.name='FP-ONE';
        Fp_pro.IsActive=true;
        insert Fp_pro;
        
        RecordType retail_rt = [select id,Name from RecordType where SobjectType='Retail_Quote__c'  and Name='Executable' Limit 1];
        Retail_Quote__c retail=new Retail_Quote__c(); 
             
       retail.recordtypeid=retail_rt.id;  
       retail.Product__c=Fp_pro.id;
        retail.Payment_Terms__c='14';
        retail.Start_Term__c=system.Today();
        retail.Term__c=12;
        retail.Utility_Settlement_Zone__c='COMED';
        retail.ContractType__c='UCBPOR';
         retail.Margin__c=12;
        retail.Margin_Allocation__c='Lump Sum';
        retail.Energy_Fixed__c=12;
        retail.Index_Margin__c=12;
        retail.Index_Margin_Allocation__c='Lump Sum';
        retail.Broker_Fee__c=0.00;
        retail.Contract_Municipality_Fee__c =0.00;
        retail.Contract_Broker_Fee__c = 0.00;
        retail.Broker_Fee_Allocation__c='Lump Sum';
        retail.Municipality_Fee__c=0.00;
        retail.Municipality_Fee_Allocation__c='Lump Sum';
        retail.Marketing_Cost__c=0.00;
        retail.Marketing_Cost_Allocation__c='Lump Sum';
       string abc = (!string.isblank(retail.Contract_Energy_On_PK__c) && retail.Contract_Energy_On_PK__c !='') ? (retail.Contract_Energy_On_PK__c) : '0' ;
            
            if (abc.startswith('$'))
            abc = abc.removeStart('$');
             string abc1 = (!string.isblank(retail.Contract_Energy_Off_PK__c) && retail.Contract_Energy_Off_PK__c !='') ? (retail.Contract_Energy_Off_PK__c) : '0' ;
            
            if (abc1.startswith('$'))
            abc1 = abc1.removeStart('$');
            
            string abc2 = (!string.isblank(retail.Contract_Energy_Off_PK__c) && retail.Contract_Energy_Off_PK__c !='') ? (retail.Contract_Energy_Off_PK__c) : '0' ;
            
            if (abc2.startswith('$'))
            abc2 = abc2.removeStart('$');
             retail.Contract_Energy_Off_PK__c= '$0.123';
       retail.Contract_Energy_On_PK__c= '$0.456';
        retail.Opportunity__c=opp.id;
        insert retail;
        return retail.id;
    }
}