src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOA_Approval_Mail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DOA_Email2__c</fullName>
        <label>DOA Email2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DOA_Email3__c</fullName>
        <label>DOA Email3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DOA_Email4__c</fullName>
        <label>DOA Email4</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DOA_Email5__c</fullName>
        <label>DOA Email5</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DOA_Email6__c</fullName>
        <label>DOA Email6</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DOA_Email__c</fullName>
        <label>DOA Email</label>
        <type>Email</type>
    </fields>
    <label>DOA Approval Mail</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DOA_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DOA Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOA_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6</booleanFilter>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>christopher.sill@dynegy.com</value>
            </filterItems>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>raymond.culver@dynegy.com</value>
            </filterItems>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>mark.t.fanning@dynegy.com</value>
            </filterItems>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>laura.hrehor2@dynegy.com</value>
            </filterItems>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>sheree.petrone2@dynegy.com</value>
            </filterItems>
            <filterItems>
                <field>User.Email</field>
                <operation>equals</operation>
                <value>robert.c.flexon2@dynegy.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Energy__c</fullName>
        <label>Energy</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notional_Value__c</fullName>
        <label>Notional Value</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Request Status</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waiting on Load Data</fullName>
                </value>
                <value>
                    <fullName>Manual Pricing in Process</fullName>
                </value>
                <value>
                    <fullName>Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Pricing Complete</fullName>
                </value>
                <value>
                    <fullName>Error-Invalid Account</fullName>
                </value>
                <value>
                    <fullName>Error Utility Web-Service Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Error - Price Curve Invalid</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/classes/sendPostApprovalMail_Test.cls
@isTest
private class sendPostApprovalMail_Test{
    static Account acc;
    static Opportunity opp;
    static Supplier__c supplier;
    static testmethod void testMethod1() {
   
        DOA_Approval_Mail__c doaApp = new DOA_Approval_Mail__c();
        doaApp.name = 'Email';
        doaApp.Doa_Email__c = 'test@gmail.com';
        doaApp.Doa_Email2__c = 'test@gmail.com';
        doaApp.Doa_Email3__c = 'test@gmail.com';
        doaApp.Doa_Email4__c = 'test@gmail.com';
        doaApp.Doa_Email5__c = 'test@gmail.com';
        doaApp.Doa_Email6__c = 'test@gmail.com';
        insert doaApp;
        
        profile p = [select id from profile limit 1];
        
        User u = new user();
        u.LastName = 'Test User'+system.now();
        u.Email = 'robert.c.flexon2@dynegy.com';
        u.UserName = 'Test321@test.com.test';
        u.Alias = 'Test';
        u.profileId = p.id;
        u.EmailEncodingKey = 'UTF-8';
        u.TimeZoneSidKey = 'America/New_York';
        u.LocaleSidKey = 'en_US';
        u.LanguageLocaleKey = 'en_US';
        insert u;
        
        RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];
       
        supplier = new Supplier__c();
        supplier.NAme ='Test supplier';
        supplier.Master_DUNS__c  ='1223';
        supplier.Supplier_DUNS__c ='999';
        supplier.Active__c = true;
        insert supplier;
        
        acc = new Account();
        acc.name = 'Test Acc';
        acc.Supplier__c = supplier.Id;
        acc.Billing_Entity__c='Dynegy';
        insert acc;
        
        opp = new Opportunity();
        opp.name = 'Test Opp';
        opp.StageName = 'New';
        opp.CloseDate = date.today().addDays(5);
        opp.Accountid = acc.id;
        opp.RecordTypeId = rec.id;
        opp.DOA_Approved__c = false;
        opp.DOA_Approver__c = u.id;
        insert opp;
        
        Retail_Quote__c rq = new Retail_Quote__c();
        rq.Opportunity__c = opp.id;
        rq.Energy__c = 5.8;   
        rq.Request_Status__c = ConstantUtility.STATUS_PRICING_COMPLETE;
        rq.RecordTypeId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_EXECUTABLE);
        rq.Notional_Value__c = 10000007; 
        rq.Utility_Settlement_Zone__c = 'Test Utility';
        insert rq;
        test.startTest();
        opp.DOA_Approved__c = true;
        update opp;
        Test.stopTest();
  }
}