src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>This field is created during the iAve conversion.</description>
        <label>Service State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>Service State Address State for LDC Account</description>
        <label>Service State</label>
        <length>165</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account__r.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK         </fullName>
                </value>
                <value>
                    <fullName>AL          </fullName>
                </value>
                <value>
                    <fullName>AR         </fullName>
                </value>
                <value>
                    <fullName>AZ          </fullName>
                </value>
                <value>
                    <fullName>CA         </fullName>
                </value>
                <value>
                    <fullName>CO         </fullName>
                </value>
                <value>
                    <fullName>CT          </fullName>
                </value>
                <value>
                    <fullName>DC         </fullName>
                </value>
                <value>
                    <fullName>DE          </fullName>
                </value>
                <value>
                    <fullName>FL           </fullName>
                </value>
                <value>
                    <fullName>GA         </fullName>
                </value>
                <value>
                    <fullName>HI           </fullName>
                </value>
                <value>
                    <fullName>IA           </fullName>
                </value>
                <value>
                    <fullName>ID           </fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN          </fullName>
                </value>
                <value>
                    <fullName>KS          </fullName>
                </value>
                <value>
                    <fullName>KY          </fullName>
                </value>
                <value>
                    <fullName>LA          </fullName>
                </value>
                <value>
                    <fullName>MA        </fullName>
                </value>
                <value>
                    <fullName>MD        </fullName>
                </value>
                <value>
                    <fullName>ME         </fullName>
                </value>
                <value>
                    <fullName>MI          </fullName>
                </value>
                <value>
                    <fullName>MN        </fullName>
                </value>
                <value>
                    <fullName>MO        </fullName>
                </value>
                <value>
                    <fullName>MS         </fullName>
                </value>
                <value>
                    <fullName>MT         </fullName>
                </value>
                <value>
                    <fullName>NC         </fullName>
                </value>
                <value>
                    <fullName>ND         </fullName>
                </value>
                <value>
                    <fullName>NE         </fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <label>Utility Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <defaultValue>&quot;1871754&quot;</defaultValue>
        <description>This is Dynergy number and will not change.</description>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Identifier_Code__c</fullName>
        <label>Organization Identifier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/OLDCBatchTest.cls
/**
 * This class is designed to provide code coverage for the 
 * OLDCBatch class.
 *
 * @
 * @version 1.0
 **/

@isTest
public class OLDCBatchTest{
    
    public static testmethod void OLDCBatchTest(){
        
        Schema.DescribeSObjectResult dsr = Account.SObjectType.getDescribe();
        Map<String,Schema.RecordTypeInfo> acctRecTypeMap = dsr.getRecordTypeInfosByName();
        Schema.RecordTypeInfo ciAcctRecType = acctRecTypeMap.get('C&I Customer');
        //we need to create a test operating company
        Supplier__c testOperatingCompany = new Supplier__c(Name='Test Supplier',Supplier_DUNS__c = 'DUNSTEST',Legacy_ID__c = 'TEST',Master_DUNS__c = 'DUNSTEST',
                                           Organization_Identifier_Code__c = 'TESTSUP',Supplier_Code__c = 'TEST',ESP_Account_Number__c = 'TEST', Active__c = true);
        insert testOperatingCompany;
        
        ID optyRecId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Standard Opportunity').RecordTypeId;
        RecordType rtExec = [select id,name from RecordType where name='Executable' and sobjectType='Retail_Quote__c' limit 1];
  
        Account Cust=new Account(Name='Unit Test',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account',ConstantUtility.CUST_CNI_REC_TYPE),Billing_Entity__c='Dynegy');
        Insert Cust;
        LDC_Vendor__c ldcvendor=new LDC_Vendor__c(Name='Test Vendor2',Service_Territory__c='AEPOHIO',DUNS__c='Test',Utility_Code__c='OP1',Service_State__c = 'OH');
        Insert ldcvendor;
        Opportunity opp =new Opportunity(Name='Test Opp',AccountId=Cust.Id,closeDate=Date.today().addmonths(5),StageName='New');
        Insert opp;
        LDC_Account__c ldcAccnt=new LDC_Account__c(Name='Unit Test LDC',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='32121212',Service_Territory__c=ldcvendor.Service_Territory__c);
        Insert ldcAccnt;
        LDC_Account__c ldcAccnt2=new LDC_Account__c(Name='Unit Test LDC2',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='7',LDC_Account_Number__c='321212123',Service_Territory__c=ldcvendor.Service_Territory__c,Ldc_Account_Status__c='ACTIVE');
        Insert ldcAccnt2;


        Opportunity_LDC__c ldcOpp= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt.Id,Opportunity__c=opp.id);
        Insert ldcOpp;
        Opportunity_LDC__c ldcOpp2= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt2.Id,Opportunity__c=opp.id);
        Insert ldcOpp2;        

        system.schedule('Test OLDC', '0 0 17 * * ?', new OLDCBatchScheduler());

        ldcAccnt.Acct_Annual_Usage__c = 43252.34;
        ldcAccnt2.Acct_Annual_Usage__c = 231.63;
        update new list<ldc_account__c>{ldcAccnt,ldcAccnt2};
        
        OLDCBatch oLDCBatch = new OLDCBatch();
        //testContractLDC2.active__c = false;
        //update testContractLDC2;
        oLDCBatch = new OLDCBatch();
        Database.executeBatch(oLDCBatch, 20);
        
        
        
    }
    
}