src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Business Account for Person Account (Used for MuniAgg, MassMarket etc)</description>
        <inlineHelpText>Related Business Customer for Individual Customer (Used for MuniAgg, MassMarket etc)</inlineHelpText>
        <label>Business Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Mass_Market_Offer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Muni_Agg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>BusinessAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>This field is created during the iAve conversion.</description>
        <label>Service State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DASR Requests</relationshipLabel>
        <relationshipName>DASR_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DASR_Submit_Date__c</fullName>
        <label>DASR Submit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DROP_Transaction_Type__c</fullName>
        <label>DROP Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drop_Date__c</fullName>
        <label>Drop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_GAAD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to Check whether the DASR is most recent one or not</description>
        <label>Most Recent DASR</label>
        <type>Checkbox</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opt_out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>Service State Address State for LDC Account</description>
        <label>Service State</label>
        <length>165</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK         </fullName>
                </value>
                <value>
                    <fullName>AL          </fullName>
                </value>
                <value>
                    <fullName>AR         </fullName>
                </value>
                <value>
                    <fullName>AZ          </fullName>
                </value>
                <value>
                    <fullName>CA         </fullName>
                </value>
                <value>
                    <fullName>CO         </fullName>
                </value>
                <value>
                    <fullName>CT          </fullName>
                </value>
                <value>
                    <fullName>DC         </fullName>
                </value>
                <value>
                    <fullName>DE          </fullName>
                </value>
                <value>
                    <fullName>FL           </fullName>
                </value>
                <value>
                    <fullName>GA         </fullName>
                </value>
                <value>
                    <fullName>HI           </fullName>
                </value>
                <value>
                    <fullName>IA           </fullName>
                </value>
                <value>
                    <fullName>ID           </fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN          </fullName>
                </value>
                <value>
                    <fullName>KS          </fullName>
                </value>
                <value>
                    <fullName>KY          </fullName>
                </value>
                <value>
                    <fullName>LA          </fullName>
                </value>
                <value>
                    <fullName>MA        </fullName>
                </value>
                <value>
                    <fullName>MD        </fullName>
                </value>
                <value>
                    <fullName>ME         </fullName>
                </value>
                <value>
                    <fullName>MI          </fullName>
                </value>
                <value>
                    <fullName>MN        </fullName>
                </value>
                <value>
                    <fullName>MO        </fullName>
                </value>
                <value>
                    <fullName>MS         </fullName>
                </value>
                <value>
                    <fullName>MT         </fullName>
                </value>
                <value>
                    <fullName>NC         </fullName>
                </value>
                <value>
                    <fullName>ND         </fullName>
                </value>
                <value>
                    <fullName>NE         </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LDCAccountTriggerHandler.cls
/* 
 * Name: LDCAccountTriggerHandler
 * Type: Apex Class
 * Test Class: LDC Trigger
 * Description:  This class is a LDC Account Trigger Handler class. 
 * Change History:
 *=====================================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Prasad Paladugu              01/13/2017       1. Initial Version created
 * 2.0         Prasad Paladugu              03/27/2017       1. Updated the flow
 * 3.0         Prasad Paladugu              08/11/2017       1. Control the class invocation using static variables
 * 6.0         Prasad Paladugu              03/01/2018       1. Implemented the Never Served Accounts through trigger
 															 2. Moved related implementation from other class to this class for reusability
 */
 public with sharing class LDCAccountTriggerHandler {
    
    public list<DASR_Request__c> oodasrlst;
    public LDCAccountTriggerHandler(){
        
    }
    
    public void updateLDCIndividualInfo(set<id> ldcset){
        set<id> accset = new set<id>();
        for(ldc_account__c ldc : [select id,account__c,account__r.business_account__c from ldc_account__c where id IN : ldcset]){
            if(ldc.account__r.business_account__c != null)
                accset.add(ldc.account__r.business_account__c);
            else
                accset.add(ldc.account__c);
        }
        if(!accset.isempty()){
            LDCInfo ldc = new LDCinfo(accset);
            Database.executeBatch(ldc,1000);
        }
    }
    
    public void processOptOut(set<id> ldcset){
    	oodasrlst = new list<DASR_Request__c>();
    	string query ='Select LDC_Account__c, DASR_Type__c, Most_Recent_GAAD__c, Contract__c, Integration_Status__C, LDC_Account__r.LDC_Account_Status__c, LDC_Account__r.opt_out__c, LDC_Account__r.LDC_Vendor__r.Service_State__c, change_effective_date__c from DASR_Request__c where LDC_Account__r.opt_out__c = true and LDC_Account__r.LDC_Vendor__r.Service_State__c LIKE \'%IL%\' and change_effective_date__c != null and (Integration_Status__C = \'Complete\' or Integration_Status__C = \'Waiting For Response\') and DASR_Type__c = \'GAAE\' and ldc_account__c IN : ldcset';
    	system.debug('Query : '+query);
    	oodasrlst = database.query(query);
    	string init = 'Trigger';
    	generateGAADDasr(oodasrlst,init);
    }
    
    public void generateGAADDasr(list<dasr_request__c> oodasrlst, string init){
    	Map<string, DASR_Request__c>dasrRecMap = new Map<string, DASR_Request__c>();
        Map<string, LDC_Account__c>ldcAccountMap = new Map<string, LDC_Account__c>();
        set<string> ldcAccountIdSet = new set<string>();
        set<string> checkForAccountStatus = new set<string>();
        Map<string, boolean>boolMap = new Map<string, boolean>();
        set<string>addaccountId = new set<string>();
        List<DASR_Request__c> accountIdForAccountStatus = new List<DASR_Request__c>();
        for(dasr_request__c dasr : oodasrlst){
            ldcAccountIdSet.add(String.valueOf(dasr.get('LDC_Account__c')));
            if(String.valueOf(dasr.get('DASR_Type__c')) == 'GAAE'){
                checkForAccountStatus.add(String.valueOf(dasr.get('LDC_Account__c')));
            }
        }
        List<LDC_Account__c> ldcAccountList = [select id, opt_out__c, LDC_Account_Status__c from LDC_Account__c where id in: ldcAccountIdSet];
        List<DASR_Request__c> DASRtyGAADList = [select id, ldc_Account__c, LDC_Account__r.LDC_Account_Status__c, Drop_Date__c from DASR_Request__c where LDC_Account__c in: ldcAccountIdSet and DASR_Type__c ='GAAD'];
           
        for(LDC_Account__c ldc : ldcAccountList){
            ldcAccountMap.put(ldc.id,ldc);
        }
        
        for(DASR_Request__c dar : DASRtyGAADList){
            boolMap.put(dar.Ldc_Account__c,true);
        }
        
        List<DASR_Request__c> dasrList = new List<DASR_Request__c>();
        DASR_Request__c dasrObj;
        
        for(dasr_request__c dasr : oodasrlst){
            if(!boolMap.containskey(String.valueOf(dasr.get('LDC_Account__c')))){
                if(!addaccountId.contains(String.valueOf(dasr.get('LDC_Account__c')))){
                    if(ldcAccountMap.get(String.valueOf(dasr.get('LDC_Account__c'))).opt_out__c == true && (String.valueOf(dasr.get('Integration_Status__C')) == 'Waiting For Response' || String.valueOf(dasr.get('Integration_Status__C')) == 'Complete') && String.valueOf(dasr.get('DASR_Type__c')) == 'GAAE'){
                        Date dt = date.today();
                        Date dt1 = date.valueOf(dasr.get('change_effective_date__c'));
                        Integer dte = dt.daysBetween(dt1);
                        addaccountId.add(String.valueOf(dasr.get('LDC_Account__c')));
                        if(dte >= 5 && init == 'Trigger'){
                        	dasrObj = new DASR_Request__c();
                        	dasrObj.DROP_Transaction_Type__c = 'EC';
                        }
                        
                        if(dte >= 5 && init == 'Batch'){
                        	dasrObj = new DASR_Request__c();
                            dasrObj.DROP_Transaction_Type__c = 'EC';
                        }
                        else if(dte < 5 && init == 'Batch'){
                        	dasrObj = new DASR_Request__c();
                            dasrObj.DROP_Transaction_Type__c ='DR';
                        }
                        
                        if(dasrobj != null){
                        	dasrObj.DASR_Type__c = 'GAAD'; 
	                        dasrObj.LDC_Account__c = String.valueOf(dasr.get('LDC_Account__c'));
	                        dasrObj.Contract__c = String.valueOf(dasr.get('Contract__c'));
	                        dasrObj.DASR_Submit_Date__c = system.now();
	                        dasrObj.Drop_Date__c= system.today();
	                        dasrObj.billing_Entity__c ='Dynegy';
	                        dasrObj.Dynegy_Initiated__c = true;
                        	dasrList.add(dasrObj);  
	                        system.debug('dasrObj : '+dasrObj);
                        }
                    }
                }
            } 
        }
        if(!dasrList.isempty())database.insert(dasrList);
    }
}

/*********** OLD CODE  LINE 14***********/
        /*ldcset.clear();
        aggregateresult ar = [select count(id) from ldc_account__c where account__c IN : accset or account__r.business_account__c IN : accset];
        system.debug('aggregateresult : '+ar);
        Integer LDCCount = Integer.valueof(ar.get('expr0'));
        if(LDCCount <= 10000){
            for(ldc_account__c ldc : [select id from ldc_account__c where account__c IN : accset or account__r.business_account__c IN : accset]){
                ldcset.add(ldc.id);
            }
            
            if(!ldcset.isempty()){
                LDCInfo ldc = new LDCinfo(ldcset);
                Database.executeBatch(ldc,1000);
            }
        }
        else{*/