src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerPLC__c</fullName>
        <label>Customer PLC</label>
        <precision>17</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLC_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PLC Change</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SetAccountPLCValueBatch.cls
/****
 * This batch will set the CustomerPLC__c value on business customer to '0' for re-calulation
 */
global class SetAccountPLCValueBatch implements Database.Batchable<sObject>{

   String query;
   global SetAccountPLCValueBatch(){}
   global SetAccountPLCValueBatch(String q){
        query = q;
   }
   global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select Id,CustomerPLC__c from account where PLC_Change__c = true');
   }
      
   global void execute(Database.BatchableContext BC, List<sObject> scope){        
        List<Account> lstAcc = new List<Account>();        
        for(Account rec : (List<Account>) scope){           
            lstAcc.add(new Account(Id = rec.Id,CustomerPLC__c = 0));
        }
        update lstAcc;
   }
   
   global void finish(Database.BatchableContext BC){
       Database.executeBatch(new CalcluatePLCBatch(),2000);
   }    
}