src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Business Account for Person Account (Used for MuniAgg, MassMarket etc)</description>
        <inlineHelpText>Related Business Customer for Individual Customer (Used for MuniAgg, MassMarket etc)</inlineHelpText>
        <label>Business Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Mass_Market_Offer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Muni_Agg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>BusinessAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bill_Cycle_Date__c.object
<CustomObject>
    <description>Used for storing meter read date, month and year</description>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to LDC Vendors</description>
        <label>LDC Vendor</label>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>Bill Cycle Date</relationshipLabel>
        <relationshipName>Bill_Cycle_Date</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Bill Cycle Date</label>
    <nameField>
        <displayFormat>BCD-{0000}</displayFormat>
        <label>Bill Cycle Date Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Cycle Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to store the supplier information at contract level</description>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account__r.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <label>Utility Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <formula>Account.Supplier__r.Supplier_DUNS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier DUNS</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESP_Account_Number__c</fullName>
        <defaultValue>&quot;1871754&quot;</defaultValue>
        <description>This is Dynergy number and will not change.</description>
        <label>ESP Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Identifier_Code__c</fullName>
        <label>Organization Identifier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/BatchSetEnrollmentProcessTest.cls
/**
 * @Version 1.1 - Prasad - Modified for code coverage
 **/

@isTest
private class BatchSetEnrollmentProcessTest {
    
    
    static testmethod void test_Enrollment_Muni_Agg() {

        Supplier__c testOperatingCompany = new Supplier__c(Name='Test Supplier',Supplier_DUNS__c = 'DUNSTEST',Legacy_ID__c = 'TEST',Master_DUNS__c = 'DUNSTEST',
                                           Organization_Identifier_Code__c = 'TESTSUP',Supplier_Code__c = 'TEST',ESP_Account_Number__c = 'TEST', Active__c = true);
        insert testOperatingCompany;
        
        Account accnt=new Account(Name='Unit Test Dynegy',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account',ConstantUtility.CUST_MUNI_REC_TYPE),Billing_Entity__c='Dynegy',supplier__c=testOperatingCompany.Id);
        Account accnt1=new Account(Name='Unit Test CES',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account',ConstantUtility.CUST_MUNI_REC_TYPE),Billing_Entity__c='CES',supplier__c=testOperatingCompany.Id);
        insert new List<Account>{accnt,accnt1};
        
        Account pAccnt=new Account(FirstName='Unit',LastName='Test',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt.id,Billing_Entity__c='Dynegy');
        Account pAccntt=new Account(FirstName='Unit',LastName='Test123',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt.id,Billing_Entity__c='Dynegy');
        Account pAccntnull=new Account(FirstName='Unit',LastName='Test123',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt.id,Billing_Entity__c='Dynegy');
        Account pAccnt1=new Account(FirstName='Unit',LastName='Test 1',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt1.id,Billing_Entity__c='CES');
        Account pAccnt2=new Account(FirstName='Unit',LastName='Test 2',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt1.id,Billing_Entity__c='CES');
        Account pAccntIL1=new Account(FirstName='Unit',LastName='Test Il1',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt.id,Billing_Entity__c='Dynegy');
        Account pAccntIl2=new Account(FirstName='Unit',LastName='Test Il2',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account','Muni Agg Individual Customer'),Business_Account__c = accnt.id,Billing_Entity__c='Dynegy');
        insert new List<Account>{pAccnt,pAccntt,pAccnt1,pAccnt2,pAccntIL1,pAccntIL2,pAccntnull};

        LDC_Vendor__c ldcvendor=new LDC_Vendor__c(Name='Test Vendor1',Service_Territory__c='DEOHIO',DUNS__c='Test',Utility_Code__c='DEO',Service_State__c='OH');
        LDC_Vendor__c ldcvendor2=new LDC_Vendor__c(Name='Test Vendor2',Service_Territory__c='ComEd-IL',DUNS__c='Test2',Utility_Code__c='Com',Service_State__c='IL');
        insert new list<LDC_Vendor__c>{ldcvendor,ldcvendor2};

        Contract ct=new Contract(Name='Test Contract Dynegy',StartDate=Date.today().addmonths(-1),Status='Draft',AccountId=accnt.Id,contractTerm=12,Rate_code__c ='GEN21F',supplier__c=testOperatingCompany.Id);
        insert ct;
        
        ct.Status='Activated';
        ct.Contract_Counter_Signed_Date__c = datetime.now();
        ct.Enrollment_Stage__c='Ready to Enroll';
        update ct;
        
        Contract ct1=new Contract(Name='Test Contract CES',StartDate=Date.today().addmonths(-1),Status='Draft',AccountId=accnt1.Id,contractTerm=12,Rate_code__c ='GEN54F',supplier__c=testOperatingCompany.Id);
        insert ct1;
        
        ct1.Status='Activated';
        ct1.Contract_Counter_Signed_Date__c = datetime.now();
        ct1.Enrollment_Stage__c='Ready to Enroll';
        update ct1;

        contract cnt1= [select id,contractnumber from contract where name='Test Contract Dynegy'];
        contract cnt2= [select id,contractnumber from contract where name='Test Contract CES'];
        
        LDC_Account__c ldcAccnt=new LDC_Account__c(Name='Unit Test LDC D',Account__c=pAccnt.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='32126551212',Service_Territory__c='DEOHIO',contract__c = cnt1.ContractNumber);
        LDC_Account__c ldcAccnt2=new LDC_Account__c(Name='Unit Test LDC2 D',Account__c=pAccntt.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='32121212312',Service_Territory__c='DEOHIO',Ldc_Account_Status__c='ACTIVE',contract__c = cnt1.ContractNumber);
        LDC_Account__c ldcAccnt3=new LDC_Account__c(Name='Unit Test LDC3 C',Account__c=pAccnt1.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='3215346312',Service_Territory__c='DEOHIO',Ldc_Account_Status__c='ACTIVE',contract__c = cnt2.ContractNumber);
        LDC_Account__c ldcAccnt4=new LDC_Account__c(Name='Unit Test LDC4 C',Account__c=pAccnt2.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='36458735312',Service_Territory__c='DEOHIO',Ldc_Account_Status__c='NEW_ACCOUNT',contract__c = cnt2.ContractNumber);
        LDC_Account__c ldcAccnt5=new LDC_Account__c(Name='Unit Test LDC3 D',Account__c=pAccntIL1.Id,LDC_Vendor__c=ldcvendor2.Id,Bill_Cycle__c='2',LDC_Account_Number__c='52126551212',Service_Territory__c='ComEd-IL',contract__c = cnt1.ContractNumber);
        LDC_Account__c ldcAccnt6=new LDC_Account__c(Name='Unit Test LDC4 D',Account__c=pAccntIL2.Id,LDC_Vendor__c=ldcvendor2.Id,Bill_Cycle__c='2',LDC_Account_Number__c='62121212312',Service_Territory__c='ComEd-IL',Ldc_Account_Status__c='ACTIVE',contract__c = cnt1.ContractNumber);
        LDC_Account__c ldcAccnt7=new LDC_Account__c(Name='Unit Test LDC D',Account__c=pAccntnull.Id,LDC_Vendor__c=ldcvendor.Id,LDC_Account_Number__c='26435775287',Service_Territory__c='DEOHIO',contract__c = cnt1.ContractNumber);
        insert new List<Ldc_Account__c>{ldcAccnt,ldcAccnt2,ldcAccnt3,ldcAccnt4,ldcAccnt5,ldcAccnt6,ldcAccnt7};
       
        Bill_Cycle_Date__c bcd=new Bill_Cycle_Date__c(Bill_Cycle__c=2,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today(),Meter_Read_Month__c=System.Now().format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().Year()));
        insert bcd;
        Bill_Cycle_Date__c bcd1=new Bill_Cycle_Date__c(Bill_Cycle__c=2,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today().adddays(28),Meter_Read_Month__c=System.Now().addmonths(1).format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().addmonths(1).Year()));
        insert bcd1;
        
        Utility_Business_Rules__c setting = new Utility_Business_Rules__c(Name=ldcvendor.Service_Territory__c,Window_Days__c=16,Days_in_Window__c=-16,Days_Out_Window__c=1, Days_up_to_window__C=-1);
        insert setting;
        Utility_Business_Rules__c setting1 = new Utility_Business_Rules__c(Name=ldcvendor2.Service_Territory__c,Window_Days__c=16,Days_in_Window__c=-16,Days_Out_Window__c=1, Days_up_to_window__C=-1);
        insert setting1;
        Utility_Business_RulesNew__c setting2 = new Utility_Business_RulesNew__c(Name=ldcvendor.Service_Territory__c,Window_Days__c=-16,Days_in_Window__c=7,Days_Out_Window__c=-5);
        insert setting2;
        
        EnrollmentHandler.SetContractToEnroll(cnt1.id);
        EnrollmentHandler.SetContractToEnroll(cnt2.id);
        
        ldcAccnt6.opt_out__c = true;
        update ldcAccnt6;
   }
    
    static testmethod void test_Enrollment_Muni_Agg_2() {

        scheduleBatchEnrollmentProcess sc=new scheduleBatchEnrollmentProcess();
        sc.execute(null);
    }

    static testmethod void test_Enrollment_CNI() {

        Supplier__c testOperatingCompany = new Supplier__c(Name='Test Supplier',Supplier_DUNS__c = 'DUNSTEST',Legacy_ID__c = 'TEST',Master_DUNS__c = 'DUNSTEST',
                                           Organization_Identifier_Code__c = 'TESTSUP',Supplier_Code__c = 'TEST',ESP_Account_Number__c = 'TEST', Active__c = true);
        insert testOperatingCompany;
        
        Account Cust=new Account(Name='Unit Test',RecordTypeId=ConstantUtility.getRecordTypeIdbyName('Account',ConstantUtility.CUST_CNI_REC_TYPE),Billing_Entity__c='Dynegy',supplier__c=testOperatingCompany.Id);
        insert Cust;
        LDC_Vendor__c ldcvendor=new LDC_Vendor__c(Name='Test Vendor2',Service_Territory__c='AEPOHIO',DUNS__c='Test',Utility_Code__c='OP1',Service_State__c='OH');
        insert ldcvendor;
        Opportunity opp =new Opportunity(Name='Test Opp',AccountId=Cust.Id,closeDate=Date.today().addmonths(5),StageName='New');
        insert opp;
        LDC_Account__c ldcAccnt=new LDC_Account__c(Name='Unit Test LDC',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='2',LDC_Account_Number__c='32121212',Service_Territory__c=ldcvendor.Service_Territory__c);
        LDC_Account__c ldcAccnt2=new LDC_Account__c(Name='Unit Test LDC2',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='7',LDC_Account_Number__c='321212123',Service_Territory__c=ldcvendor.Service_Territory__c,Ldc_Account_Status__c='ACTIVE');
        LDC_Account__c ldcAccnt4=new LDC_Account__c(Name='Unit Test LDC2',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='7',LDC_Account_Number__c='421212123',Service_Territory__c=ldcvendor.Service_Territory__c,Ldc_Account_Status__c='ACTIVE',Rate_code__c='DK56');
        insert new list<ldc_account__c>{ldcAccnt,ldcAccnt2,ldcAccnt4};

        Contract ct=new Contract(Name='Test Contract',StartDate=Date.today().addmonths(-1),Status='Draft',AccountId=Cust.Id,Opportunity__c=opp.id,contractTerm=12,supplier__c=testOperatingCompany.Id);

        insert ct;
        ct.Status='Activated';
        ct.Contract_Counter_Signed_Date__c = datetime.now();
        ct.Enrollment_Stage__c='Ready to Enroll';
        update ct;
        Utility_Business_Rules__c setting = new Utility_Business_Rules__c(Name=ldcvendor.Service_Territory__c,Window_Days__c=7,Days_in_Window__c=7,Days_Out_Window__c=-5);
        
        insert setting;
        Utility_Business_RulesNew__c setting1 = new Utility_Business_RulesNew__c(Name=ldcvendor.Service_Territory__c,Window_Days__c=-16,Days_in_Window__c=7,Days_Out_Window__c=-5);
        insert setting1;
        
        Bill_Cycle_Date__c bcd=new Bill_Cycle_Date__c(Bill_Cycle__c=2,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today(),Meter_Read_Month__c=System.Now().format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().Year()));
        insert bcd;
        Bill_Cycle_Date__c bcd2=new Bill_Cycle_Date__c(Bill_Cycle__c=7,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today().adddays(7),Meter_Read_Month__c=System.Now().addmonths(-1).format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().addmonths(-1).Year()));
        insert bcd2;
        Bill_Cycle_Date__c bcd3=new Bill_Cycle_Date__c(Bill_Cycle__c=7,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today().adddays(7),Meter_Read_Month__c=System.Now().format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().Year()));
        insert bcd3;
        Bill_Cycle_Date__c bcd4=new Bill_Cycle_Date__c(Bill_Cycle__c=7,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today().adddays(7),Meter_Read_Month__c=System.Now().addmonths(1).format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().addmonths(1).Year()));
        insert bcd4;
        Bill_Cycle_Date__c bcd5=new Bill_Cycle_Date__c(Bill_Cycle__c=7,LDC_Vendor__c=ldcvendor.Id,Meter_Read_Date__c=Date.today().adddays(7),Meter_Read_Month__c=System.Now().addmonths(2).format('MMM').toUpperCase(),Meter_Read_Year__c=String.valueof(Date.today().addmonths(2).Year()));
        insert bcd5;

        Opportunity_LDC__c ldcOpp= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt.Id,Opportunity__c=opp.id);
        Opportunity_LDC__c ldcOpp2= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt2.Id,Opportunity__c=opp.id);
        Opportunity_LDC__c ldcOpp4= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt4.Id,Opportunity__c=opp.id);
        insert new list<Opportunity_LDC__c>{ldcOpp,ldcOpp2,ldcOpp4};

        EnrollmentHandler.SetContractToEnroll(ct.id);
        EnrollmentHandler.SetContractToEnroll('');
        scheduleBatchEnrollmentProcess sc=new scheduleBatchEnrollmentProcess();
        sc.execute(null);
        
        LDC_Account__c ldcAccnt3=new LDC_Account__c(Name='Unit Test LDC3',Account__c=Cust.Id,LDC_Vendor__c=ldcvendor.Id,Bill_Cycle__c='50',LDC_Account_Number__c='321212124',Service_Territory__c=ldcvendor.Service_Territory__c);
        insert ldcAccnt3;
        Opportunity_LDC__c ldcOpp3= new Opportunity_LDC__c(LDC_Account__c=ldcAccnt3.Id,Opportunity__c=opp.id);
        insert ldcOpp3;
        
        EnrollmentHandler.SetContractToEnroll(ct.id);

        AsyncApexJob apexJob = new AsyncApexJob();
        apexjob = [Select Id,Apexclass.Name, Status, NumberOfErrors, JobItemsProcessed,ExtendedStatus, TotalJobItems, CreatedBy.Email from AsyncApexJob  where NumberOfErrors!= null AND apexclass.name='BatchStartEnrollmentProcess' limit 1];
        if(apexjob != null)BatchUtility.sendAsyncApexJobExceptionEmails(apexJob.id);

    }
    
}