src/objects/Account_Type_Settings__c.object
<CustomObject>
    <description>Object supports Account Type mapping from Contract, Contract Type, Bill Method and Service Territory.</description>
    <fields>
        <fullName>Account_Type_Code__c</fullName>
        <label>Account Type Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RETAIL_STANDALONE</fullName>
                </value>
                <value>
                    <fullName>RETAIL_SUBACCT</fullName>
                </value>
                <value>
                    <fullName>WHOLESALE</fullName>
                </value>
                <value>
                    <fullName>FLOW_THROUGH</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR_RR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_RR</fullName>
                </value>
                <value>
                    <fullName>RETAIL_FRIEND</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR_BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Class__c</fullName>
        <defaultValue>&quot;DEFAULT&quot;</defaultValue>
        <label>Rate Class</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Account Type Settings</label>
    <nameField>
        <displayFormat>ATS-{0000}</displayFormat>
        <label>Account Type Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Type Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a matrix of Account Type selections. This allows Account Types  to be mapped and selected based on Vendor and Bill Method.
Defining Below As Name field Length is limited to 40 
CT1 - Small Stable Contract - Evergreen 
CT2 - Small Stable Contract - MTM Renewal 
CT3 - Large Stable Contract 
CT4 - Large Stable PT-C Contract 
CT5 - Hybrid 
CT6 - Block and Index
CT7 - Non Standard</description>
    <fields>
        <fullName>AccountTypeCode__c</fullName>
        <description>The Account Type Code to use based on the Vendor and the Bill Method.</description>
        <inlineHelpText>The Account Type Code to use based on the Vendor and the Bill Method.</inlineHelpText>
        <label>Account Type Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>The Type of Contract that Maps to the particular bill method and Vendor (or Service Territory)</description>
        <inlineHelpText>The Type of Contract that Maps to the particular bill method and Vendor (or Service Territory)</inlineHelpText>
        <label>Contract Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Type Setting</label>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Account_Type_Code__c</fullName>
        <label>Account Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RETAIL_STANDALONE</fullName>
                </value>
                <value>
                    <fullName>RETAIL_SUBACCT</fullName>
                </value>
                <value>
                    <fullName>WHOLESALE</fullName>
                </value>
                <value>
                    <fullName>FLOW_THROUGH</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR_RR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_RR</fullName>
                </value>
                <value>
                    <fullName>RETAIL_FRIEND</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account_Type_Code__c</fullName>
        <label>Account Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RETAIL_STANDALONE</fullName>
                </value>
                <value>
                    <fullName>RETAIL_SUBACCT</fullName>
                </value>
                <value>
                    <fullName>WHOLESALE</fullName>
                </value>
                <value>
                    <fullName>FLOW_THROUGH</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR_RR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_RR</fullName>
                </value>
                <value>
                    <fullName>RETAIL_FRIEND</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>UCBNONPOR_BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <inlineHelpText>Populated by the Pricing Webscrape.  It matches the LDC Rate Class on the Meter level.  This field is sent to Lodestar the tag field &quot;Rate Code.&quot;</inlineHelpText>
        <label>Utility Rate Class</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/Flow_SetAccountLDCAcctTypeCode.cls
/**
 * This class is designed to host an Invocable Action and can be called from the Process Builder
 * Its purpose is to set the LDC_Account__r.Account_Type_Code__c value based on the Contract.Bill_Type__c,
 * and the LDC_Account__r.LDC_Vendor__r.DUNS__c on the Contract_LDC__c record that has been marked as Active.
 * 
 * @version 1.1 - CJG - 03/21/2016 - Updated the functionality to also update the Rate_Code__c
 *                                   on the Account_LDC from the Contract_LDC
 * @version 1.2 - CJG - 03/31/2016 - Updated the functionality to also update the Contract_Type__c
 *                                   on the related Contract record
 * @version 1.3 - CJG - 04/14/2016 - Updated functionality not to Set Contract Type Any longer.
 * @version 1.4 - CJG - 04/14/2016 - Change to obtaining AccountTypeCode__c - now determined By Contract Type and Service Territory.
 * @version 1.5 - PP  - 10/15/2016 - Added functionality check billmethod also
 * @version 1.5 - PP  - 01/20/2017 - Added functionality to skip billing group if thery are active on it
 * @version 1.5 - PP  - 05/30/2017 - Updated the mapping functionality for MA sites in order to pull multiple from map<String,map<String,Account_Type_Settings__c>> 
 										to map<String,map<String,map<string,list<Account_Type_Settings__c>>>>
 * @version 1.5 - PP  - 10/15/2017 - Updated the mapping functionality for PA Sites to look state values and default checks
 									 Changed custom settings to custom objects to hold values
 * @version 1.5 - PP  - 12/28/2017 - Upgraded the functionality and performance for map
 **/
public class Flow_SetAccountLDCAcctTypeCode {
    @InvocableMethod(label='Set Account LDC' description='Set the Related LDC Account Type Code from the Contract LDC if marked as active.')
    public static void SetAccountLDCInfoFROMContractLDC(List<Id> contractLDCId){
        list<id> cldcId = new list<id>();
        set<string> ldcST = new set<string>();
        list<contract_ldc__c> cldclst = new list<contract_ldc__c>();
        for(Contract_LDC__c cntrct:[SELECT Id, Name, Contract__c, LDC_Account__c,LDC_Account__r.Service_Territory__c,LDC_Account__r.Utility_Rate_Class__c,
                                        Contract__r.Contract_Type__c,Contract__r.Bill_Method__c,ldc_account__r.Account_Type_Code__c FROM Contract_LDC__c 
                                        WHERE Id IN :contractLDCId]){
            if(cntrct.ldc_account__r.Account_Type_Code__c != 'RETAIL_FRIEND'){
                cldcId.add(cntrct.id);
                ldcST.add(cntrct.LDC_Account__r.Service_Territory__c);
            }                                       
        }
        if(!cldcId.isempty()){
            map<Id,String> ldcAccountIdToAccountTypeMap = new map<Id,String>();
            map<String,map<String,map<string,list<Account_Type_Settings__c>>>> settingsMap = ObtainAccountTypeSettingMapByAlternateKey(ldcST);
            for(Contract_LDC__c cntrct:[SELECT Id, Name, Contract__c, LDC_Account__c,LDC_Account__r.Service_Territory__c,LDC_Account__r.Utility_Rate_Class__c,
                                            Contract__r.Contract_Type__c,Contract__r.Bill_Method__c,Account_Type_Code__c FROM Contract_LDC__c WHERE Id IN :cldcId]){
                                                    
                map<String,map<string,list<Account_Type_Settings__c>>> contractTypeMap = settingsMap.get(cntrct.LDC_Account__r.Service_Territory__c);
                if(contractTypeMap != null && cntrct.Contract__r.Contract_Type__c != null){
                    system.debug('contractTypeMap : '+contractTypeMap);
                    map<string,list<Account_Type_Settings__c>> billMethodMap = contractTypeMap.get(cntrct.Contract__r.Contract_Type__c);
                    if(billMethodMap != null){
                        system.debug('billMethodMap : '+billMethodMap);
                        list<Account_Type_Settings__c> atslst = billMethodMap.get(cntrct.Contract__r.Bill_Method__c);
                        Account_Type_Settings__c acctTypeSetting;
                        if(atslst != null){
                            if(atslst.size() > 1){
                                string rateclassStr = '';
                                Account_Type_Settings__c tempats;
                                
                                for(Account_Type_Settings__c ats : atslst){
                                    system.debug('LDC UTILITY RATE CLASS : '+cntrct.LDC_Account__r.Utility_Rate_Class__c);
                                    if(cntrct.LDC_Account__r.Utility_Rate_Class__c != null){
                                        if(ats.rate_class__c != 'DEFAULT'){
                                            rateclassStr= ats.rate_class__c;
                                        } 
                                        else if(ats.rate_class__c == 'DEFAULT')
                                            tempats=ats;
                                        
                                        if(rateclassStr.contains(cntrct.LDC_Account__r.Utility_Rate_Class__c))
                                            acctTypeSetting = ats;
                                    }
                                    else{
                                        if(ats.rate_class__c == 'DEFAULT')
                                            tempats = ats;
                                    }
                                }
                                if(acctTypeSetting == null)
                                    acctTypeSetting = tempats;
                            }
                            else
                                acctTypeSetting = atslst[0];
                        }
                        else{
                            atslst = billMethodMap.get(null);
                            if(atslst != null)
                                acctTypeSetting = atslst[0];
                        }
                        /***************** COMMENTED FOR T-001944   ********************************/
                        /*if(billMethodMap.size() > 1){
                            for(AccountTypeSetting__c ats : billMethodMap.values()){
                                system.debug('test inner : '+ats.Bill_Method__c +' : '+cntrct.Contract__r.Bill_Method__c);
                                if(ats.Bill_Method__c.equalsIgnorecase(cntrct.Contract__r.Bill_Method__c) && ats.Bill_Method__c != null)
                                     atslst = billMethodMap.get(ats.Bill_Method__c);
                                    // acctTypeSetting = billMethodMap.get(ats.Bill_Method__c);
                            }
                        }
                        else{
                            atslst = billMethodMap.get(cntrct.Contract__r.Bill_Method__c);
                            //AccountTypeSetting__c ats1 = billMethodMap.get(cntrct.Contract__r.Bill_Method__c);
                            system.debug('test ats1 : '+ats1);
                            if(ats1 != null && ats1.Contract_Type__c.equalsIgnorecase(cntrct.Contract__r.Contract_Type__c))
                                acctTypeSetting = ats1;
                            else
                                acctTypeSetting = billMethodMap.get(null);
                        }*/
                        if(acctTypeSetting != null) ldcAccountIdToAccountTypeMap.put(cntrct.LDC_Account__c,acctTypeSetting.Account_Type_Code__c);
                    }
                    else{
                        if(billMethodMap == null && billMethodMap.size()>0){
                            list<Account_Type_Settings__c> atslst = billMethodMap.get(null);
                            Account_Type_Settings__c acctTypeSetting;
                            if(atslst.size()>1){
                                
                            }
                            else if(!atslst.isempty()){
                                acctTypeSetting = atslst[0];
                            }
                        }
                    }
                }
                if(ldcAccountIdToAccountTypeMap.get(cntrct.LDC_Account__c) != null){
                    cntrct.Account_Type_Code__c = ldcAccountIdToAccountTypeMap.get(cntrct.LDC_Account__c);
                    cldclst.add(cntrct);
                }
            }
            List<LDC_Account__c> ldcsToUpdate = new List<LDC_Account__c>();
            for(LDC_Account__c ldcAcct:[SELECT Id, Account_Type_Code__c FROM LDC_Account__c WHERE Id IN :ldcAccountIdToAccountTypeMap.keySet()]){
                ldcAcct.Account_Type_Code__c = ldcAccountIdToAccountTypeMap.get(ldcAcct.Id);
                ldcsToUpdate.add(ldcAcct);
            }
            if(!ldcsToUpdate.isEmpty()) update ldcsToUpdate;
            if(!cldclst.isEmpty()) update cldclst;
        }
    }
    /**
     * Simply returns the AccounTypeSetting__c records in a Map of Maps with the first key being
     * ServiceTerritory__c and the Second Key being the Contract_Type__c.
     *
     * @return Map<String,Map<String,AccountTypeSetting__c>>  - the Map to return
     **/
    public static map<String,map<String,map<string,list<Account_Type_Settings__c>>>> ObtainAccountTypeSettingMapByAlternateKey(set<string> sTerritory){
        Map<String,Account_Type_Settings__c> settingMap = new Map<String,Account_Type_Settings__c>(); //AccountTypeSetting__c.getAll();
        for(Account_Type_Settings__c ats : [select id,name,Account_Type_Code__c,Bill_Method__c,Contract_Code__c,Contract_Type__c,Rate_Class__c,Service_Territory__c,
                                            State__c,key__c from Account_Type_Settings__c where Service_Territory__c IN : sTerritory order by Service_Territory__c,Contract_Type__c]){
            settingMap.put(ats.Name,ats);
        }
        
        map<String,map<String,map<string,list<Account_Type_Settings__c>>>> returnMap = new map<String,map<String,map<string,list<Account_Type_Settings__c>>>>();
        for(Account_Type_Settings__c setting:settingMap.values()){
            
            map<String,map<string,list<Account_Type_Settings__c>>> tempMap = new map<String,map<string,list<Account_Type_Settings__c>>>();
            map<string,list<Account_Type_Settings__c>> tempMap2 = new map<String,list<Account_Type_Settings__c>>();
            list<Account_Type_Settings__c> atslst = new list<Account_Type_Settings__c>();
            
            if(returnMap.containsKey(setting.Service_Territory__c)){
                tempMap = returnMap.get(setting.Service_Territory__c);
                system.debug('tempMap : '+tempmap.size()+' : '+tempmap.keyset());
                for(string st : tempMap.keyset()){
                    if(tempMap.containsKey(setting.Contract_Type__c)){
                        tempMap2 = tempMap.get(setting.Contract_Type__c);
                        for(string str : tempMap2.keyset()){
                        	if(tempMap2.containskey(setting.Bill_Method__c)){
	                            atslst = tempmap2.get(setting.Bill_Method__c);
	                        }
                        }
                    }
                }
            }
            atslst.add(setting);
            tempMap2.put(setting.Bill_Method__c,atslst);
            tempMap.put(setting.Contract_Type__c,tempMap2);
            returnMap.put(setting.Service_Territory__c,tempMap);
        }
        return returnMap;
    }
}