src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Business Account for Person Account (Used for MuniAgg, MassMarket etc)</description>
        <inlineHelpText>Related Business Customer for Individual Customer (Used for MuniAgg, MassMarket etc)</inlineHelpText>
        <label>Business Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Mass_Market_Offer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Muni_Agg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>BusinessAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Flow_ReparentAccountfromContractLDC.cls
/**
 * This class is designed to host an Invocable Method that can be called 
 * from the Process Builder. Its purpose is to reparent the LDC_Account__r.Account__c
 * from the Contract_LDC__c record based on the Contract__r.Account that it is connected to.
 * 
 * @author Chris Gary <cgary@cloudperformer.com>
 * @version 1.0
 * @version 1.1 Updated the functionality to meet business requirements -Prasad
 * @version 1.0 Updated the functionality to work on change effective date instead of immediate effect -Prasad
 **/
public class Flow_ReparentAccountfromContractLDC {
    @InvocableMethod(label='Reparent Individual Accounts' description='Reparent Person Accounts to the correct offer or MuniAgg Account')
    public static void ReparentAccount(List<Id> contractLDCId){
        //put the List into a Set
        Set<Id> contractLDCIdSet = new Set<Id>();
        contractLDCIdSet.addAll(contractLDCId);
        //get the data needed as well as the Accounts to update
        List<Contract_LDC__c> contractLDCList = [SELECT 
                                                    Id, Contract__c, Contract__r.AccountId,
                                                    LDC_Account__c, LDC_Account__r.Account__c,
                                                    LDC_Account__r.Account__r.Business_Account__c
                                                FROM Contract_LDC__c 
                                                WHERE Id IN :contractLDCIdSet];
        Set<Id> accountIdSet = new Set<Id>();
        for(Contract_LDC__c contractLDC:contractLDCList){
            //get the AccountIds in a Map to possibly update
            if(contractLDC.LDC_Account__r.Account__c != null) accountIdSet.add(contractLDC.LDC_Account__r.Account__c);
        }
        //now get the possible accounts for Update
        Map<Id,Account> accountList = new Map<Id,Account>([SELECT
                                                            Id, Business_Account__c
                                                          FROM Account
                                                          WHERE Id IN :accountIdSet]);
        //go through each of the Contract_LDC__c records, and if the 
        //LDC_Account__r.Account__r.Business_Account__c is not empty and 
        //does not match the Contract__r.AccountId - update accordingly.
        List<Account> accountListToUpdate = new List<Account>();
        for(Contract_LDC__c contractLDC:contractLDCList){ 
            if(contractLDC.LDC_Account__r.Account__r.Business_Account__c != null &&
               contractLDC.LDC_Account__r.Account__r.Business_Account__c != contractLDC.Contract__r.AccountId){
               Account acct = accountList.get(contractLDC.LDC_Account__r.Account__c);
               system.debug('Account : '+acct);
               if(acct != null){ 
                    acct.Business_Account__c = contractLDC.Contract__r.AccountId;
                    Integer count= 0;
                    Integer accountlistsize=accountListToUpdate.size();
                    
                        if(accountListToUpdate.size()==0){
                            count=0;
                        }
                        else{
                            for(Integer i=0; i<accountlistsize ;i++){
                                if(accountListToUpdate[i].id != acct.id) {
                                    count++;
                                }
                            }
                        }
                        system.debug('Count : '+count);
                        if(accountListToUpdate.size() == count){
                            accountListToUpdate.add(acct);
                            system.debug('Adding account');
                        }
               }
            }
        }
        if(!accountListToUpdate.isEmpty()) update accountListToUpdate;
    }
}