src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ALL_IN_Price__c</fullName>
        <label>Total All-In Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>Rate Ready</fullName>
                </value>
                <value>
                    <fullName>Bill Ready</fullName>
                </value>
                <value>
                    <fullName>SBO/ESP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Counter_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Index_Adder_Total_Per_KWH__c</fullName>
        <label>Total Energy Adder</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Index_Name__c</fullName>
        <label>Quote Index Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Broker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Quote</label>
        <referenceTo>Retail_Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to store the supplier information at contract level</description>
        <inlineHelpText>The legal retail entity selling to this customer (Dynegy Energy Services East, LLC)</inlineHelpText>
        <label>Operating Company</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Priced_MWH__c</fullName>
        <label>Total Priced MWHrs</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Type_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a matrix of Contract Type selections based on Service Territory and Bill Method
Defining Below As Name field Length is limited to 40
CT1 - Small Stable Contract - Evergreen
CT2 - Small Stable Contract - MTM Renewal
CT3 - Large Stable Contract
CT4 - Large Stable PT-C Contract
CT5 - Hybrid
CT6 - Block and Index</description>
    <fields>
        <fullName>Bill_Method__c</fullName>
        <label>Bill Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contract Type Setting</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Referral_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ABC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Amendment</fullName>
        <active>true</active>
        <businessProcess>Dynegy</businessProcess>
        <description>Used to create an Amendment Opportunity</description>
        <label>Amendment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>ALL_IN_Price__c</fullName>
        <label>Total All-In Price Per MWH</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Index_Adder_Total_Per_KWH__c</fullName>
        <label>Total Energy Adder Per KWH</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Index_Name__c</fullName>
        <label>Quote Index Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Price_KWH__c</fullName>
        <label>Quote Price KWH</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Request Status</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waiting on Load Data</fullName>
                </value>
                <value>
                    <fullName>Manual Pricing in Process</fullName>
                </value>
                <value>
                    <fullName>Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Pricing Complete</fullName>
                </value>
                <value>
                    <fullName>Error-Invalid Account</fullName>
                </value>
                <value>
                    <fullName>Error Utility Web-Service Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Error - Price Curve Invalid</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Priced_KWH__c</fullName>
        <label>Total All-in- Price Per KWH</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Priced_MWH__c</fullName>
        <label>Total Priced MWHrs</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/CreateContractFromQuoteController.cls
/* 
 * Name: CreateContractFromQuoteController
 * Type: Apex Class
 * Test Class: CreateContractFromQuoteControllerTest
 * Description:  This class is used to create Contract from Executable Quotes. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         02/10/2016       1. Initial Version created
 * 2.0		   Prasad Paladugu 				03/17/2017		 1. Mapped new fields for quotes
 */
global with sharing class CreateContractFromQuoteController {
    public Retail_Quote__c recQuote {get; set;}
    public Contract quoteContract {get; set;}
    public final string USER_CONFIRMATION_MESSAGE = 'Please Validate the Following Fields from Signed Contract:'; 
    public final string NO_CODE_FOUND = 'No Code Found';
    public final string ERR_SELECT_VALID_RATE_CODE = 'Please select a valid rate code for contract creation.';
    public final string ERR_CONTRACTNAME_MISSING = 'Contract Name is required.'; 
    //public final string ERR_CONTRACTTYPE_MISSING = 'Contract Type is mandatory for contract creation.';
    public final string ERR_CONTRACTTYPE_MISSING = 'No Contract Type found for the Service Territory and Bill Method selected.';
    public final string ERR_BILLMETHOD_MISSING = 'Bill Method is required.';
    public final string ERR_COUNTERSIGNEDDATE_MISSING = 'Contract Counter Signed Date is required.';
    public string rateCode {get; set;}
    public string contractName {get; set;}
    public string strQuery;   
    
    public CreateContractFromQuoteController(ApexPages.StandardController stdController){
        rateCode = NO_CODE_FOUND;
        strQuery = 'Select ';
        contractName = '';
        quoteContract = new Contract();
        if(stdController.getRecord() != null){
            String recId = ((Retail_Quote__c)stdController.getRecord()).id;
            for(String rtFld : schema.SObjectType.Retail_Quote__c.fields.getMap().keySet()){
                strQuery += rtFld + ',';
            }
            strQuery += 'Product__r.Name,Opportunity__r.Service_Territory__c,Opportunity__r.Account.Name,Opportunity__r.Account.BillingAddress,Opportunity__r.Account.BillingStreet,Opportunity__r.Account.BillingCity,Opportunity__r.Account.Supplier__c,'+
                        'Opportunity__r.Account.BillingState,Opportunity__r.Account.BillingCountry,Opportunity__r.Account.BillingPostalCode,Opportunity__r.Account.id,Opportunity__r.RecordTypeId,Opportunity__r.Contract.Id,'+
                        'Opportunity__r.Referral_Broker__c FROM Retail_Quote__c WHERE ID = :recId LIMIT 1';
            
            recQuote = Database.query(strQuery);
            recQuote.Request_Status__c = 'Contract Signed';            
            if(recQuote != null && recQuote.Quote_Price_KWH__c != null && recQuote.Opportunity__r.Service_Territory__c != null){
                list<Rate_Code__c> lstRC = [select Id, Name from Rate_Code__c Where Price__c = :recQuote.Quote_Price_KWH__c AND Service_Territory__c = :recQuote.Opportunity__r.Service_Territory__c];
                if(!lstRC.isEmpty()){
                    rateCode = lstRC[0].Name;
                }
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,USER_CONFIRMATION_MESSAGE));
            
        }
    }
    
    public PageReference finishRequest(){
        /*
        if(rateCode == null || rateCode == '' || rateCode == NO_CODE_FOUND){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ERR_SELECT_VALID_RATE_CODE));
            return null;
        }
        */
        Boolean hasErrorMessage = false;
        if(rateCode == null || rateCode == NO_CODE_FOUND){
            rateCode = '';
        }
        if(contractName == null || contractName == ''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ERR_CONTRACTNAME_MISSING));
            hasErrorMessage = true;
        }
        /* Commented below code for SCR-1341- Nanda
        Contract_Type_Setting__c cts = Contract_Type_Setting__c.getValues(recQuote.Opportunity__r.Service_Territory__c+'-'+quoteContract.Bill_Method__c);
        if(cts!=null)
            quoteContract.Contract_Type__c = cts.Contract_Type__c;
        if(quoteContract.Contract_Type__c == null || quoteContract.Contract_Type__c == ''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ERR_CONTRACTTYPE_MISSING));
            hasErrorMessage = true;
        }*/
        if(quoteContract.Bill_Method__c == null || quoteContract.Bill_Method__c == ''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ERR_BILLMETHOD_MISSING));
            hasErrorMessage = true;
        }  
        if(quoteContract.Contract_Counter_Signed_Date__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ERR_COUNTERSIGNEDDATE_MISSING));
            hasErrorMessage = true;
        }
        if(hasErrorMessage){             
             return null;
        }
        
        ID OptyAmendRecTypeId;
        try{
          OptyAmendRecTypeId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Amendment').RecordTypeId;
        }
        catch(Exception ex){
          OptyAmendRecTypeId = null;
        }      
        
        //Contract quoteContract;        
        if(recQuote != null && recQuote.Opportunity__r.Account.id != null){
            Map<String, Schema.SObjectField> mapRetQtDescribe = schema.SObjectType.Retail_Quote__c.fields.getMap();
            Map<String, Schema.SObjectField> mapContractDescribe = schema.SObjectType.Contract.fields.getMap();
            //quoteContract = new Contract(Name = contractName);
            //Dynamically populate the contarct fields which are have matching fields in Quote
            for(String retQtField : mapRetQtDescribe.KeySet()){
                Schema.DescribeFieldResult describersult = mapRetQtDescribe.get(retQtField).getDescribe();
                if(!describersult.isCustom() || !describersult.isCreateable() || describersult.isCalculated()){
                    continue;
                }
                else if(mapContractDescribe.containsKey(retQtField))
                {
                    system.debug('Test : '+retQtField+' : '+recQuote.get(retQtField));
                    quoteContract.put(retQtField, recQuote.get(retQtField));
                }
            }
            //Set additional fields which can not be set via fieldmap
            quoteContract.Name = contractName;
            
            //Added for the new fields which salesforce receive from pricing SCR-1287
            //quoteContract.Quote_Index_Adder_Total_Per_KWH__c = recQuote.Quote_Index_Adder_Total_Per_KWH__c;
            quoteContract.ALL_IN_Price__c= recQuote.Total_Priced_KWH__c;
            quoteContract.Total_Priced_MWH__c= recQuote.Total_Priced_MWH__c;
            quoteContract.Quote_Index_Name__c= recQuote.Quote_Index_Name__c;
            quoteContract.Contract_Type__c = recQuote.ContractType__c ;
            
            quoteContract.StartDate = recQuote.Start_Term__c;
            quoteContract.ContractTerm = recQuote.Term__c.intValue();
            quoteContract.Product_Name__c = recQuote.Product__r.Name;
            quoteContract.Retail_Quote__c=recQuote.id;
            quoteContract.Rate_Code__c = rateCode;
            quoteContract.Service_Territory__c=recQuote.Opportunity__r.Service_Territory__c;
            quoteContract.AccountId=recQuote.Opportunity__r.Account.id;
            quoteContract.BillingStreet=recQuote.Opportunity__r.Account.BillingStreet;
            quoteContract.BillingCity=recQuote.Opportunity__r.Account.BillingCity;
            quoteContract.BillingState=recQuote.Opportunity__r.Account.BillingState;
            quoteContract.BillingCountry=recQuote.Opportunity__r.Account.BillingCountry;
            quoteContract.BillingPostalCode=recQuote.Opportunity__r.Account.BillingPostalCode;
            quoteContract.Contract_Broker_Fee__c = recQuote.Contract_Broker_Fee__c;
            quoteContract.Contract_Index_Margin__c = recQuote.Contract_Index_Margin__c;
            quoteContract.Contract_Margin__c = recQuote.Contract_Margin__c;
            quoteContract.Contract_Marketing_Cost__c = recQuote.Contract_Marketing_Cost__c;
            quoteContract.Contract_Municipality_Fee__c = recQuote.Contract_Municipality_Fee__c;
            quoteContract.Referral_Broker__c = recQuote.Opportunity__r.Referral_Broker__c;
            quoteContract.Supplier__c = recQuote.Opportunity__r.Account.Supplier__C;
            quoteContract.LodeStar_Identifier__c=DynegyCommonUtils.generateRandomString(20);
            
            if(OptyAmendRecTypeId != null && OptyAmendRecTypeId.equals(recQuote.Opportunity__r.RecordTypeId) 
                && recQuote.Opportunity__r.Contract.Id != null){
                quoteContract.Parent_Contract__c = recQuote.Opportunity__r.Contract.Id;
            }
            try{
                update recQuote;
                insert quoteContract;
            }
            catch(Exception Ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error creating Quote:'+ex.getMessage()));
                return null;
            }
        }
        if(quoteContract != null){
            return getObjectView(quoteContract);
        }
           
        return getObjectView(recQuote);
               
    }
    
    public PageReference exitRequest(){
        return getObjectView(recQuote);       
    }
    
    public PageReference getObjectView(sObject sobj){
        return (new ApexPages.StandardController(sobj)).view();
    }
    
    public PageReference cancelCode(){
        return Page.CreateContractFromQuote;       
    }
    
    public PageReference submitCode(){
        return Page.CreateContractFromQuote;       
    }
    
    public PageReference findRateCode(){
        return Page.SelectRateCodeForContract;
    }
    
    webservice static String contractExists(Id oppId){
    
        if(oppId == null){
            return 'NA';
        }
        
        List<Contract> lstCon = [select Id from Contract where Opportunity__c = :oppId];
        
        if(!lstCon.isEmpty()){
            return 'YES';
        }
        
        return 'NO';
    }
    webservice static String contractExistsOnQuote(Id quoteId){
        if(quoteId == null){
            return 'NA';
        }
        
        List<Contract> lstConQuote = [select Id from Contract where Retail_Quote__c = :quoteId];
        
        if(!lstConQuote.isEmpty()){
            return 'YES';
        }
        
        return 'NO';
    }
}