src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Entity__c</fullName>
        <label>Billing Entity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Billing_Entity</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>Utility vendor DUNS</description>
        <label>DUNS</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <label>Utility Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Refresh_Expiration_Date__c</fullName>
        <description>Refresh Expiration Date</description>
        <label>Refresh Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Energy__c</fullName>
        <label>Energy</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Indicative</fullName>
        <active>true</active>
        <label>Indicative</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Billing_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dynegy</fullName>
    </customValue>
    <customValue>
        <fullName>CES</fullName>
    </customValue>
    <masterLabel>Billing Entity</masterLabel>
</GlobalValueSet>

src/classes/PricingWSHelperTest.cls
/* 
 * Name: PricingWSHelperTest
 * Type: Test Class
 * Apex Class: PricingWSHelper
 * Description:  This is test class for code coverage of PricingWSHelper. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0        Sneha Gadde        03/14/2016       1. Initial Version created
 */


@isTest(SeeAllData=false)
public class PricingWSHelperTest {

  private static testmethod void PricingWSHelper_UnitTest()
  {
    Test.startTest();  
      RecordType rec =[select id,name from RecordType where name = 'Standard Opportunity'];

       Account acc = new Account();
       acc.name = 'Test Acc';
       acc.Billing_Entity__c='Dynegy';
       insert acc;
       
       Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       opp.Accountid = acc.id;
       opp.RecordTypeId = rec.id;
       insert opp;
       
       Retail_Quote__c rq = new Retail_Quote__c();
       rq.Opportunity__c = opp.id;
       rq.Energy__c = 5.8;   
       rq.RecordTypeId = ConstantUtility.getRecordTypeIdbyName('Retail_Quote__c','Indicative');
       rq.Utility_Settlement_Zone__c = 'Test Utility';
       insert rq;
       
       LDC_Account__c lacc = new LDC_Account__c();
       lacc.name  ='Test LDC acc';
       lacc.Account__c = acc.id;
       lacc.LDC_Account_Number__c = '123456';
       insert lacc;
      Opportunity_LDC__c oppLdc = new Opportunity_LDC__c();
     // oppLdc.name = 'Test LDC Acc';
      oppLdc.LDC_Account__c = lacc.id;   
      oppLdc.Opportunity__c = opp.id;
      insert oppLdc;
      List<Retail_Quote__c> rqLst = new List<Retail_Quote__c>();
      rqLst.add(rq);
      Opportunity opp1 = [select Id,Name,Refresh_Expiration_Date__c,AccountId,recordType.name,(Select Id, Name, LDC_Account__r.name,LDC_Account__r.LDC_Account_Number__c,LDC_Account__r.LDC_Vendor__r.DUNS__c,LDC_Account__r.LDC_Vendor__r.Utility_Code__c from OpportunityLDCs__r) from Opportunity where id=:opp.id];
      PricingWSHelper.sendQuotesForPricing(rqLst,opp1,acc);
      //PricingWSHelper.onPricingFailure('None');
      PricingWSHelper.sendQuotesForPricingFuture(PricingWSHelper.getQuotesforPricing(rqLst,opp1,acc));
      PricingWSHelper.onPricingFailure(PricingWSHelper.getQuotesforPricing(rqLst,opp1,acc));
    Test.stopTest();  
  }
    
}