src/objects/Account_Exception__c.object
<CustomObject>
    <description>This Object is created to store the account exceptions</description>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <formula>DASR_Request__r.Change_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DASR_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DASR Request</label>
        <referenceTo>DASR_Request__c</referenceTo>
        <relationshipLabel>Account_Exceptions</relationshipLabel>
        <relationshipName>Account_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Account_Exceptions</relationshipLabel>
        <relationshipName>Account_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is created to check whether the Account Exception is most recent or not DTM151</description>
        <label>Most Recent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <label>Reason_Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account_Exception</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Account_Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account_Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Group__c.object
<CustomObject>
    <description>Object supports the ability to group accounts for billing by contract.</description>
    <fields>
        <fullName>contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Select Contract Related to Business Customer by Name &amp; ContractNumber only</errorMessage>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Searches only Related Contracts by Name &amp; ContractNumber only</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Billing Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Group_Ldc__c.object
<CustomObject>
    <description>Object supports the relationship between LDC Accounts and Billing Group.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Billing Group Ldc</relationshipLabel>
        <relationshipName>Billing_Group_Ldc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Billing Group Ldc</relationshipLabel>
        <relationshipName>Billing_Group_Ldc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Billing Group Ldc</label>
    <nameField>
        <displayFormat>BGLDC-{0000000}</displayFormat>
        <label>Billing Group Ldc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Group Ldcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DASR Requests</relationshipLabel>
        <relationshipName>DASR_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DASR_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DASR Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dynegy_Initiated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Dynegy Initiated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_GAAD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to Check whether the DASR is most recent one or not</description>
        <label>Most Recent DASR</label>
        <type>Checkbox</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/FlagContractLDC.cls
/**********************************************************
Class :  FlagContractLDC
Test Class : DASRGAAEBatch_Test.DASRGAAEBatch_Activate,DASRGAACBatchTest.DASRGAACBatch_Activate
Version     Date            Author
1.0         11/29/2017      Prasad Paladugu 
***********************************************************/
global class FlagContractLDC implements system.schedulable,database.Batchable<sObject>,database.Stateful{
    
    public FlagContractLDC(){
    }
    
    global set<id> aeIDSet;
    global list<Account_Exception__c> aelst;
    
    global void execute(schedulableContext sc){
        system.debug('Schedule Run Start >>>>>>>>');
        FlagContractLDC fcldc = new FlagContractLDC();
        database.executebatch(fcldc,100);
    }
    
    global database.QueryLocator Start (database.BatchableContext bc){
        
        aeIDSet = new set<id>();
        aelst = new list<Account_Exception__c>();
        for(Account_Exception__c ae : [select id,name,change_effective_date__c,dasr_request__c from Account_Exception__c where Reason_Code__c='DTM150' and Most_Recent__c = true]){
            aeIDSet.add(ae.dasr_request__c);
            aelst.add(ae);
        }
        
        string q='select id, dasr_type__c, dynegy_initiated__c,ldc_account__c,contract__c, LDC_Account__r.LDC_Account_Status__c From DASR_Request__c  where'+ 
                 '((Dynegy_Initiated__c = true AND Change_Effective_Date__c != null AND dasr_activated__c = false AND Most_recent_gaad__c = false AND ((Accepted__c = true AND '+
                 'Integration_Status__c = \'Complete\' and Dasr_type__c = \'GAAE\' and lastmodifieddate >= '+label.dasr_gaae+') OR (Dasr_type__c = \'GAAC\' and '+
                 'lastmodifieddate >= '+label.dasr_gaae+' and (Integration_Status__c = \'Complete\' OR (Integration_Status__c = \'Manually Fulfilled\' '+
                 'and ldc_account__r.service_territory__c = \'ComEd-IL\'))))) OR (ID IN: aeIDSet)) AND Change_Effective_Date__c <= Today order by Change_Effective_Date__c';
        return database.getQueryLocator(q);     
    }
    
    global void execute(database.BatchableContext bc,list<dasr_request__c> scope){
        
        list<dasr_request__c> dasrlst = (list<dasr_request__c>)scope;
        set<string> dasrESet = new set<string>();
        set<string> dasrCSet = new set<string>();
        list<contract_ldc__c> cldclst = new list<contract_ldc__c>();
        list<dasr_request__c> dasrUPlst = new list<dasr_request__c>();
        list<id> cldcEId = new list<id>();
        list<id> cldcCId = new list<id>();
        set<id> ldcset = new set<id>();
        set<id> cntset = new set<id>();
        set<id> ldcActSet = new set<id>();
        set<id> cldcActSet = new set<id>();
        
        for(dasr_request__c dasr : dasrlst){
            ldcset.add(dasr.ldc_account__c);
            if(dasr.contract__c != null)
                cntset.add(dasr.contract__c);
            
            if(dasr.dasr_type__c == 'GAAE')
                dasrESet.add(dasr.ldc_account__c+''+dasr.contract__c);
            else if(dasr.dasr_type__c == 'GAAC')
                dasrCSet.add(dasr.ldc_account__c+''+dasr.contract__c);
            
            dasr.dasr_activated__c = true;
            dasrUPlst.add(dasr);
        }
        
        for(contract_ldc__c cldc : [select id,Name,ldc_account__c,contract__c from contract_ldc__c where ldc_account__c IN : ldcset and contract__c IN : cntset order by createddate]){
            cldc.active__c = true;
            if(dasrESet.contains(cldc.ldc_account__c+''+cldc.contract__c))
                cldcEId.add(cldc.id);
            else if(dasrCSet.contains(cldc.ldc_account__c+''+cldc.contract__c)){
                cldcCId.add(cldc.id);
                ldcActSet.add(cldc.ldc_account__c);
                cldcActSet.add(cldc.id);
            }
            cldclst.add(cldc);
        }
        
        system.debug('LDC SET : '+ldcActSet);
        system.debug('CLDC SET : '+cldcCId);
        
        list<Billing_Group_Ldc__c> bgldclst = new list<Billing_Group_Ldc__c>();
        for(Billing_Group_Ldc__c bgldc : [select id,active__c from Billing_Group_Ldc__c where ldc_account__c IN : ldcset and Billing_Group__r.contract__c IN : cntset]){
            bgldc.active__c = true;
            bgldclst.add(bgldc);
        }
        
        cntset.clear();
        
        //for only GAAC dasrs specifically as they move from one to other contract and reenrollment is not considered as there might be gap in service
        //Flow_DeactivateNonApplicableContracts.DeactivateNonActiveContractLDCRecs(cldcCId);
        for(contract_ldc__c cldc : [select id,ldc_account__c,contract__c,active__c from contract_ldc__c where ldc_account__c IN : ldcActSet and active__c = true AND Id NOT IN : cldcCId]){
            system.debug(' Current Contract LDC : '+cldc);
            if(cldc.Active__c = true  && !cldcActset.contains(cldc.id)){
                cldc.active__c = false;
                cldclst.add(cldc);
                cntset.add(cldc.contract__c);
            }
        }
        
        for(Billing_Group_Ldc__c bgldc : [select id,active__c from Billing_Group_Ldc__c where ldc_account__c IN : ldcset and Billing_Group__r.contract__c IN : cntset]){
            bgldc.active__c = false;
            bgldclst.add(bgldc);
        }
        
        cldcEId.addAll(cldcCId);
        Flow_ReparentAccountfromContractLDC.ReparentAccount(cldcEId);
        
        if(!bgldclst.isempty()) update bgldclst;
        if(!cldclst.isempty()) update cldclst;
        if(!dasrUPlst.isempty()) database.update(dasrUPlst,false);
    }
    
    global void finish(database.BatchableContext bc){
        for(Account_Exception__c ae : aelst){
            ae.Most_Recent__c = false;
        }
        if(!aelst.isempty()) update aelst;
    }
}