src/objects/ChangeReason__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Allow_On_Outbound__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow On Outbound</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <label>Reason Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_Value__c</fullName>
        <label>Reason Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_For_Drop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid For Drop?</label>
        <type>Checkbox</type>
    </fields>
    <label>Change Reason</label>
</CustomObject>

src/classes/ChangeReasonUtilTest.cls
/* 
 * Name: ChangeReasonUtilTest
 * Type: Apex Test Coverage  
 * Description: Test coverage for the ChangeReasonUtil Apex Class.         
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sneha Gadde        03/25/2016       1. Initial Version created
 */
@isTest(SeeAllData=false)
private class ChangeReasonUtilTest{
private static testmethod void ChangeReasonUtil_UnitTest() 
 {
   Test.startTest();
   ChangeReason__c cr = new ChangeReason__c();
      cr.name = 'Test CR';
      cr.Reason_Value__c = 'Test Val';
      cr.Reason_Code__c = 'Test Code';
      cr.Object_API_Name__c = 'ChangeReason__c';
      cr.Valid_For_Drop__c = true;
      cr.Allow_On_Outbound__c = true;
      insert cr;
      
      ChangeReasonUtil cntrl = new ChangeReasonUtil();
      ChangeReasonUtil.getChgRsnCodeForVal('Test Val');
      ChangeReasonUtil.getChgRsnCodeForCode('Test Code');
      ChangeReasonUtil.getChgRsnCodeForVal(null);
      ChangeReasonUtil.getChgRsnCodeForCode(null);
          
      ChangeReasonUtil.getChgRsnCodeForVal('Test Val','ChangeReason__c');
      ChangeReasonUtil.getDropCodeForVal('Test Val','ChangeReason__c');
      ChangeReasonUtil.getChgRsnValForCode('Test Val','ChangeReason__c');
      ChangeReasonUtil.isRsnAllowOutbound('Test Val','ChangeReason__c');
      ChangeReasonUtil.getChgRsnCodeForVal('Test Code','ChangeReason__c');
      ChangeReasonUtil.getChgRsnCodeForVal(null,'');
      ChangeReasonUtil.getDropCodeForVal('Test Code','ChangeReason__c');
      ChangeReasonUtil.getDropCodeForVal(null,'');
      ChangeReasonUtil.getChgRsnValForCode('Test Code','ChangeReason__c');
      ChangeReasonUtil.getChgRsnValForCode(null,'');
      ChangeReasonUtil.isRsnAllowOutbound('Test Code','ChangeReason__c');
      ChangeReasonUtil.isRsnAllowOutbound(null,'');
   Test.stopTest();  
 }
 
}