src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Quote</label>
        <referenceTo>Retail_Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Credit_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Check_Required__c</fullName>
        <formula>OR(Max_60_Day_Max_Exposure__c &gt;= 375000, Max_Aggregate_PLC__c &gt;= 5000)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Check Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Executable_Quote_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Executable Quote Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refresh_Expiration_Date__c</fullName>
        <description>Refresh Expiration Date</description>
        <label>Refresh Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Credit_Check_Required__c</fullName>
        <formula>OR(X60_Day_Max_Exposure__c &gt;= 375000,  Aggregate_PLC__c &gt;= 5000)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Check Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Price_KWH__c</fullName>
        <label>Quote Price KWH</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Request Status</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waiting on Load Data</fullName>
                </value>
                <value>
                    <fullName>Manual Pricing in Process</fullName>
                </value>
                <value>
                    <fullName>Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Pricing Complete</fullName>
                </value>
                <value>
                    <fullName>Error-Invalid Account</fullName>
                </value>
                <value>
                    <fullName>Error Utility Web-Service Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Error - Price Curve Invalid</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>Term in Months</description>
        <label>Term (Whole Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetExecutablePriceController.cls
/* 
 * Name: GetExecutablePriceController
 * Type: Apex Class
 * Test Class: GetExecutablePriceControllerTest
 * Description:  This class is used to request for the Executable pricing information based on the Quote selected from "Pricing Complete" list. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         01/30/2016       1. Initial Version created
 */
public class GetExecutablePriceController {

    public List<RetailQuoteWrapper> retQuoteWrapList {get; set;}
    public ApexPages.StandardController oppCntrlr {get;Set;}
    public Boolean quotesAvailable {get; set;} 
    public static final String STATUS_CONTRACT_SIGNED = 'Contract Signed';
    public ID RetQuoteIndivativeId;
    public ID RetQuoteExecutableId;
    private final Opportunity opty;
      Opportunity opp;
        Account acc;
    Set<Id> idsToClone = new Set<Id>();
         
    public GetExecutablePriceController(ApexPages.StandardController stdController){
        oppCntrlr=stdController;
        Opportunity recOpp = (Opportunity)stdController.getRecord(); 
        quotesAvailable = true;        
        RetQuoteIndivativeId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_INDICATIVE);
        RetQuoteExecutableId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,ConstantUtility.RT_EXECUTABLE);
        retQuoteWrapList = new List<RetailQuoteWrapper>();
        if(recOpp != null && recOpp.id != null){
           if(label.OppQueryFields != null && label.OppQueryFields !=''){
              this.opty = (Opportunity)ConstantUtility.getObject('Opportunity',label.OppQueryFields,recOpp.id);
            }
            else{
              this.opty = (Opportunity)ConstantUtility.getObject('Opportunity','Id:Name:Refresh_Expiration_Date__c:Executable_Quote_Generated__c',recOpp.id);   
           }
           if((opty.Refresh_Expiration_Date__c >= System.TODAY() || opty.Refresh_Expiration_Date__c == null)){
                if(retQuoteWrapList == null) {
                    retQuoteWrapList = new List<RetailQuoteWrapper>();
                }
                 for(Retail_Quote__c rq : [SELECT id,Name,Request_Status__c,Term__c,Quote_Price_KWH__c,Product__c,Credit_Check_Required__c,Opportunity__r.Credit_Approved__c
                                        FROM  Retail_Quote__c WHERE Request_Status__c = :ConstantUtility.STATUS_PRICING_COMPLETE 
                                        AND RecordTypeId = :RetQuoteIndivativeId AND Opportunity__c = :opty.Id]){                
                    retQuoteWrapList.add(new RetailQuoteWrapper(rq));                   
                }   
            }
        }
        if(retQuoteWrapList.isEmpty()){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ConstantUtility.ERR_NO_EXECUTABLE_QUOTES_AVAILABLE));            
            quotesAvailable = false;
        }
        
    }
    
    public PageReference cancelRequest(){
        return getOptyView();       
    }
     
    public PageReference createRequest(){
    System.Debug('Test:*****');
        Set<Id> idsToClone = new Set<Id>();     
        Id oppId = opty.id;
        String strQuery = ConstantUtility.getObjectFieldsQuery(ConstantUtility.RT_OBJECT);
        strQuery += ' FROM '+ConstantUtility.RT_OBJECT+' WHERE RecordTypeId = :RetQuoteIndivativeId and Opportunity__c = :oppId' ;
        List<Retail_Quote__c> lstRTQT = Database.query(strQuery);
        
        for(RetailQuoteWrapper rqw :retQuoteWrapList){
            if(rqw.selected){
                if(rqw.retQuote.Credit_Check_Required__c && !rqw.retQuote.Opportunity__r.Credit_Approved__c ){
                   ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ConstantUtility.ERR_CHECK_CREDIT_APPROVAL));
                    quotesAvailable = false;
                    return null;
                }
                else {                      
                    idsToClone.add(rqw.retQuote.id);
                }       
            }
        }
         if(label.OppQueryFields != null && label.OppQueryFields !=''){
          opp = (Opportunity)ConstantUtility.getObject('Opportunity',label.OppQueryFields,oppId);
        }
        else{
          opp = (Opportunity)ConstantUtility.getObject('Opportunity','Id:Name:Refresh_Expiration_Date__c:Executable_Quote_Generated__c',oppId);   
        }
        
        if(opp.AccountId != null){
            if(label.AccQueryFields != null && label.AccQueryFields !=''){
                acc = (Account)ConstantUtility.getObject('Account',label.AccQueryFields,opp.AccountId);
            }
         else{
                acc = (Account)ConstantUtility.getObject('Account','Id:Name',opp.AccountId);    
            }
        }
        
        RetailQuoteHandler.cloneAndCreateQuoteHistory(lstRTQT, idsToClone, ConstantUtility.RT_EXECUTABLE, ConstantUtility.RT_INDICATIVE);
        opp.Executable_Quote_Generated__c=true;
        update opp;
        String strQuery1 = ConstantUtility.getObjectFieldsQuery(ConstantUtility.RT_OBJECT);
        string qtStatus=ConstantUtility.STATUS_WAITING;
        strQuery1 += ' FROM '+ConstantUtility.RT_OBJECT+' WHERE RecordTypeId = :RetQuoteExecutableId and Request_Status__c =:qtStatus and Opportunity__c = :oppId' ;
        List<Retail_Quote__c> lstRTQT1 = Database.query(strQuery1); 
        //PricingWSHelper.sendQuotesForPricing(lstRTQT1,opp,acc); 
       
        PricingWSHelper.sendQuotesForPricingFuture(PricingWSHelper.getQuotesforPricing(lstRTQT1,opp,acc));
        
        return getOptyView();     
    }
    
    public PageReference sendNewQuotes(){
        checkQuoteExpiry();
         String oppId = opty.Id;
        List<Retail_Quote__c> newExecutableQuotesLst = new List<Retail_Quote__c>();
        
        System.Debug('Quotes are being sent ... ******');
         String strQuery = ConstantUtility.getObjectFieldsQuery(ConstantUtility.RT_OBJECT);
        strQuery += ' FROM Retail_Quote__c WHERE (RecordTypeId = :RetQuoteExecutableId or (RecordTypeId = :RetQuoteIndivativeId and Request_Status__c =\''+ ConstantUtility.STATUS_NEW+'\')) and Request_Status__c !=\''+STATUS_CONTRACT_SIGNED+'\' and Opportunity__c = :oppId'; //New Quotes::
        newExecutableQuotesLst =  Database.query(strQuery);
        system.debug('New Quotes::'+newExecutableQuotesLst);
       if(!newExecutableQuotesLst.isEmpty()){
         Set<id> rtQuoteIdLst = new Set<id>();
          for(Retail_Quote__c recRTQT :newExecutableQuotesLst) 
            rtQuoteIdLst.add(recRTQT.id);  
            sendQuotesForPricing(rtQuoteIdLst,oppId);
           return getOptyView();
        } 
        
        
       /* for(Retail_Quote__c rq : newExecutableQuotesLst){
                rq.Request_Status__c = ConstantUtility.STATUS_WAITING;                      
                newExecutableQuotesLst.add(rq);
                
        }
        if(!newExecutableQuotesLst.isEmpty()){
            update newExecutableQuotesLst;
            return getOptyView();
        }*/
        if(!quotesAvailable)
            return getOptyView();
        else    
            return null; 
    } 
    
    @future(callout=true)
    public static void sendQuotesForPricing(Set<id> rtQuoteIdLst, id oppId)
    {
        Opportunity opp;
        Account acc;
        String strQuery = ConstantUtility.getObjectFieldsQuery(ConstantUtility.RT_OBJECT);
        strQuery += ' FROM Retail_Quote__c WHERE id=:rtQuoteIdLst' ;
         List<Retail_Quote__c> lstQuoteSendForPricing =  Database.query(strQuery);
         if(label.OppQueryFields != null && label.OppQueryFields !=''){
          opp = (Opportunity)ConstantUtility.getObject('Opportunity',label.OppQueryFields,oppId);
        }
        else{
          opp = (Opportunity)ConstantUtility.getObject('Opportunity','Id:Name:Refresh_Expiration_Date__c:AccountId',oppId);   
        }
        
        if(opp.AccountId != null){
            if(label.AccQueryFields != null && label.AccQueryFields !=''){
                acc = (Account)ConstantUtility.getObject('Account',label.AccQueryFields,opp.AccountId);
            }
            else{
                acc = (Account)ConstantUtility.getObject('Account','Id:Name',opp.AccountId);    
            }
        }
        
        if(!lstQuoteSendForPricing.isEmpty()){
           PricingWSHelper.sendQuotesForPricing(lstQuoteSendForPricing,opp,acc);
           system.debug('Response sent');
          for(Retail_Quote__c recRTQT : lstQuoteSendForPricing)  
           recRTQT.Request_Status__c = ConstantUtility.STATUS_WAITING;
            
           Database.SaveResult[] srList = Database.update(lstQuoteSendForPricing, false);
        }
        
    }
    
    public void checkQuoteExpiry(){
        String quoteStatus = '';
        String oppId = opty.Id;
        String strQuery = ConstantUtility.getObjectFieldsQuery(ConstantUtility.RT_OBJECT);
        strQuery += ' FROM Retail_Quote__c WHERE RecordTypeId = :RetQuoteExecutableId and Opportunity__c = :oppId' ;
        //List<Retail_Quote__c> lstRTQT = ; 
        List<Retail_Quote__c> lstQuoteExpired = new List<Retail_Quote__c>(); 
        if(opty != null && opty.id != null){                       
            for(Retail_Quote__c rq : Database.query(strQuery)){
                quoteStatus = rq.Request_Status__c;
                if(opty.Refresh_Expiration_Date__c >= System.TODAY() || opty.Refresh_Expiration_Date__c == null){
                    /*
                    if(setQuoteSendForPricing.contains(quoteStatus)) {
                        rq.Request_Status__c = ConstantUtility.STATUS_WAITING;
                        lstQuoteSendForPricing.add(rq);    
                    }
                    if(setQuoteWaitingUpdate.contains(quoteStatus)) {
                        lstQuoteWaitingUpdate.add(rq); 
                    }*/
                    if(quoteStatus.equals(ConstantUtility.STATUS_EXPIRED)){
                        lstQuoteExpired.add(rq);   
                        idsToClone.add(rq.id);
                    }
                }
                else {                  
                     if(quoteStatus != STATUS_CONTRACT_SIGNED){
                            lstQuoteExpired.add(rq);   
                            idsToClone.add(rq.id);
                     }
                }
            }
           
            if(!lstQuoteExpired.isEmpty()){
               RetailQuoteHandler.cloneAndCreateQuoteHistory(lstQuoteExpired, idsToClone,ConstantUtility.RT_INDICATIVE, ConstantUtility.RT_EXECUTABLE);   
            }
        }
    }
    
    public class RetailQuoteWrapper {
        public Retail_Quote__c retQuote {get; set;}
        public Boolean selected {get; set;}
 
        public RetailQuoteWrapper(Retail_Quote__c q) {
            retQuote = q;
            selected = false;
        }
    }
    
    public PageReference getOptyView(){
        
        return (new ApexPages.StandardController(opty)).view();
    }
}