src/objects/Contract_LDC__c.object
<CustomObject>
    <description>Junction Object many to many relationship (Contract/LDC)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <description>LDC Account Number</description>
        <formula>LDC_Account__r.LDC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LDC Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Contract LDCS</relationshipLabel>
        <relationshipName>Contract_LDCS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract LDC</label>
    <nameField>
        <label>Contract LDC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract LDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DASR Requests</relationshipLabel>
        <relationshipName>DASR_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DASR_Submit_Date__c</fullName>
        <label>DASR Submit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dynegy_Initiated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Dynegy Initiated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <label>LDC Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LDCOnIncorrectContractList.cls
/**
 * This class is designed to provide a report for lDCs on incorrect contract wrt DASR
 *
 * @
 * @version 1.0
 **/

global class LDCOnIncorrectContractList implements Database.Batchable <sobject>,Database.Stateful{

    string query;
    global Document objD1 = new Document();
    
    global String filecontent;
    //fileContent = 'LDCId' + ','+'LDCNumber'+','+'LDC_Account_Status'+','+'DASR.Name'+','+'Change_Effective_Date'+','+'DASR_Type'+','+'DASR.Contract'+','+'Current Contract'+'\n';
    global LDCOnIncorrectContractList( ){
        
    }
 
    global Database.QueryLocator start (Database.BatchableContext bc){
        fileContent = 'LDCId' + ','+'LDCNumber'+','+'LDC_Account_Status'+','+'DASR.Name'+','+'Change_Effective_Date'+','+'DASR_Type'+','+'DASR.Contract'+','+'Current Contract'+'\n';
        query='select id,(select id FROM DASRs__r where Change_Effective_Date__c <= Today and Dynegy_Initiated__c = true AND Accepted__c = true AND Integration_Status__c = \'Complete\' and contract__c != null and DASR_Type__c != null order by Change_Effective_Date__c DESC,DASR_Submit_Date__c DESC LIMIT 1),(select Id from Contract_LDCs__r where Active__C = true LIMIT 1 ) from LDC_Account__C where id IN (select LDC_Account__c from DASR_REQUEST__C where Change_Effective_Date__c <= Today and Dynegy_Initiated__c = true AND Accepted__c = true AND Integration_Status__c = \'Complete\' and contract__c != null and DASR_Type__c != null)';
        
        return Database.getQueryLocator(query);
    }
   
    global void execute (Database.BatchableContext bc, list<sobject> scope ){
        list<LDC_Account__c> LDCList =  (list<LDC_Account__c>) scope;
        set<ID> DASRIds = new set<ID>();
        set<Id> CLDCIds = new set<Id>();
        set<Id> MissingActiveCLDC = new set<Id>();
        Map<Id,DASR_Request__c> LDCIdToDasR = new Map<Id,DASR_Request__c>();
        Map<Id,Contract_LDC__C> LDCIdToCLDC = new Map<Id,Contract_LDC__C>();
        
        for(LDC_Account__c LDC: LDCList)
        {
            Contract_LDC__C CLDC;
            DASR_Request__c DASR = LDC.DASRs__R;
            DASRIds.add(DASR.Id);
            if(LDC.Contract_LDCs__r.size() > 0)
            {
                CLDC = LDC.Contract_LDCs__r;
                CLDCIds.add(CLDC.Id);
            }
            else
            {
                MissingActiveCLDC.add(LDC.Id);
            }
        }
        for(DASR_Request__c DR: [select LDC_Account__c,LDC_Account__r.LDC_Account_Status__C,LDC_Account__r.LDC_Account_Number__C,name,Change_Effective_Date__c,DASR_Type__c,contract__r.contractnumber from DASR_Request__c where Id IN:DASRIds] )
        {
            LDCIdToDasR.put(DR.LDC_Account__c,DR);  
        }
        for(Contract_LDC__C CL:[select LDC_Account__c,contract__r.contractnumber from Contract_LDC__C where Id IN:CLDCIds])
        {
            if(LDCIdToDasR.containskey(CL.LDC_Account__c))
            {
                if(LDCIdToDasR.get(CL.LDC_Account__c).contract__r.contractnumber != CL.contract__r.contractnumber)
                {
                    fileContent+= LDCIdToDasR.get(CL.LDC_Account__c).LDC_Account__c+','+'A'+LDCIdToDasR.get(CL.LDC_Account__c).LDC_Account__r.LDC_Account_Number__C+','+LDCIdToDasR.get(CL.LDC_Account__c).LDC_Account__r.LDC_Account_Status__C+','+LDCIdToDasR.get(CL.LDC_Account__c).Name+','+LDCIdToDasR.get(CL.LDC_Account__c).Change_Effective_Date__c+','+LDCIdToDasR.get(CL.LDC_Account__c).DASR_Type__c+','+LDCIdToDasR.get(CL.LDC_Account__c).contract__r.contractnumber+','+CL.contract__r.contractnumber+'\n';
                }
            }
            
        }
        for(Id LDCid:MissingActiveCLDC)
        {
            fileContent+= LDCIdToDasR.get(LDCid).LDC_Account__c+','+'A'+LDCIdToDasR.get(LDCid).LDC_Account__r.LDC_Account_Number__C+','+LDCIdToDasR.get(LDCid).LDC_Account__r.LDC_Account_Status__C+','+LDCIdToDasR.get(LDCid).Name+','+LDCIdToDasR.get(LDCid).Change_Effective_Date__c+','+LDCIdToDasR.get(LDCid).DASR_Type__c+','+LDCIdToDasR.get(LDCid).contract__r.contractnumber+','+' '+'\n';
        }
        
        
        
    }
    global void finish (Database.BatchableContext bc){
        system.debug('BatchableContext : '+bc);
        objD1.name = 'LDCContractMismatch.csv';
        objD1.body = blob.valueof(fileContent);
        objD1.folderId = UserInfo.getUserId();
        insert objD1;
  
    }
}