src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DASR Requests</relationshipLabel>
        <relationshipName>DASR_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_GAAD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to Check whether the DASR is most recent one or not</description>
        <label>Most Recent DASR</label>
        <type>Checkbox</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Utility Provider</description>
        <label>LDC Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>LDC Account&apos;s Service Territory doesn&apos;t match with the LDC Vendor&apos;s Service Territory</errorMessage>
            <filterItems>
                <field>LDC_Vendor__c.Service_Territory__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Territory__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LDC_Vendor__c</referenceTo>
        <relationshipLabel>LDC Accounts</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opt_out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <description>Service State Address State for LDC Account</description>
        <label>Service State</label>
        <length>165</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LDC_Vendor__c.object
<CustomObject>
    <description>Utility Vendor for LDC</description>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK         </fullName>
                </value>
                <value>
                    <fullName>AL          </fullName>
                </value>
                <value>
                    <fullName>AR         </fullName>
                </value>
                <value>
                    <fullName>AZ          </fullName>
                </value>
                <value>
                    <fullName>CA         </fullName>
                </value>
                <value>
                    <fullName>CO         </fullName>
                </value>
                <value>
                    <fullName>CT          </fullName>
                </value>
                <value>
                    <fullName>DC         </fullName>
                </value>
                <value>
                    <fullName>DE          </fullName>
                </value>
                <value>
                    <fullName>FL           </fullName>
                </value>
                <value>
                    <fullName>GA         </fullName>
                </value>
                <value>
                    <fullName>HI           </fullName>
                </value>
                <value>
                    <fullName>IA           </fullName>
                </value>
                <value>
                    <fullName>ID           </fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN          </fullName>
                </value>
                <value>
                    <fullName>KS          </fullName>
                </value>
                <value>
                    <fullName>KY          </fullName>
                </value>
                <value>
                    <fullName>LA          </fullName>
                </value>
                <value>
                    <fullName>MA        </fullName>
                </value>
                <value>
                    <fullName>MD        </fullName>
                </value>
                <value>
                    <fullName>ME         </fullName>
                </value>
                <value>
                    <fullName>MI          </fullName>
                </value>
                <value>
                    <fullName>MN        </fullName>
                </value>
                <value>
                    <fullName>MO        </fullName>
                </value>
                <value>
                    <fullName>MS         </fullName>
                </value>
                <value>
                    <fullName>MT         </fullName>
                </value>
                <value>
                    <fullName>NC         </fullName>
                </value>
                <value>
                    <fullName>ND         </fullName>
                </value>
                <value>
                    <fullName>NE         </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LDC Vendor</label>
    <nameField>
        <label>LDC Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/insertDASRRequestGAAD.cls
/* 
 * Name: insertDASRRequestGAAD
 * Type: Apex Class
 * Test Class: insertDASRRequestGAAD_Test
 * Description:  This batch class is to automate Drops for Enrollments. 
 * Change History:
 *=====================================================================================================================================================
 * Version     Author                   Date             Description 
 * 1.0         Nanda Eluru              04/28/2017       1. Initial Version created
 * 2.0         Nanda Eluru	            07/27/2017       1. Updated the class to requirement
 * 3.0         Prasad Paladugu          03/01/2018       1. Enhanced functionality for Never Served customers
 														 2. Moved the original code to trigger handler class
 */
 global class insertDASRRequestGAAD implements Database.batchable<sObject>{
    String query;
    global insertDASRRequestGAAD(){}
    global insertDASRRequestGAAD(String q) {
       query = q;
   }
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'Select LDC_Account__c, DASR_Type__c, Most_Recent_GAAD__c, Contract__c, Integration_Status__C, LDC_Account__r.LDC_Account_Status__c, LDC_Account__r.opt_out__c, LDC_Account__r.LDC_Vendor__r.Service_State__c, change_effective_date__c from DASR_Request__c where (LDC_Account__r.opt_out__c = true and LDC_Account__r.LDC_Vendor__r.Service_State__c LIKE \'%IL%\' and change_effective_date__c != null and (Integration_Status__C = \'Waiting For Response\' or Integration_Status__C = \'Complete\') and DASR_Type__c = \'GAAE\')';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<DASR_Request__c> oodasrlst = (list<DASR_Request__c>) scope;
        string init ='Batch';
        LDCAccountTriggerHandler ldchandler = new LDCAccountTriggerHandler();
        ldchandler.generateGAADDasr(oodasrlst,init);
    }   
    global void finish(Database.BatchableContext BC){
    }   
}