src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DASR_Submit_Date__c</fullName>
        <label>DASR Submit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Send_Date__c</fullName>
        <description>Date to be sent to utility</description>
        <label>Integration Send Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_EDI_Update_Date__c</fullName>
        <label>Last EDI Update Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Originator_Name__c</fullName>
        <formula>LDC_Account__r.Account__r.Supplier__r.Name</formula>
        <label>Originator Name (old)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <formula>LDC_Account__r.LDC_Vendor__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Name (old)</label>
        <type>Text</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Enrolled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrolled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <description>Status of the enrollment</description>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Ready</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Start_Date__c</fullName>
        <description>Start Date of the LDC</description>
        <label>LDC Start Date</label>
        <type>Date</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EDIDataResetBatch.cls
global class EDIDataResetBatch implements Database.Batchable<sObject>, Database.Stateful,Database.AllowsCallouts
{
    String q;
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        q=ConstantUtility.getObjectFieldsQuery('DASR_Request__c') +' From DASR_Request__c where (Integration_Status__c  in (\'Waiting For Response\')) AND DASR_Submit_Date__c !=null  ' ;
        
        q += ' order by Originator_Name__c,Recipient_Name__c, CreatedDate ASC ';
        //q = generateSOQLQuery('DASR_Request__c');
        System.debug('q=='+q);
        return Database.getQueryLocator(q);
    }
    public void execute(Database.BatchableContext BC, List<Sobject> scope)
    {
        List<DASR_Request__c> lToProcess = (List<DASR_Request__c>) scope;
        
        List<DASR_Request__c> lDR = new List<DASR_Request__c>();
        Set<Id> sLDCID = new Set<Id>();
        LisT<LDC_Account__c> lLA = new list<LDC_Account__c>();
        LDC_Account__c tLA;
        for(DASR_Request__c tDR : lToProcess)
        {
            if(tDR.DASR_Type__c != null)
            {
                sLDCID.add(tDR.LDC_Account__c);
                tDR.Integration_Status__c ='Complete';
                tDR.Integration_Send_Date__c = System.today();
                tDR.Accepted__c  = true;
                tDR.Last_EDI_Update_Date__c = system.today();
                lDR.add(tDR);
                
                if(tDR.LDC_Account__c != null && tDR.DASR_Type__c == 'GAAE' )
                { 
                    tLA = new LDC_Account__c();
                    tLA.id = tDR.LDC_Account__c;
                    tLA.LDC_Account_Status__c ='ACTIVE';
                    tLA.Enrollment_Status__c ='Accepted';
                    tLA.Enrolled__c = true;
                    if(tDR.LDC_Account__r.LDC_Start_Date__c == null){
                        
                        tLA.LDC_Start_Date__c = System.today();
                    }
                    lLA.add(tLA);
                    
                }
                else if(tDR.LDC_Account__c != null && tDR.DASR_Type__c == 'GAAD' )
                { 
                    tLA = new LDC_Account__c();
                    tLA.id = tDR.LDC_Account__c;
                    tLA.LDC_Account_Status__c ='PENDING_FINAL';

                    lLA.add(tLA);
                    
                }
            }
        }
        update lDR;
        update lLA;
    }
    public void finish(Database.BatchableContext BC)
    {}    
}