src/objects/DASR_Request__c.object
<CustomObject>
    <description>Junction object with many to many relationship between Contract and LDC Account to support communication with the utility.</description>
    <fields>
        <fullName>Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DASR Requests</relationshipLabel>
        <relationshipName>DASR_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DASR_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DASR Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GAAC</fullName>
                </value>
                <value>
                    <fullName>GAAE</fullName>
                </value>
                <value>
                    <fullName>GAAH</fullName>
                </value>
                <value>
                    <fullName>GAAD</fullName>
                </value>
                <value>
                    <fullName>GAAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dynegy_Initiated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Dynegy Initiated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting For Response</fullName>
                </value>
                <value>
                    <fullName>Manually Fulfilled</fullName>
                </value>
                <value>
                    <fullName>TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_GAAD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to Check whether the DASR is most recent one or not</description>
        <label>Most Recent DASR</label>
        <type>Checkbox</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/DASRBatchJobAuto.cls
global class DASRBatchJobAuto implements System.Queueable{
    
   /* global void execute (SchedulableContext sc){
        system.debug('Starting auto.......');
        list<aggregateresult> result = [select count(id),Change_Effective_Date__c from dasr_request__c where Accepted__c = true and Dynegy_Initiated__c = true and Integration_Status__c = 'Complete'
                                            and createdby.name != 'Integration User' and DASR_Type__c = 'GAAC' and DASR_Activated__c = false 
                                            and Change_Effective_Date__c <= today 
                                            group by Change_Effective_Date__c
                                            order by Change_Effective_Date__c ];
        system.debug('Result : '+result.size()+' : '+result);
        string dateres ='';
        for(AggregateResult arr : result){
            system.debug('AggregateResult : '+arr); 
            dateres=string.valueof(arr.get('Change_Effective_Date__c'));
            
        }
        system.debug('dateres : '+dateres);
        dateres=string.valueof(result[0].get('Change_Effective_Date__c')); 
        DASRBatchJob Dasr = new DASRBatchJob(Date.valueof(result[0].get('Change_Effective_Date__c')),Integer.valueof(result[0].get('expr0')));
        Database.executeBatch(Dasr,20);
        system.debug('dateres : '+dateres);
    }*/
    global final Integer recordstotal;
    global final Date DatetoProcess;
    global set<id> errset;
    
    public DASRBatchJobAuto(){
        
    }
    
    public DASRBatchJobAuto(Date dt,Integer co,set<id> idset){
        DatetoProcess = dt;
        recordstotal = co;
        errset = idset;
    }
    
    global void execute (QueueableContext qc){
        system.debug('Starting Queueable auto.......');
        list<aggregateresult> result = [select count(id),Change_Effective_Date__c from dasr_request__c where Accepted__c = true and Dynegy_Initiated__c = true and (Integration_Status__c = 'Complete' 
                                            or (Integration_Status__c = 'Manually Fulfilled'  and ldc_account__r.service_territory__c = 'ComEd-IL')) and createdby.name != 'Integration User' 
                                            and DASR_Type__c = 'GAAC' and DASR_Activated__c = false and contract__c != null and Most_recent_gaad__c = true //and Change_Effective_Date__c <= today 
                                            group by Change_Effective_Date__c
                                            order by Change_Effective_Date__c limit 20];
        system.debug('Result : '+result.size()+' : '+result);
        if(!result.isempty()){
            if(errset == null)
                errset = new set<id>();
                
            string dateres = string.valueof(result[0].get('Change_Effective_Date__c')); 
            Date dasrdt = Date.valueof(result[0].get('Change_Effective_Date__c'));
            system.debug('dateres : '+dateres);
            DASRBatchJob Dasr;
            if(DatetoProcess == dasrdt){            //If looping over same date reduce batch size in order to filter out the erroring one.
                if(recordstotal < 5){
                    Dasr = new DASRBatchJob(Date.valueof(result[0].get('Change_Effective_Date__c')),recordstotal+1,errset);
                    Database.executeBatch(Dasr,10);
                }
                else if(recordstotal == 5){
                    Dasr = new DASRBatchJob(Date.valueof(result[0].get('Change_Effective_Date__c')),recordstotal+1,errset);
                    Database.executeBatch(Dasr,1);
                }
                else{                               //If error is not resolved skip that dasr by updating                               
                    list<Dasr_request__c> dasruplst = new list<Dasr_request__c>();
                    for(Dasr_request__c dlist : [select id,dasr_activated__c from dasr_request__c where Accepted__c = true and Dynegy_Initiated__c = true and (Integration_Status__c = 'Complete' 
                                            or (Integration_Status__c = 'Manually Fulfilled'  and ldc_account__r.service_territory__c = 'ComEd-IL')) and createdby.name != 'Integration User' 
                                            and DASR_Type__c = 'GAAC' and DASR_Activated__c = false and Change_Effective_Date__c =: dasrdt and contract__c != null and Most_recent_gaad__c = true]){
                        errset.add(dlist.id);
                        dlist.dasr_activated__c = true;
                        dasruplst.add(dlist);                                                   
                    }
                    if(!dasruplst.isempty()) update dasruplst;
                    if(result.size() > 1){
                        Dasr = new DASRBatchJob(Date.valueof(result[1].get('Change_Effective_Date__c')),1,errset);
                        Database.executeBatch(Dasr,100);
                    }
                    else{
                        Dasr = new DASRBatchJob(Date.valueof(result[0].get('Change_Effective_Date__c')),1,errset);
                        Database.executeBatch(Dasr,100);
                    }
                }
            }
            else{
                Dasr = new DASRBatchJob(Date.valueof(result[0].get('Change_Effective_Date__c')),1,errset);
                Database.executeBatch(Dasr,100);
            }
            system.debug('dateres : '+dateres);
        }
    }
}