src/objects/EDIIntegrationConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Meter_Number__c</fullName>
        <label>Default Meter Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EDI_Outbound_End_Point__c</fullName>
        <label>EDI Outbound End Point</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Interval_Request_Code__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <label>Interval Request Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_Email__c</fullName>
        <label>Notify Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receipient_DUNS__c</fullName>
        <label>Receipient DUNS</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <label>Recipient Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EDI Integration Configuration</label>
</CustomObject>

src/classes/EDIIntegrationConfigUtil.cls
public class EDIIntegrationConfigUtil {
    public static EDIIntegrationConfiguration__c  intConfig;
    static {
        intConfig = EDIIntegrationConfiguration__c.getInstance('Default');
    }
    public static String getNotificationUserId() {
        return intConfig != null && intConfig.Notify_Email__c  != null ? intConfig.Notify_Email__c : 'anandmishra@kpmg.com';
    }  
    public static String getIntUserName() {
        return intConfig != null && intConfig.User_Name__c   != null ? intConfig.User_Name__c  : 'dynsfdev';
    }  
    public static String getIntUserPwd() {
        return intConfig != null && intConfig.Password__c    != null ? intConfig.Password__c   : 'u7SBbSIG';
    }
    public static String getEDIEndPoint() {
        return intConfig != null && intConfig.EDI_Outbound_End_Point__c  != null ? intConfig.EDI_Outbound_End_Point__c : 'https://salesforcetest.dynegy.com/SforceESG.svc/SforceESG';
    }
    public static String getIntRequestCode() {
        return intConfig != null && intConfig.Interval_Request_Code__c != null ? intConfig.Interval_Request_Code__c : 'N';
    }
    public static String getIntDefMeterNumber() {
        return intConfig != null && intConfig.Default_Meter_Number__c  != null ? intConfig.Default_Meter_Number__c  : 'ALL';
    }
    public static String getESGRecpName() {
        return intConfig != null && intConfig.Recipient_Name__c     != null ? intConfig.Recipient_Name__c    : 'ESG';
    }
    public static String getESGRecpDuns() {
        return intConfig != null && intConfig.Receipient_DUNS__c     != null ? intConfig.Receipient_DUNS__c    : '049050839';
    }
}