src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Credit_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Check_Notes__c</fullName>
        <label>Credit Check Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LDC_Annual_Usage__c</fullName>
        <description>The Annual Usage Recorded of the related LDC Account.</description>
        <inlineHelpText>The Annual Usage Recorded of the related LDC Account.</inlineHelpText>
        <label>LDC Annual Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cloneOpportunityCntl.cls
/*****************************************************************************************
Class :  cloneOpportunityCntl
Description : To clone opportunity LDC's along with opoortunity when clonned.
Version Date            Author      Comments
1.0     9/11/2017       Prasad      Initial Version Created
******************************************************************************************/
public with sharing class cloneOpportunityCntl {
    
    public opportunity opp {get;set;}
    public opportunity newopp {get;set;}
    public ID oldOppId {get;set;}
    public boolean displayPopUp {get;set;}
    public string selectedoption {get;set;}
    
    public list<selectoption> getsellist(){
        list<selectoption> options = new list<selectoption>();
        options.add(new selectoption('Yes','Yes'));
        options.add(new selectoption('No','No'));
        return options;
    }
    
    public cloneOpportunityCntl(ApexPages.StandardController controller){
        opp = (opportunity)controller.getrecord();
        opp.Credit_Check_Notes__c= null;
        opp.Credit_Approved__c = false;
        oldOppId = opp.Id;
    }
    
    public pagereference saveopp(){
        pagereference pg;
        try{
            newopp = opp.clone(false,false,true,false);
            insert newopp;
        }
        catch(Exception e){
            ApexPages.addMessages(e); 
        }
        system.debug('Test oldID : '+oldoppId+' ID --> '+newopp.id);
        if(newopp.id != null && (newopp.type == 'C&I' || newopp.type == 'Small Business')){
            list<opportunity_ldc__c> oldclst= [select id,name,ldc_account__c,ldc_annual_usage__c,opportunity__c,rate_code__c from opportunity_ldc__c where opportunity__c =: oldoppId];
            if(!oldclst.isempty()){
                displayPopUp = true;
                return null;
            }
            else{
                pg = new pagereference('/'+newopp.id);
                pg.setredirect(true);
                return pg;
            }
        }
        if(newopp.id != null && (newopp.type != 'C&I' || newopp.type != 'Small Business')){
            pg = new pagereference('/'+newopp.id);
            pg.setredirect(true);
            return pg;
        }
        else
            return null;
    }
    
    public pagereference createoppldc(){
        displayPopUp=false;
        pagereference clonepg;
        system.debug('Test oldID : '+oldoppId+' ID --> '+newopp.id);
        if(selectedoption == 'Yes'){
            list<opportunity_ldc__c> oldclst= [select id,name,ldc_account__c,ldc_annual_usage__c,opportunity__c,rate_code__c from opportunity_ldc__c where opportunity__c =: oldoppId];
            list<opportunity_ldc__c> oldclstnew = new list<opportunity_ldc__c>();
            for(opportunity_ldc__c oldc : oldclst){
                opportunity_ldc__c oppldc = new opportunity_ldc__c();
                oppldc = oldc.clone(false,false,true,false);
                oppldc.opportunity__c = newopp.id;
                oldclstnew.add(oppldc);
            }
            if(!oldclstnew.isempty()) insert oldclstnew;
        }
        clonepg = new pagereference('/'+newopp.id);
        clonepg.setredirect(true);
        system.debug('Clonepg'+clonepg+' : '+clonepg.getRedirect()+' : '+clonepg.getParameters());
        return clonepg;
    }
    
    public pagereference savenewopp(){
        pagereference pg;
        try{
            newopp = opp.clone(false,false,true,false);
            insert newopp;
        }
        catch(Exception e){
            ApexPages.addMessages(e); 
        }
        system.debug('Test oldID : '+oldoppId+' ID --> '+newopp.id);
        
        if(newopp.id != null && (newopp.type == 'C&I' || newopp.type == 'Small Business')){
            list<opportunity_ldc__c> oldclst= [select id,name,ldc_account__c,ldc_annual_usage__c,opportunity__c,rate_code__c from opportunity_ldc__c where opportunity__c =: oldoppId];
            if(!oldclst.isempty()){
                displayPopUp = true;
                return null;
            }
            else{
                pg = new pagereference('/setup/ui/recordtypeselect.jsp?ent=Opportunity&retURL=%2F'+newopp.id+'&save_new_url=%2F006%2Fe%3F');
                pg.setredirect(true);
                return pg;
            }
        }
        if(newopp.id != null && (newopp.type != 'C&I' || newopp.type != 'Small Business')){
            pg = new pagereference('/setup/ui/recordtypeselect.jsp?ent=Opportunity&retURL=%2F'+newopp.id+'&save_new_url=%2F006%2Fe%3F');
            pg.setredirect(true);
            return pg;
        }
        else
            return null;
        /*if(newopp.id != null){
            pg = new pagereference('/setup/ui/recordtypeselect.jsp?ent=Opportunity&retURL=%2F'+newopp.id+'&save_new_url=%2F006%2Fe%3F');
            pg.setredirect(true);
            return pg;
        }
        else
            return null;*/
    }
    
    public pagereference Cancel(){
        PageReference opptyPage = new ApexPages.StandardController(opp).view();
        opptyPage.setRedirect(true);
        return opptyPage;
    }
    
}