src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/OpptyLDCLookupController.cls
/* 
 * Name: OpptyLDCLookupController
 * Type: Apex Class
 * Test Class: OpptyLDCLookupControllerTest
 * Description:  This class controls the custom Lookup for LDC Account. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti        01/15/2016       1. Initial Version created
 */
public with sharing class OpptyLDCLookupController {
    public Opportunity_LDC__c optyLDC {get;set;}
    public Opportunity oppRec;
    
    public LDC_Account__c account {get;set;} 
    public List<LDC_Account__c> results{get;set;}
    public string searchString{get;set;} 
    
    public OpptyLDCLookupController () {
      optyLDC = new Opportunity_LDC__c();
      List<Opportunity> lstOpp = [Select id, Name, AccountId, Service_Territory__c from Opportunity where id = :ApexPages.currentPage().getParameters().get('masterId')];
      if(!lstOpp.isEmpty()){
        oppRec = lstOpp[0];
        optyLDC.Opportunity__c = oppRec.id;   
      }
      else{
        oppRec = null;
      }                
    }   
    
    public PageReference cancel() { 
        if(oppRec == null) return new PageReference('/');   
        return optyViewRedirect();
    }
    
    public PageReference save() {
        insert optyLDC;
        if(oppRec == null) new PageReference('/');
        return optyViewRedirect();
    } 
    
    private PageReference optyViewRedirect(){
        PageReference opptyPage = new ApexPages.StandardController(oppRec).view();
        opptyPage.setRedirect(true);
        return opptyPage;
    }
    
    public void setSearchParam() {
      account = new LDC_Account__c();     
      searchString = System.currentPageReference().getParameters().get('lksrch');
      runSearch();  
    }
    
    public PageReference search() {
      runSearch();
      return null;
    }
    
    private void runSearch() {
      results = performSearch(searchString);               
    } 
    
    // run the search and return the records found. 
    private List<LDC_Account__c> performSearch(string searchString) {
      String opptyId = System.currentPageReference().getParameters().get('oppID');
      if(opptyId != null){
          //String accId = [Select id,Name,AccountId from Opportunity where id =:opptyId].AccountId;
          Opportunity oppty = [SELECT Name,AccountId,Service_Territory__c FROM Opportunity WHERE Id =:opptyId LIMIT 1];
          //String soql = 'select Id, Name, LDC_Account_Number__c,  Service_Territory__c from LDC_Account__c where Account__c = :accId';
          String accId = oppty.AccountId;
          String sTerr = oppty.Service_Territory__c;
          String soql = 'select Id, Name, LDC_Account_Number__c,  Service_Territory__c from LDC_Account__c where Account__c = :accId AND Service_Territory__c = :sTerr';
          if(searchString != '' && searchString != null)
            soql = soql +  ' AND name LIKE \'%' + searchString +'%\'';
          soql = soql + ' Limit 25'; 
          return database.query(soql);
      }
      return null;  
    }
    
    public PageReference saveAccount() {
      insert account;
      account = new LDC_Account__c();
      return null;
    }
    
    public string getFormTag() {
      return System.currentPageReference().getParameters().get('frm');
    }
    
    public string getTextBox() {
      return System.currentPageReference().getParameters().get('txt');
    }
}