src/objects/LDC_Account__c.object
<CustomObject>
    <description>Object supports the individual local distribution accounts tied to a Customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LDC Accounts (Account)</relationshipLabel>
        <relationshipName>LDC_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Alias_Name__c</fullName>
        <description>This field is created during the iAve Conversion</description>
        <label>Alias Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>LDC Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW_ACCOUNT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_FINAL</fullName>
                </value>
                <value>
                    <fullName>PENDING_ENROLLMENT</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>NEVER_SERVED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_LDC__c.object
<CustomObject>
    <description>Junction Object between Opportunity and LDC</description>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>LDCOPPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity LDCs</relationshipLabel>
        <relationshipName>OpportunityLDCs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity LDC</label>
    <nameField>
        <displayFormat>OL-{0000000}</displayFormat>
        <label>Opportunity LDC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity LDCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/CreateMultipleOptyLDC.cls
/* 
 * Name: CreateMultipleOptyLDC
 * Type: Apex Class
 * Test Class: CreateMultipleOptyLDCTest
 * Description:  Allows Selecting Multiple Account LDC for Opportunity. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         03/13/2016       1. Initial Version created
 */
public with sharing class CreateMultipleOptyLDC {
 
    public String selectionId{get;set;}
    public ApexPages.StandardSetController setCon;
    public Set<Id> selectedIds;
    public Opportunity oppRec;
    public boolean resetHeader {get; set;}
    
    public CreateMultipleOptyLDC ()
    {
        Integer pageSize = 5;
        try{
            if(label.OpportunityLDCPageSize != null && label.OpportunityLDCPageSize != '' && label.OpportunityLDCPageSize != '0'){
                pageSize = (Integer.ValueOf(label.OpportunityLDCPageSize) < 50)?Integer.ValueOf(label.OpportunityLDCPageSize):50;
            }
        }
        catch (Exception ex){
            system.debug('>>> Invalid Value for Paging Size:' + label.OpportunityLDCPageSize);
        }
        List<Opportunity> lstOpp = [Select id, Name, AccountId, Service_Territory__c from Opportunity where id = :ApexPages.currentPage().getParameters().get('masterId')];
        if(!lstOpp.isEmpty()){
          oppRec = lstOpp[0];
          selectedIds= new Set<Id>();
          setCon= new ApexPages.StandardSetController(  [select Id, Name, Alias_Name__c,    LDC_Account_Status__c, LDC_Account_Number__c,  Service_Territory__c from LDC_Account__c where Account__c = :oppRec.AccountId AND Service_Territory__c = :oppRec.Service_Territory__c AND Id Not IN (select LDC_Account__c From Opportunity_LDC__c Where Opportunity__c = :oppRec.id) order by ldc_account_number__C ASC] );
          setCon.setpageNumber(1);
          setCon.setPageSize(pageSize);
          if(setCon.getResultSize() == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'No more LDC Accounts available to add'));
          }
        }
        else{
          oppRec = null;
        } 
        
    }
    
    public PageReference cancel() { 
        if(oppRec == null) return new PageReference('/');   
        return optyViewRedirect();
    }
    
    public PageReference save() {
        List<Opportunity_LDC__c> lstOptyLDC = new List<Opportunity_LDC__c>();
        for(ID selId : selectedIds){   
            Opportunity_LDC__c oRec = new Opportunity_LDC__c();
            oRec.LDC_Account__c = selId;
            oRec.Opportunity__c = oppRec.id;
            lstOptyLDC.add(oRec);                        
        }
        system.debug('>>> Inserting List: ' + lstOptyLDC);
        if(!lstOptyLDC.isEmpty()){
            insert lstOptyLDC;
        }
        
        if(oppRec == null) return new PageReference('/');
        return optyViewRedirect();
    }
    
    private PageReference optyViewRedirect(){
        PageReference opptyPage = new ApexPages.StandardController(oppRec).view();
        opptyPage.setRedirect(true);
        return opptyPage;
    }
    
    public void addSelectedId(){
        if(selectionId != null && selectionId != ''){
            system.debug('>>> Adding To Set :' + selectionId);
            selectedIds.add(selectionId);
            setHeaderValue();
        }
        else{
            system.debug('>>> Iterating Over Current Record set');
            for(sObject so : setCon.getRecords()){
                LDC_Account__c a = (LDC_Account__c)so;
                system.debug('>>> Checking for : ' + a.Id); 
                if(!selectedIds.contains(a.Id)){
                    system.debug('>>> Adding : ' + a.Id + ' TO : '+selectedIds);
                    selectedIds.add(a.Id);
                }
                else{
                    system.debug('>>> SET : ' + selectedIds + ' Allready Has : '+a.id);
                }
            }
        }
        
        system.debug('>>> Selection Set :' + selectedIds);  
 
    }

    public void removeSelectedId(){
        if(selectionId != null && selectionId != ''){
            system.debug('>>> Removing From Set :' + selectionId);
            selectedIds.remove(selectionId);
            setHeaderValue();
        }
        else{
            system.debug('>>> Iterating Over Current Record set');
            for(sObject so : setCon.getRecords()){
                LDC_Account__c a = (LDC_Account__c)so;
                system.debug('>>> Checking for : ' + a.Id); 
                if(!selectedIds.contains(a.Id)){
                    system.debug('>>> SET : ' + selectedIds + ' Do Not Have : '+a.id + ' Ignoring.....');
                }
                else{
                    system.debug('>>> SET : ' + selectedIds + ' Has : '+a.id + ' Removing this');
                    selectedIds.remove(a.id);
                }
            }
        }
        system.debug('>>> Selection Set :' + selectedIds);
    }
 
    public Integer getSelectedCount(){
 
        return selectedIds.size();
 
    }
 
    public void doNext(){
 
        if(setCon.getHasNext()){
            setCon.next();            
            setHeaderValue();
        }
            
    }
 
    public void doPrevious(){
 
        if(setCon.getHasPrevious()){
            setCon.previous();        
            setHeaderValue();
        }
    }
 
    public List<ldcAccountWrapper> getLDCAccounts(){
 
        List<ldcAccountWrapper> lstLDCAccWrapper = new List<ldcAccountWrapper>();
 
        for(sObject so : setCon.getRecords()){
            LDC_Account__c a = (LDC_Account__c)so;
 
            ldcAccountWrapper ldcWapper = new ldcAccountWrapper(a,false);
            if(selectedIds.contains(a.Id)){
                ldcWapper.IsSelected=true;
            }
            else{
                ldcWapper.IsSelected=false;
            }
            lstLDCAccWrapper.add(ldcWapper);
        }
 
        return lstLDCAccWrapper;
 
    }
 
    public Boolean getHasPrevious(){
 
        return setCon.getHasPrevious();
 
    }
 
    public Boolean getHasNext(){
 
        return setCon.getHasNext();
 
    }
 
    public Integer getPageNumber(){
 
        return setCon.getPageNumber();
 
    }
 
    public Integer getTotalPages(){
 
        Decimal totalSize = setCon.getResultSize();
        Decimal pageSize = setCon.getPageSize();
 
        Decimal pages = totalSize/pageSize;
 
        return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    
    public void setHeaderValue(){
        resetHeader = true;
        for(sObject so : setCon.getRecords()){
            LDC_Account__c a = (LDC_Account__c)so;              
            if(!selectedIds.contains(a.Id)){
                resetHeader = false;
                break;      
            }
        }
        
    }
 
    public with sharing class ldcAccountWrapper{
 
        public LDC_Account__c ldcAcc{get;set;}
        public Boolean IsSelected{get;set;}
 
        public ldcAccountWrapper(LDC_Account__c a, Boolean s){
            ldcAcc=a;
            IsSelected=s;
        }
 
    }
}