src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Blend &amp; Extend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Type__c</fullName>
        <label>Pricing Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Refresh</fullName>
                </value>
                <value>
                    <fullName>Addendum Account Add</fullName>
                </value>
                <value>
                    <fullName>Addendum Product Change</fullName>
                </value>
                <value>
                    <fullName>Addendum Block Purchase</fullName>
                </value>
                <value>
                    <fullName>Addendum % Energy Purchase</fullName>
                </value>
                <value>
                    <fullName>Amendment Extend Term</fullName>
                </value>
                <value>
                    <fullName>Amendment Drop Account</fullName>
                </value>
                <value>
                    <fullName>Renewal Evergreen</fullName>
                </value>
                <value>
                    <fullName>Renewal MTM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ABC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <recordTypes>
        <fullName>Indicative</fullName>
        <active>true</active>
        <label>Indicative</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Quote_History__c.object
<CustomObject>
    <description>Custom Quote History Object for Retail</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quote_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynegy_Quote_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retail Quote History</label>
    <nameField>
        <displayFormat>QH-{0000000}</displayFormat>
        <label>Retail Quote History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes History</pluralLabel>
    <recordTypes>
        <fullName>Executable</fullName>
        <active>true</active>
        <label>Executable</label>
    </recordTypes>
    <recordTypes>
        <fullName>Indicative</fullName>
        <active>true</active>
        <label>Indicative</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/ConstantUtility.cls
/* 
 * Name: ConstantUtility
 * Type: Apex Class
 * Test Class: Covered under the respective main classes
 * Description:  This class define various constants used accross the project. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         01/18/2016       1. Initial Version created
 */
public with sharing class ConstantUtility {
    public static final String ERR_NO_QUOTES = (label.No_Quotes_on_Opportunity !=null && label.No_Quotes_on_Opportunity != '')?label.No_Quotes_on_Opportunity:'Please add Quotes and request for price';
    public static final String ERR_PRICE_VALID = (label.Price_Still_Valid !=null && label.Price_Still_Valid != '')?label.Price_Still_Valid:'Price is still valid or waiting for Pricing System response';
    public static final String ERR_VALID_QUOTES_SUBMITTED = (label.Valid_Quotes_Submit !=null && label.Valid_Quotes_Submit != '')?label.Valid_Quotes_Submit:'All valid Quotes have been sent to Pricing System';
    public static final String ERR_INVALID_QUOTE_STATUS = (label.Invalid_Quote_Status !=null && label.Invalid_Quote_Status != '')?label.Invalid_Quote_Status:'Please add a Request Status to one of your Retail Quotes';
    public static final String ERR_CHECK_CREDIT_APPROVAL = (label.Credit_Check_Approval_Message !=null && label.Credit_Check_Approval_Message != '')?label.Credit_Check_Approval_Message:'Get the credit check approval before proceeding to creating an executable quote';
    public static final String ERR_NO_EXECUTABLE_QUOTES_AVAILABLE = (label.No_Quotes_available_for_Executable_Price !=null && label.No_Quotes_available_for_Executable_Price != '')?label.No_Quotes_available_for_Executable_Price:'Please add qualified quotes and then request for the Executable Price';
    public static final String STATUS_WAITING = 'Waiting on Load Data';
    public static final String STATUS_EXPIRED = 'Expired';
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_PRICING_COMPLETE = 'Pricing Complete';
    public static final String RT_INDICATIVE = 'Indicative';
    public static final String RT_EXECUTABLE = 'Executable';
    public static final String RT_OBJECT = 'Retail_Quote__c';
    public static final String RT_HIST_OBJECT = 'Retail_Quote_History__c';
    public static final string STATUS_SUCCESS='Success';
    public static final string STATUS_Failure='Failure';
    public static final string CUST_MUNI_REC_TYPE='Muni Agg Customer';
    public static final string CUST_CNI_REC_TYPE='C&I Customer';
    public static final string CUST_MASS_REC_TYPE='Mass Market Offer';
    
    public static Id getRecordTypeId(String sObj, String sRectypeName){
        List<RecordType> recTypeLst = [select id,name from RecordType where sobjectType =:sObj and name = :sRectypeName];
        return (!recTypeLst.isEmpty())?recTypeLst[0].id:null;
    }

    public static Id getRecordTypeIdbyName(string obj,String recTypeName){
        return Schema.getGlobalDescribe().get(obj).getDescribe().getRecordTypeInfosByName().get(recTypeName).getRecordTypeId();
    }
    
    public static String getObjectFieldsQuery(String selectedObject){
        String strQuery = ' Select ';
        Map<String, Schema.SObjectType> gdMap = Schema.getGlobalDescribe();
        Schema.Describesobjectresult dsr = gdMap.get(selectedObject).getDescribe();
        Map<String, Schema.SObjectField> fieldMap = dsr.fields.getMap();
        
        for(String strField : fieldMap.keySet()){
            strQuery += strField +',';
        }
        
        strQuery = strQuery.substring(0, strQuery.length() - 1);
        
        if(selectedObject == ConstantUtility.RT_OBJECT){
            strQuery +=',Product__r.Name'; 
            strQuery +=',Opportunity__r.name,Opportunity__r.Pricing_Type__c,Opportunity__r.Opportunity_Type__c,Opportunity__r.accountid,Opportunity__r.stagename,Opportunity__r.Service_Territory__c,Opportunity__r.Referral_Broker__c,opportunity__r.type ';  
        }
         
        return strQuery;        
    }
    
    public static sObject getObject(String sObjName, String objFields, ID objId){
        String strQuery = ' Select ';
        List<String> lstFields = new List<String>();
        lstFields = objFields.split(':');
        for(String strField : lstFields){
            strQuery += strField +',';
        }
        strQuery = strQuery.substring(0, strQuery.length() - 1);
        strQuery += ' FROM '+sObjName +' WHERE Id = :objId' ;
        
        List<sObject> lstObj = Database.query(strQuery);
        
        if(!lstObj.isEmpty()){
            return lstObj[0];
        }
        
        return null;
    }
    
    public static Boolean IsSobjectType(string objName,Id ObjId){
        return String.valueOf(ObjId.getSobjectType())==objName;
    }
    
    public static List<String> CheckDatabaseResults(Database.SaveResult[] results){
        List<string> errors=new List<string>();
        for (Database.SaveResult result : results) {
            if (!result.isSuccess()) {
                Database.Error[] errs = result.getErrors();
                for(Database.Error err : errs){
                    System.debug(err.getStatusCode() + ' - ' + err.getMessage());
                    Errors.add(err.getMessage());
                   }
            }
        }
        return errors;
    }
}