src/objects/Rate_Code__c.object
<CustomObject>
    <description>Object used for Utility Rate Codes</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territory</valueSetName>
        </valueSet>
    </fields>
    <label>Rate Code</label>
    <nameField>
        <label>Rate Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEPOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>DAYTON</fullName>
    </customValue>
    <customValue>
        <fullName>DEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEOHIO</fullName>
    </customValue>
    <customValue>
        <fullName>FEWP</fullName>
    </customValue>
    <customValue>
        <fullName>Ameren-IL</fullName>
    </customValue>
    <customValue>
        <fullName>ComEd-IL</fullName>
    </customValue>
    <customValue>
        <fullName>Duquesne - PA</fullName>
    </customValue>
    <customValue>
        <fullName>MetEd - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PECO - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penelec - PA</fullName>
    </customValue>
    <customValue>
        <fullName>PPL - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Penn Power - PA</fullName>
    </customValue>
    <customValue>
        <fullName>Pike County - PA</fullName>
    </customValue>
    <customValue>
        <fullName>UGI - PA</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>EVERE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>FGE - MA</fullName>
    </customValue>
    <customValue>
        <fullName>WMECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>NAN - MA</fullName>
    </customValue>
    <customValue>
        <fullName>MAELEC - MA</fullName>
    </customValue>
    <customValue>
        <fullName>BECO - MA</fullName>
    </customValue>
    <customValue>
        <fullName>COMM - MA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMB - MA</fullName>
    </customValue>
    <masterLabel>Service Territory</masterLabel>
</GlobalValueSet>

src/classes/SelectRateCodeControllerTest.cls
/* 
 * Name: SelectRateCodeControllerTest
 * Type: Test Class
 * Apex Class: SelectRateCodeController
 * Description: Test class for code coverage of SelectRateCodeController. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0        Sneha Gadde        03/18/2016       1. Initial Version created
 */
 
 @isTest(SeeAllData=false)
public class SelectRateCodeControllerTest {
private static testmethod void selectRateCode_UnitTest() 
 {
     Test.startTest();
       Rate_Code__c rc = new Rate_Code__c();
       rc.name  ='test rc';
       rc.Price__c = 100.00;
       rc.Service_Territory__c  = 'AEPOHIO';
       insert rc;
       ApexPages.currentPage().getParameters().put('serviceTeritory','AEPOHIO');
       ApexPages.currentPage().getParameters().put('quotePrice','100.00');
       
      SelectRateCodeController cntrl = new SelectRateCodeController();
      cntrl.searchRateCode();
      cntrl.getListItems();
      cntrl.setListSize(); 
      cntrl.Newratecode();
      cntrl.createratecode();
      cntrl.cancelcreateratecode();
      
      ApexPages.currentPage().getParameters().put('serviceTeritory','AEPOHIO');
      ApexPages.currentPage().getParameters().put('quotePrice','00.00');
       
      SelectRateCodeController cntrl1 = new SelectRateCodeController();
      cntrl1.searchRateCode(); 
    
     Test.stopTest();
 }  
 private static testmethod void selectRateCodeTest1()
 {
     Test.startTest();
       Rate_Code__c rc = new Rate_Code__c();
       rc.name  ='test rc';
       rc.Price__c = 15.2345;
       rc.Service_Territory__c  = 'AEPOHIO';
       insert rc;
       ApexPages.currentPage().getParameters().put('serviceTeritory','AEPOHIO');
       ApexPages.currentPage().getParameters().put('quotePrice','15');
       
      SelectRateCodeController cntrl = new SelectRateCodeController();
      cntrl.searchRateCode();
      cntrl.getListItems();
      cntrl.setListSize();  
    
     Test.stopTest();
 }     
    
 
    
}