src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Billing_Option__c</fullName>
        <label>Billing Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DUAL</fullName>
                </value>
                <value>
                    <fullName>SBO</fullName>
                </value>
                <value>
                    <fullName>UCB</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Broker_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Broker Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin_Allocation__c</fullName>
        <label>Index Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/MWh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin__c</fullName>
        <description>Changed from Text to Currency</description>
        <inlineHelpText>This field was previously labeled as &quot;Index Margin.&quot;  It was changed per ticket T-000122.</inlineHelpText>
        <label>Energy Adder Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin_Allocation__c</fullName>
        <label>Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>Term in Months</description>
        <label>Term (Whole Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Quote_History__c.object
<CustomObject>
    <description>Custom Quote History Object for Retail</description>
    <fields>
        <fullName>Broker_Fee__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Broker Fee</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UCBNONPOR</fullName>
                </value>
                <value>
                    <fullName>IEC</fullName>
                </value>
                <value>
                    <fullName>TIER_1_2</fullName>
                </value>
                <value>
                    <fullName>TIER_A</fullName>
                </value>
                <value>
                    <fullName>UCBPOR</fullName>
                </value>
                <value>
                    <fullName>UCBPOR_BR</fullName>
                </value>
                <value>
                    <fullName>WESA</fullName>
                </value>
                <value>
                    <fullName>GFEC</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - Evergreen</fullName>
                </value>
                <value>
                    <fullName>Small Stable Contract - MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Large Stable Contract</fullName>
                </value>
                <value>
                    <fullName>Large Stable PT-C Contract</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Block and Index</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin_Allocation__c</fullName>
        <label>Index Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Index_Margin__c</fullName>
        <label>Index Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin_Allocation__c</fullName>
        <label>Margin Allocation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$/Mwh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quote_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dynegy_Quote_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <description>Original Quote Number</description>
        <label>Quote Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>Term in Months</description>
        <label>Term</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Retail Quote History</label>
    <nameField>
        <displayFormat>QH-{0000000}</displayFormat>
        <label>Retail Quote History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetailQuoteHandler.cls
/* 
 * Name: RetailQuoteHandler
 * Type: Apex Class
 * Test Class: Covered under the respective main classes
 * Description:  This class contains the functions to assist with the Retail Quote realted modules. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0         Sreenivas Amirisetti         01/17/2016       1. Initial Version created
 */
public with sharing class RetailQuoteHandler {  
    
    public static List<Retail_Quote__c> cloneAndCreateQuoteHistory(List<Retail_Quote__c> lstRetQt, Set<Id> retQtToClone, String rtRecordType, String rtHistRecordType){
        Map<String, Schema.SObjectField> mapRetQtDescribe = schema.SObjectType.Retail_Quote__c.fields.getMap();
        Map<String, Schema.SObjectField> mapRetQtHistDescribe = schema.SObjectType.Retail_Quote_History__c.fields.getMap();
        List<Retail_Quote_History__c> lstRTQTHistToCreate = new List<Retail_Quote_History__c>();
        List<Retail_Quote__c> lstClonedRetQuotes = new List<Retail_Quote__c>();
        List<Retail_Quote__c> lstDeleteRetQuotes = new List<Retail_Quote__c>();
        ID rtRetQtId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_OBJECT,rtRecordType);
        ID rtRetQtHistId = ConstantUtility.getRecordTypeId(ConstantUtility.RT_HIST_OBJECT,rtHistRecordType);        
        
        for(Retail_Quote__c recRtQt : lstRetQt){
            Retail_Quote_History__c recRetQtHist = new Retail_Quote_History__c();
            //Loop through custom fields and copy to History record if matching field name is found
            for(String retQtField : mapRetQtDescribe.KeySet()){
                Schema.DescribeFieldResult describersult = mapRetQtDescribe.get(retQtField).getDescribe();
                if(describersult.isCustom() == false || describersult.isCreateable() == false){
                    continue;
                }
                else if(mapRetQtHistDescribe.containsKey(retQtField))
                {
                    recRetQtHist.put(retQtField, recRtQt.get(retQtField));
                }
            }
            //Add the standard fields to History record.
            recRetQtHist.Quote_Number__c = recRtQt.Name;
            recRetQtHist.RecordTypeId = rtRetQtHistId;
            
            lstRTQTHistToCreate.add(recRetQtHist);
            lstDeleteRetQuotes.add(recRtQt);

        }

        for(Retail_Quote__c rtq:[SELECT Id, Name, RecordTypeId, Product__c, Term__c, Opportunity__c, Utility_Settlement_Zone__c,billing_option__c, ContractType__c, Payment_Terms__c, Start_Term__c, Margin__c, Margin_Allocation__c, Index_Margin__c, Index_Margin_Allocation__c, Broker_Fee__c, Broker_Fee_Allocation__c, Municipality_Fee__c, Municipality_Fee_Allocation__c, Marketing_Cost__c, Marketing_Cost_Allocation__c, Energy_Fixed__c, Voluntary_REC__c, Voluntary_REC_Generator_Type__c, Voluntary_REC_Geographic_Location__c, Off_Peak_Block_Size__c, On_Peak_Block_Size__c FROM Retail_Quote__c where Id in :retQtToClone]){
                Retail_Quote__c clonedRetQuote = rtq.clone(false, false, false, false);
                clonedRetQuote.Request_Status__c = ConstantUtility.STATUS_WAITING;
                clonedRetQuote.RecordTypeId = rtRetQtId;
                lstClonedRetQuotes.add(clonedRetQuote); 
        }
        
        if(!lstClonedRetQuotes.isEmpty()){
            //In future we can use the srList to log any faliures in a custom way if the need be.
            Database.SaveResult[] srList = Database.insert(lstClonedRetQuotes, false);
        }
        if(!lstRTQTHistToCreate.isEmpty()){
            //In future we can use the srList to log any faliures in a custom way if the need be.
            Database.SaveResult[] srList = Database.insert(lstRTQTHistToCreate, false);
        }
        if(!lstDeleteRetQuotes.isEmpty()){
            //In future we can use the srList to log any faliures in a custom way if the need be.
            Database.DeleteResult[] srList = Database.delete(lstDeleteRetQuotes, false);
        }
        return lstClonedRetQuotes;
    }   

}