src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Notional_Value__c</fullName>
        <label>Notional Value</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailComponentClass.cls
public  class EmailComponentClass
{
    public Id opptyId {get;set;}
    public List<Retail_Quote__c> getretailQuotes()
    {    
        List<Retail_Quote__c> retailQuoteList;
        retailQuoteList = [SELECT id, name, Notional_Value__c FROM Retail_Quote__c WHERE opportunity__c=: opptyId and Notional_Value__c > = 10000000];
        system.debug('============retailQuoteList===='+retailQuoteList);
        return retailQuoteList;
        
    }
}