src/objects/Retail_Quote__c.object
<CustomObject>
    <description>Custom quote object for Retail</description>
    <fields>
        <fullName>Energy__c</fullName>
        <label>Energy</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Dynagy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Settlement_Zone__c</fullName>
        <label>Utility Settlement Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMIL.AEM.IL</fullName>
                </value>
                <value>
                    <fullName>COMED</fullName>
                </value>
                <value>
                    <fullName>DEOK_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>FEOH_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>AEPOHIO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DAY_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>APS_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>DUQ_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>METED_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PECO_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENELEC_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PENNPOWER_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>PPL_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>UGI_RESID_AGG</fullName>
                </value>
                <value>
                    <fullName>Z.NEMASSBOST</fullName>
                </value>
                <value>
                    <fullName>Z.SEMASS</fullName>
                </value>
                <value>
                    <fullName>Z.WCMASS</fullName>
                </value>
                <value>
                    <fullName>Z.CONNECTICUT</fullName>
                </value>
                <value>
                    <fullName>Z.MAINE</fullName>
                </value>
                <value>
                    <fullName>Z.NEWHAMPSHIRE</fullName>
                </value>
                <value>
                    <fullName>Z.VERMONT</fullName>
                </value>
                <value>
                    <fullName>Z.RHODEISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retail Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Quotes</pluralLabel>
    <recordTypes>
        <fullName>Indicative</fullName>
        <active>true</active>
        <label>Indicative</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RetailQuoteHandlerTest.cls
/* 
 * Name: RetailQuoteHandlerTest
 * Type: Test Class
 * Apex Class: RetailQuoteHandler
 * Description: Test class for code coverage of RetailQuoteHandler. 
 * Change History:
 *===================================================================================================================================
 * Version     Author                       Date             Description 
 * 1.0        Sneha Gadde        03/14/2016       1. Initial Version created
 */


@isTest(SeeAllData=false)
public class RetailQuoteHandlerTest {

    private static testmethod void RetailQuoteHandler_UnitTest()
    {
      Test.startTest();  
        Opportunity opp = new Opportunity();
       opp.name = 'Test Opp';
       opp.StageName = 'New';
       opp.CloseDate = date.today().addDays(5);
       insert opp;
       
       Retail_Quote__c rq = new Retail_Quote__c();
       rq.Opportunity__c = opp.id;
       rq.Energy__c = 5.8;   
       rq.Utility_Settlement_Zone__c = 'Test Utility';
       insert rq;
       set<id> rtQuoteIdLst = new set<Id>();
       rtQuoteIdLst.add(rq.id);
       List<Retail_Quote__c> rtQuoteLst = new List<Retail_Quote__c>();
       rtQuoteLst.add(rq);
       List<Retail_Quote__c> newRtQuoteLst = RetailQuoteHandler.cloneAndCreateQuoteHistory(rtQuoteLst,rtQuoteIdLst,'Indicative','Indicative');
       system.assertEquals(newRtQuoteLst.size(), 1); 
      Test.stopTest();  
    }
}