src/objects/State_Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>State Country</label>
</CustomObject>

src/classes/StateCountryUtil.cls
public class StateCountryUtil {
    public static string getStateCodeForVal(String stateName, String country)
    {
        String retVal;
        if(stateName == null || String.isEmpty(stateName))
        {
            return null;
        }
        for(State_Country__c tVal : State_Country__c.getall().values())
        {
            if(tVal.Value__c != null && tVal.Value__c.equalsIgnorecase(stateName) && tVal.Country__c != null && tVal.Country__c.equalsIgnorecase(country))
            {
                retVal = tVal.Code__c.toUpperCase();
                break;
            }
        }
        
        return retVal;
    }
    
}