src/objects/Supplier__c.object
<CustomObject>
    <description>Dynegy Billing Entity</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_DUNS__c</fullName>
        <description>This is needed to support EDI integration</description>
        <label>Master DUNS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_DUNS__c</fullName>
        <label>Supplier DUNS</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IntegrationUtil_Test.cls
@IsTest
private class IntegrationUtil_Test 
{
    @IsTest static void testValidator() 
    {
        Supplier__c        supplier = new Supplier__c();
        supplier.NAme ='Test supplier';
        supplier.Master_DUNS__c  ='1223';
        supplier.Supplier_DUNS__c ='999';
        supplier.Active__c = true;

        Supplier__c        supplier1 = new Supplier__c();
        supplier1.NAme ='Test supplier1';
        supplier1.Master_DUNS__c  ='12231';
        supplier1.Supplier_DUNS__c ='9991';
        supplier1.Active__c = true;        
        
        Database.SaveResult[] srInsert = database.insert(new List<Supplier__c>{supplier,supplier1},false);
        
        Database.UpsertResult[] srUpsert = database.upsert(new List<Supplier__c>{supplier,supplier1},false);
        
        IntegrationUtil.collectErrors(null);
        IntegrationUtil.collectErrors(srInsert);
        
        IntegrationUtil.generateDocId(System.now());
        IntegrationUtil.collectUpsertErrors(null);
        IntegrationUtil.collectUpsertErrors(srUpsert);
        IntegrationUtil.convertDateToString(system.today());
        IntegrationUtil.convertStringToDate('20160101');
        IntegrationUtil.convertStringToDate('2016-01-01');
        IntegrationUtil.convertStringToDate('201611');
        IntegrationUtil.convertStringToDate('201600');
        
        IntegrationUtil.convertTimeToString(System.now());
        IntegrationUtil.generateDateTime(System.now());
        IntegrationUtil.generateDate(System.now());
        IntegrationUtil.generateDocId(System.now());
        IntegrationUtil.generateRandomString(10);
        IntegrationUtil.generateTime(System.now());
        IntegrationUtil.remSpecialChars('2011-11-11');
        IntegrationUtil.remSpecialChars(null);
        
    }
}